import { LTX_EXTEND, quoted } from "#/utils";

export const config = {
  zone_mine_field: {
    [LTX_EXTEND]: "zone_base",
    GroupControlSection: "spawn_group_zone",
    $spawn: quoted("zones\\scenes\\mine_field"),
    $prefetch: 16,
    $def_sphere: 1.5,
    class: "Z_MBALD",
    accamulate_time: 100000,
    attenuation: 1,
    awaking_time: 10,
    blowout_explosion_time: 150,
    blowout_light: "on",
    blowout_light_time: 150,
    blowout_once: true,
    blowout_particles: "explosions\\explosion_mine",
    blowout_particles_time: 150,
    blowout_sound: "weapons\\f1_explode",
    blowout_sound_time: 150,
    blowout_time: 1000,
    blowout_wind: "on",
    blowout_wind_power: 0.5,
    blowout_wind_time_end: 1001,
    blowout_wind_time_peak: 200,
    blowout_wind_time_start: 150,
    disable_idle_time: -1,
    disable_time: -1,
    disable_time_small: -1,
    ef_anomaly_type: 1,
    ef_weapon_type: 13,
    effective_radius: 1.5,
    entrance_sound: "weapons\\mine_on",
    hit_impulse_scale: 0.15,
    hit_sound: "anomaly\\anomaly_gravy_hit1",
    hit_type: "explosion",
    idle_light: "off",
    idle_particles: "",
    ignore_artefacts: true,
    ignore_nonalive: false,
    ignore_small: true,
    light_color: [0.9, 0.9, 0.8],
    light_height: 1.5,
    light_range: 30.0,
    light_time: 0.3,
    max_start_power: 11.0,
    shape_edge_color: [32, 32, 32, 255],
    shape_transp_color: [255, 0, 0, 60],
  },
};
