import { LTX_INCLUDE } from "#/utils";

export const config = {
  [LTX_INCLUDE]: [
    "weapons\\delayed_action_fuse.ltx",
    "weapons\\upgrades_properties.ltx",

    "weapons\\upgrades\\w_abakan_up.ltx",
    "weapons\\upgrades\\w_ak74_up.ltx",
    "weapons\\upgrades\\w_ak74u_up.ltx",
    "weapons\\upgrades\\w_beretta_up.ltx",
    "weapons\\upgrades\\w_bm16_up.ltx",
    "weapons\\upgrades\\w_colt1911_up.ltx",
    "weapons\\upgrades\\w_desert_eagle_up.ltx",
    "weapons\\upgrades\\w_fn2000_up.ltx",
    "weapons\\upgrades\\w_fort_up.ltx",
    "weapons\\upgrades\\w_g36_up.ltx",
    "weapons\\upgrades\\w_groza_up.ltx",
    "weapons\\upgrades\\w_hpsa_up.ltx",
    "weapons\\upgrades\\w_l85_up.ltx",
    "weapons\\upgrades\\w_lr300_up.ltx",
    "weapons\\upgrades\\w_mp5_up.ltx",
    "weapons\\upgrades\\w_pb_up.ltx",
    "weapons\\upgrades\\w_pkm_up.ltx",
    "weapons\\upgrades\\w_pm_up.ltx",
    "weapons\\upgrades\\w_sig220_up.ltx",
    "weapons\\upgrades\\w_sig550_up.ltx",
    "weapons\\upgrades\\w_spas12_up.ltx",
    "weapons\\upgrades\\w_svd_up.ltx",
    "weapons\\upgrades\\w_svu_up.ltx",
    "weapons\\upgrades\\w_toz34_up.ltx",
    "weapons\\upgrades\\w_usp45_up.ltx",
    "weapons\\upgrades\\w_val_up.ltx",
    "weapons\\upgrades\\w_vintorez_up.ltx",
    "weapons\\upgrades\\w_walther_up.ltx",
    "weapons\\upgrades\\w_wincheaster1300_up.ltx",
    "weapons\\upgrades\\w_protecta_up.ltx",

    "misc\\outfit_upgrades\\o_novice_outfit_up.ltx",
    "misc\\outfit_upgrades\\o_stalker_outfit_up.ltx",
    "misc\\outfit_upgrades\\o_svoboda_light_outfit_up.ltx",
    "misc\\outfit_upgrades\\o_scientific_outfit_up.ltx",
    "misc\\outfit_upgrades\\o_cs_heavy_outfit_up.ltx",
    "misc\\outfit_upgrades\\o_dolg_outfit_up.ltx",
    "misc\\outfit_upgrades\\o_svoboda_heavy_outfit_up.ltx",
    "misc\\outfit_upgrades\\o_specops_outfit_up.ltx",
    "misc\\outfit_upgrades\\o_exo_outfit_up.ltx",
    "misc\\outfit_upgrades\\o_dolg_heavy_outfit_up.ltx",
    "misc\\outfit_upgrades\\o_military_outfit_up.ltx",

    "misc\\outfit_upgrades\\helm_battle_up.ltx",
    "misc\\outfit_upgrades\\helm_hardhat_up.ltx",
    "misc\\outfit_upgrades\\helm_protective_up.ltx",
    "misc\\outfit_upgrades\\helm_respirator_up.ltx",
    "misc\\outfit_upgrades\\helm_tactic_up.ltx",
  ],
};
