local LuaLogger = require("scripts.utils.logging").LuaLogger
local create_ts_class_instance = require("lualib_bundle").__TS__New
local log = create_ts_class_instance(LuaLogger, "_declaration");

log:info("Declaring globals")

-- ---------------------------------------------------------------------------------------------------------------------

require("scripts.core.db")

-- ---------------------------------------------------------------------------------------------------------------------

-- todo: Remove whole declarations file, should not be used after 100% TS migration

local coreCheckers = require("scripts.utils.checkers")
local coreTreasureManager = require("scripts.core.TreasureManager")

local utilsActor = require("scripts.utils.actor")
local utilsAlife = require("scripts.utils.alife")
local utilsConfigs = require("scripts.utils.configs")
local utilsControls = require("scripts.utils.controls")
local debugUtils = require("scripts.utils.debug")
local utilsGameSaves = require("scripts.utils.game_saves")
local utilsIds = require("scripts.utils.ids")

-- ---------------------------------------------------------------------------------------------------------------------

time_infinite = 100000000
mus_vol = 0
amb_vol = 0

-- ---------------------------------------------------------------------------------------------------------------------

getTreasureManager = coreTreasureManager.getTreasureManager

-- ---------------------------------------------------------------------------------------------------------------------

parse_names = utilsConfigs.parseNames

-- ---------------------------------------------------------------------------------------------------------------------

give_info = utilsActor.giveInfo
disable_info = utilsActor.disableInfo
has_alife_info = utilsActor.hasAlifeInfo

-- ---------------------------------------------------------------------------------------------------------------------

get_story_object = utilsAlife.getStoryObject
get_story_squad = utilsAlife.getStorySquad
action = utilsAlife.action;
character_community = utilsAlife.getCharacterCommunity

-- ---------------------------------------------------------------------------------------------------------------------

set_inactivate_input_time = utilsControls.setInactiveInputTime
abort = debugUtils.abort
set_save_marker = utilsGameSaves.setMarker

get_object_story_id = utilsIds.getObjectStoryId
get_story_object_id = utilsIds.getStoryObjectId

IsStalker = coreCheckers.isStalker

-- ---------------------------------------------------------------------------------------------------------------------

printf = function(fmt, ...)
end

-- ---

if time_global == nil then
  log:info("Mock time_global calls")

  local device_instance = device()

  time_global = function()
    return device_instance:time_global()
  end
end
