/* eslint sort-keys-fix/sort-keys-fix: "error"*/

export const animations = {
  acidic: "acidic.ppe",
  acidic_mine: "acidic_mine.ppe",
  alcohol: "alcohol.ppe",
  artefact_test_fireball_1_cam: "artefact_test_fireball_1_cam.anm",
  artefact_test_fireball_2_cam: "artefact_test_fireball_2_cam.anm",
  artefact_test_fireball_3_cam: "artefact_test_fireball_3_cam.anm",
  benchmarks_marsh_benchmark: "benchmarks\\marsh_benchmark.anm",
  black: "black.ppe",
  blink: "blink.ppe",
  brighten: "brighten.ppe",
  camera_effects_actor_move_down: "camera_effects\\actor_move\\down.anm",
  camera_effects_actor_move_go_back: "camera_effects\\actor_move\\go_back.anm",
  camera_effects_actor_move_go_front: "camera_effects\\actor_move\\go_front.anm",
  camera_effects_actor_move_jump: "camera_effects\\actor_move\\jump.anm",
  camera_effects_actor_move_strafe_left: "camera_effects\\actor_move\\strafe_left.anm",
  camera_effects_actor_move_strafe_right: "camera_effects\\actor_move\\strafe_right.anm",
  camera_effects_dream: "camera_effects\\dream.anm",
  camera_effects_drunk: "camera_effects\\drunk.anm",
  camera_effects_earthquake: "camera_effects\\earthquake.anm",
  camera_effects_earthquake_00: "camera_effects\\earthquake_00.anm",
  camera_effects_earthquake_1: "camera_effects\\earthquake_1.anm",
  camera_effects_earthquake_2: "camera_effects\\earthquake_2.anm",
  camera_effects_empty: "camera_effects\\empty.anm",
  camera_effects_fatigue: "camera_effects\\fatigue.anm",
  camera_effects_fireball: "camera_effects\\fireball.anm",
  camera_effects_fusker: "camera_effects\\fusker.anm",
  camera_effects_head_shot: "camera_effects\\head_shot.anm",
  camera_effects_hit_back: "camera_effects\\hit_back.anm",
  camera_effects_hit_back_left: "camera_effects\\hit_back_left.anm",
  camera_effects_hit_back_right: "camera_effects\\hit_back_right.anm",
  camera_effects_hit_front: "camera_effects\\hit_front.anm",
  camera_effects_hit_front_left: "camera_effects\\hit_front_left.anm",
  camera_effects_hit_front_right: "camera_effects\\hit_front_right.anm",
  camera_effects_hit_left: "camera_effects\\hit_left.anm",
  camera_effects_hit_right: "camera_effects\\hit_right.anm",
  camera_effects_pripyat_horror: "camera_effects\\pripyat_horror.anm",
  camera_effects_pripyat_horror1: "camera_effects\\pripyat_horror1.anm",
  camera_effects_scenario_cam_jupiter_jup_a9_actor_conservation_info_cam:
    "camera_effects\\scenario_cam\\jupiter\\jup_a9_actor_conservation_info_cam.anm",
  camera_effects_scenario_cam_jupiter_jup_a9_actor_power_info_cam:
    "camera_effects\\scenario_cam\\jupiter\\jup_a9_actor_power_info_cam.anm",
  camera_effects_scenario_cam_jupiter_jup_a9_actor_way_info_cam:
    "camera_effects\\scenario_cam\\jupiter\\jup_a9_actor_way_info_cam.anm",
  camera_effects_scenario_cam_jupiter_jup_b15_sleep: "camera_effects\\scenario_cam\\jupiter\\jup_b15_sleep.anm",
  camera_effects_scenario_cam_jupiter_jup_b15_wake_up: "camera_effects\\scenario_cam\\jupiter\\jup_b15_wake_up.anm",
  camera_effects_scenario_cam_jupiter_jup_b19_waiting_for_mercs:
    "camera_effects\\scenario_cam\\jupiter\\jup_b19_waiting_for_mercs.anm",
  camera_effects_scenario_cam_jupiter_jup_b1_fireball_cam:
    "camera_effects\\scenario_cam\\jupiter\\jup_b1_fireball_cam.anm",
  camera_effects_scenario_cam_jupiter_jup_b213: "camera_effects\\scenario_cam\\jupiter\\jup_b213.anm",
  camera_effects_scenario_cam_jupiter_jup_b217_camera_effector:
    "camera_effects\\scenario_cam\\jupiter\\jup_b217_camera_effector.anm",
  camera_effects_scenario_cam_jupiter_jup_b217_welcome_cameff:
    "camera_effects\\scenario_cam\\jupiter\\jup_b217_welcome_cameff.anm",
  camera_effects_scenario_cam_jupiter_jup_b219_cam_1: "camera_effects\\scenario_cam\\jupiter\\jup_b219_cam_1.anm",
  camera_effects_scenario_cam_jupiter_jup_b219_cam_10: "camera_effects\\scenario_cam\\jupiter\\jup_b219_cam_10.anm",
  camera_effects_scenario_cam_jupiter_jup_b219_cam_2: "camera_effects\\scenario_cam\\jupiter\\jup_b219_cam_2.anm",
  camera_effects_scenario_cam_jupiter_jup_b219_cam_3: "camera_effects\\scenario_cam\\jupiter\\jup_b219_cam_3.anm",
  camera_effects_scenario_cam_jupiter_jup_b219_cam_4: "camera_effects\\scenario_cam\\jupiter\\jup_b219_cam_4.anm",
  camera_effects_scenario_cam_jupiter_jup_b219_cam_5: "camera_effects\\scenario_cam\\jupiter\\jup_b219_cam_5.anm",
  camera_effects_scenario_cam_jupiter_jup_b219_cam_6: "camera_effects\\scenario_cam\\jupiter\\jup_b219_cam_6.anm",
  camera_effects_scenario_cam_jupiter_jup_b219_cam_7: "camera_effects\\scenario_cam\\jupiter\\jup_b219_cam_7.anm",
  camera_effects_scenario_cam_jupiter_jup_b219_cam_8: "camera_effects\\scenario_cam\\jupiter\\jup_b219_cam_8.anm",
  camera_effects_scenario_cam_jupiter_jup_b219_cam_9: "camera_effects\\scenario_cam\\jupiter\\jup_b219_cam_9.anm",
  camera_effects_scenario_cam_jupiter_jup_b219_descent_camera:
    "camera_effects\\scenario_cam\\jupiter\\jup_b219_descent_camera.anm",
  camera_effects_scenario_cam_jupiter_jup_b8_heli_4_camera:
    "camera_effects\\scenario_cam\\jupiter\\jup_b8_heli_4_camera.anm",
  camera_effects_scenario_cam_jupiter_jup_b9_heli_1_camera:
    "camera_effects\\scenario_cam\\jupiter\\jup_b9_heli_1_camera.anm",
  camera_effects_scenario_cam_pripyat_labx8_electro_fireball:
    "camera_effects\\scenario_cam\\pripyat\\labx8_electro_fireball.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_01: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_01.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_02: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_02.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_03: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_03.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_04: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_04.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_05: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_05.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_06: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_06.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_07: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_07.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_08: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_08.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_09: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_09.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_10: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_10.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_11: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_11.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_12: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_12.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_13: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_13.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_14: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_14.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_15: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_15.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_16: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_16.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_17: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_17.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_17_1: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_17_1.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_18: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_18.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_19: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_19.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_20: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_20.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_21: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_21.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_22: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_22.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_23: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_23.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_24: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_24.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_25: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_25.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_25_1: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_25_1.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_26: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_26.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_27: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_27.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_28: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_28.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_29: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_29.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_30: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_30.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_31: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_31.anm",
  camera_effects_scenario_cam_pripyat_pri_a15_cam_32: "camera_effects\\scenario_cam\\pripyat\\pri_a15_cam_32.anm",
  camera_effects_scenario_cam_pripyat_pri_a18_inspect_monolith_cameff:
    "camera_effects\\scenario_cam\\pripyat\\pri_a18_inspect_monolith_cameff.anm",
  camera_effects_scenario_cam_pripyat_pri_a20_dead_recon_squad:
    "camera_effects\\scenario_cam\\pripyat\\pri_a20_dead_recon_squad.anm",
  camera_effects_scenario_cam_pripyat_pri_a20_recon_squad_comm:
    "camera_effects\\scenario_cam\\pripyat\\pri_a20_recon_squad_comm.anm",
  camera_effects_scenario_cam_pripyat_pri_a21_scene_end_cam:
    "camera_effects\\scenario_cam\\pripyat\\pri_a21_scene_end_cam.anm",
  camera_effects_scenario_cam_pripyat_pri_a22_give_task: "camera_effects\\scenario_cam\\pripyat\\pri_a22_give_task.anm",
  camera_effects_scenario_cam_pripyat_pri_a22_radio_camera:
    "camera_effects\\scenario_cam\\pripyat\\pri_a22_radio_camera.anm",
  camera_effects_scenario_cam_pripyat_pri_a25_find_door_without_explosive_cameff:
    "camera_effects\\scenario_cam\\pripyat\\pri_a25_find_door_without_explosive_cameff.anm",
  camera_effects_scenario_cam_pripyat_pri_a28_evac_cam_1:
    "camera_effects\\scenario_cam\\pripyat\\pri_a28_evac_cam_1.anm",
  camera_effects_scenario_cam_pripyat_pri_a28_evac_cam_heli:
    "camera_effects\\scenario_cam\\pripyat\\pri_a28_evac_cam_heli.anm",
  camera_effects_scenario_cam_pripyat_pri_a28_ssu_communication_camera:
    "camera_effects\\scenario_cam\\pripyat\\pri_a28_ssu_communication_camera.anm",
  camera_effects_scenario_cam_pripyat_pri_b302_fireball_acidic_cam:
    "camera_effects\\scenario_cam\\pripyat\\pri_b302_fireball_acidic_cam.anm",
  camera_effects_scenario_cam_pripyat_pri_b304_fireball_cam:
    "camera_effects\\scenario_cam\\pripyat\\pri_b304_fireball_cam.anm",
  camera_effects_scenario_cam_pripyat_pri_b305_catscene_1_medik_back:
    "camera_effects\\scenario_cam\\pripyat\\pri_b305_catscene_1_medik_back.anm",
  camera_effects_scenario_cam_pripyat_pri_b305_catscene_2_dialog_with_kovalsky:
    "camera_effects\\scenario_cam\\pripyat\\pri_b305_catscene_2_dialog_with_kovalsky.anm",
  camera_effects_scenario_cam_pripyat_pri_b305_catscene_2_dialog_with_kovalsky_01:
    "camera_effects\\scenario_cam\\pripyat\\pri_b305_catscene_2_dialog_with_kovalsky_01.anm",
  camera_effects_scenario_cam_pripyat_pri_b305_catscene_2_dialog_with_kovalsky_02:
    "camera_effects\\scenario_cam\\pripyat\\pri_b305_catscene_2_dialog_with_kovalsky_02.anm",
  camera_effects_scenario_cam_pripyat_pri_b305_catscene_3_lost_signal:
    "camera_effects\\scenario_cam\\pripyat\\pri_b305_catscene_3_lost_signal.anm",
  camera_effects_scenario_cam_pripyat_pri_b305_catscene_4_strelok_came:
    "camera_effects\\scenario_cam\\pripyat\\pri_b305_catscene_4_strelok_came.anm",
  camera_effects_scenario_cam_pripyat_pri_b305_catscene_5_dialog_with_strelok:
    "camera_effects\\scenario_cam\\pripyat\\pri_b305_catscene_5_dialog_with_strelok.anm",
  camera_effects_scenario_cam_pripyat_pri_b305_catscene_5_dialog_with_strelok_1:
    "camera_effects\\scenario_cam\\pripyat\\pri_b305_catscene_5_dialog_with_strelok_1.anm",
  camera_effects_scenario_cam_pripyat_pri_b305_catscene_5_dialog_with_strelok_2:
    "camera_effects\\scenario_cam\\pripyat\\pri_b305_catscene_5_dialog_with_strelok_2.anm",
  camera_effects_scenario_cam_pripyat_pri_b307_fireball_1:
    "camera_effects\\scenario_cam\\pripyat\\pri_b307_fireball_1.anm",
  camera_effects_scenario_cam_pripyat_pri_b307_fireball_2:
    "camera_effects\\scenario_cam\\pripyat\\pri_b307_fireball_2.anm",
  camera_effects_scenario_cam_pripyat_pri_b307_fireball_3:
    "camera_effects\\scenario_cam\\pripyat\\pri_b307_fireball_3.anm",
  camera_effects_scenario_cam_zaton_zat_a23_documents_cam:
    "camera_effects\\scenario_cam\\zaton\\zat_a23_documents_cam.anm",
  camera_effects_scenario_cam_zaton_zat_b100_heli_2_camera:
    "camera_effects\\scenario_cam\\zaton\\zat_b100_heli_2_camera.anm",
  camera_effects_scenario_cam_zaton_zat_b101_heli_5_camera:
    "camera_effects\\scenario_cam\\zaton\\zat_b101_heli_5_camera.anm",
  camera_effects_scenario_cam_zaton_zat_b14_robbery: "camera_effects\\scenario_cam\\zaton\\zat_b14_robbery.anm",
  camera_effects_scenario_cam_zaton_zat_b20_teleport_dive:
    "camera_effects\\scenario_cam\\zaton\\zat_b20_teleport_dive.anm",
  camera_effects_scenario_cam_zaton_zat_b28_heli3_camera:
    "camera_effects\\scenario_cam\\zaton\\zat_b28_heli3_camera.anm",
  camera_effects_scenario_cam_zaton_zat_b44_fireball_1_cam:
    "camera_effects\\scenario_cam\\zaton\\zat_b44_fireball_1_cam.anm",
  camera_effects_scenario_cam_zaton_zat_b44_fireball_2_cam:
    "camera_effects\\scenario_cam\\zaton\\zat_b44_fireball_2_cam.anm",
  camera_effects_scenario_cam_zaton_zat_b5_from_bandits: "camera_effects\\scenario_cam\\zaton\\zat_b5_from_bandits.anm",
  camera_effects_scenario_cam_zaton_zat_b5_from_stalkers:
    "camera_effects\\scenario_cam\\zaton\\zat_b5_from_stalkers.anm",
  camera_effects_scenario_cam_zaton_zaton_b54_01: "camera_effects\\scenario_cam\\zaton\\zaton_b54_01.anm",
  camera_effects_scenario_cam_zaton_zaton_b56_01: "camera_effects\\scenario_cam\\zaton\\zaton_b56_01.anm",
  camera_effects_scenario_cam_zaton_zaton_b56_02: "camera_effects\\scenario_cam\\zaton\\zaton_b56_02.anm",
  camera_effects_shell_shock: "camera_effects\\shell_shock.anm",
  camera_effects_sleep: "camera_effects\\sleep.anm",
  camera_effects_surge_01: "camera_effects\\surge_01.anm",
  camera_effects_surge_02: "camera_effects\\surge_02.anm",
  camera_effects_weapon_abakan_idle_bore: "camera_effects\\weapon\\abakan_idle_bore.anm1",
  camera_effects_weapon_abakan_idle_bore2: "camera_effects\\weapon\\abakan_idle_bore2.anm1",
  camera_effects_weapon_abakan_reload: "camera_effects\\weapon\\abakan_reload.anm",
  camera_effects_weapon_abakan_reload_grenade: "camera_effects\\weapon\\abakan_reload_grenade.anm",
  camera_effects_weapon_abakan_reload_w_gl: "camera_effects\\weapon\\abakan_reload_w_gl.anm",
  camera_effects_weapon_abakan_shoot: "camera_effects\\weapon\\abakan_shoot.anm",
  camera_effects_weapon_abakan_switch_off: "camera_effects\\weapon\\abakan_switch_off.anm",
  camera_effects_weapon_abakan_switch_on: "camera_effects\\weapon\\abakan_switch_on.anm",
  camera_effects_weapon_ak74_idle_bore: "camera_effects\\weapon\\ak74_idle_bore.anm1",
  camera_effects_weapon_ak74_idle_bore2: "camera_effects\\weapon\\ak74_idle_bore2.anm1",
  camera_effects_weapon_ak74_reload: "camera_effects\\weapon\\ak74_reload.anm",
  camera_effects_weapon_ak74_reload_grenade: "camera_effects\\weapon\\ak74_reload_grenade.anm",
  camera_effects_weapon_ak74_reload_w_gl: "camera_effects\\weapon\\ak74_reload_w_gl.anm",
  camera_effects_weapon_ak74_shoot: "camera_effects\\weapon\\ak74_shoot.anm",
  camera_effects_weapon_ak74_switch_off: "camera_effects\\weapon\\ak74_switch_off.anm",
  camera_effects_weapon_ak74_switch_on: "camera_effects\\weapon\\ak74_switch_on.anm",
  camera_effects_weapon_ak74u_reload: "camera_effects\\weapon\\ak74u_reload.anm",
  camera_effects_weapon_ak74u_shoot: "camera_effects\\weapon\\ak74u_shoot.anm",
  camera_effects_weapon_beretta_reload: "camera_effects\\weapon\\beretta_reload.anm",
  camera_effects_weapon_bm16_reload_l: "camera_effects\\weapon\\bm16_reload_l.anm",
  camera_effects_weapon_bm16_reload_lr: "camera_effects\\weapon\\bm16_reload_lr.anm",
  camera_effects_weapon_bm16_shoot_l: "camera_effects\\weapon\\bm16_shoot_l.anm",
  camera_effects_weapon_bm16_shoot_r: "camera_effects\\weapon\\bm16_shoot_r.anm",
  camera_effects_weapon_colt1911_reload: "camera_effects\\weapon\\colt1911_reload.anm",
  camera_effects_weapon_desert_eagle_reload: "camera_effects\\weapon\\desert_eagle_reload.anm",
  camera_effects_weapon_fn_2000_idle_bore: "camera_effects\\weapon\\fn_2000_idle_bore.anm1",
  camera_effects_weapon_fn_2000_idle_bore2: "camera_effects\\weapon\\fn_2000_idle_bore2.anm1",
  camera_effects_weapon_fn_2000_reload: "camera_effects\\weapon\\fn_2000_reload.anm",
  camera_effects_weapon_fn_2000_reload_grenade: "camera_effects\\weapon\\fn_2000_reload_grenade.anm",
  camera_effects_weapon_fn_2000_reload_w_gl: "camera_effects\\weapon\\fn_2000_reload_w_gl.anm",
  camera_effects_weapon_fn_2000_shoot: "camera_effects\\weapon\\fn_2000_shoot.anm",
  camera_effects_weapon_fn_2000_switch_off: "camera_effects\\weapon\\fn_2000_switch_off.anm",
  camera_effects_weapon_fn_2000_switch_on: "camera_effects\\weapon\\fn_2000_switch_on.anm",
  camera_effects_weapon_fort_reload: "camera_effects\\weapon\\fort_reload.anm",
  camera_effects_weapon_g36_reload: "camera_effects\\weapon\\g36_reload.anm1",
  camera_effects_weapon_g36_reload_grenade: "camera_effects\\weapon\\g36_reload_grenade.anm",
  camera_effects_weapon_g36_reload_w_gl: "camera_effects\\weapon\\g36_reload_w_gl.anm",
  camera_effects_weapon_g36_switch_off: "camera_effects\\weapon\\g36_switch_off.anm",
  camera_effects_weapon_g36_switch_on: "camera_effects\\weapon\\g36_switch_on.anm",
  camera_effects_weapon_groza_reload: "camera_effects\\weapon\\groza_reload.anm",
  camera_effects_weapon_groza_reload_grenade: "camera_effects\\weapon\\groza_reload_grenade.anm",
  camera_effects_weapon_groza_reload_w_gl: "camera_effects\\weapon\\groza_reload_w_gl.anm",
  camera_effects_weapon_groza_shoot: "camera_effects\\weapon\\groza_shoot.anm",
  camera_effects_weapon_groza_switch_off: "camera_effects\\weapon\\groza_switch_off.anm",
  camera_effects_weapon_groza_switch_on: "camera_effects\\weapon\\groza_switch_on.anm",
  camera_effects_weapon_hpsa_reload: "camera_effects\\weapon\\hpsa_reload.anm",
  camera_effects_weapon_knife_idle_bore: "camera_effects\\weapon\\knife_idle_bore.anm1",
  camera_effects_weapon_knife_kick_start1: "camera_effects\\weapon\\knife_kick_start1.anm",
  camera_effects_weapon_knife_kick_start2: "camera_effects\\weapon\\knife_kick_start2.anm",
  camera_effects_weapon_l85_idle_bore: "camera_effects\\weapon\\l85_idle_bore.anm1",
  camera_effects_weapon_l85_idle_bore2: "camera_effects\\weapon\\l85_idle_bore2.anm1",
  camera_effects_weapon_l85_reload: "camera_effects\\weapon\\l85_reload.anm",
  camera_effects_weapon_l85_reload_grenade: "camera_effects\\weapon\\l85_reload_grenade.anm",
  camera_effects_weapon_l85_reload_w_gl: "camera_effects\\weapon\\l85_reload_w_gl.anm",
  camera_effects_weapon_l85_shoot: "camera_effects\\weapon\\l85_shoot.anm",
  camera_effects_weapon_l85_switch_off: "camera_effects\\weapon\\l85_switch_off.anm",
  camera_effects_weapon_l85_switch_on: "camera_effects\\weapon\\l85_switch_on.anm",
  camera_effects_weapon_lr300_reload: "camera_effects\\weapon\\lr300_reload.anm",
  camera_effects_weapon_lr300_reload_grenade: "camera_effects\\weapon\\lr300_reload_grenade.anm",
  camera_effects_weapon_lr300_reload_w_gl: "camera_effects\\weapon\\lr300_reload_w_gl.anm",
  camera_effects_weapon_lr300_shoot: "camera_effects\\weapon\\lr300_shoot.anm",
  camera_effects_weapon_lr300_switch_off: "camera_effects\\weapon\\lr300_switch_off.anm",
  camera_effects_weapon_lr300_switch_on: "camera_effects\\weapon\\lr300_switch_on.anm",
  camera_effects_weapon_mp5_reload: "camera_effects\\weapon\\mp5_reload.anm",
  camera_effects_weapon_mp5_shoot: "camera_effects\\weapon\\mp5_shoot.anm",
  camera_effects_weapon_pb_reload: "camera_effects\\weapon\\pb_reload.anm",
  camera_effects_weapon_pkm_reload: "camera_effects\\weapon\\pkm_reload.anm",
  camera_effects_weapon_pm_reload: "camera_effects\\weapon\\pm_reload.anm",
  camera_effects_weapon_sig220_reload: "camera_effects\\weapon\\sig220_reload.anm",
  camera_effects_weapon_sig550_idle_bore: "camera_effects\\weapon\\sig550_idle_bore.anm1",
  camera_effects_weapon_sig550_idle_bore2: "camera_effects\\weapon\\sig550_idle_bore2.anm1",
  camera_effects_weapon_sig550_reload: "camera_effects\\weapon\\sig550_reload.anm",
  camera_effects_weapon_sig550_reload_grenade: "camera_effects\\weapon\\sig550_reload_grenade.anm",
  camera_effects_weapon_sig550_reload_w_gl: "camera_effects\\weapon\\sig550_reload_w_gl.anm",
  camera_effects_weapon_sig550_shoot: "camera_effects\\weapon\\sig550_shoot.anm",
  camera_effects_weapon_sig550_switch_off: "camera_effects\\weapon\\sig550_switch_off.anm",
  camera_effects_weapon_sig550_switch_on: "camera_effects\\weapon\\sig550_switch_on.anm",
  camera_effects_weapon_spas12_reload: "camera_effects\\weapon\\spas12_reload.anm1",
  camera_effects_weapon_svd_idle_bore: "camera_effects\\weapon\\svd_idle_bore.anm1",
  camera_effects_weapon_svd_idle_bore2: "camera_effects\\weapon\\svd_idle_bore2.anm1",
  camera_effects_weapon_toz_reload_l: "camera_effects\\weapon\\toz_reload_l.anm",
  camera_effects_weapon_toz_reload_lr: "camera_effects\\weapon\\toz_reload_lr.anm",
  camera_effects_weapon_usp45_reload: "camera_effects\\weapon\\usp45_reload.anm",
  camera_effects_weapon_val_reload: "camera_effects\\weapon\\val_reload.anm",
  camera_effects_weapon_vintorez_reload: "camera_effects\\weapon\\vintorez_reload.anm",
  camera_effects_weapon_walter99_reload: "camera_effects\\weapon\\walter99_reload.anm",
  camera_effects_weapon_winchester1300_reload: "camera_effects\\weapon\\winchester1300_reload.anm1",
  contrast: "contrast.ppe",
  controller_hit: "controller_hit.ppe",
  deimos: "deimos.ppe",
  deimos1: "deimos1.ppe",
  electra: "electra.ppe",
  electra_mine: "electra_mine.ppe",
  fade_in: "fade_in.ppe",
  fade_in_out: "fade_in_out.ppe",
  fade_to_black_9_sec: "fade_to_black_9_sec.ppe",
  fire_hit: "fire_hit.ppe",
  flame: "flame.ppe",
  fuzz: "fuzz.ppe",
  gravi: "gravi.ppe",
  gravi_mine: "gravi_mine.ppe",
  helicopter_aaa: "helicopter\\aaa.anm",
  mosquito_bald: "mosquito_bald.ppe",
  nightvision_1: "nightvision_1.ppe",
  nightvision_2: "nightvision_2.ppe",
  nightvision_3: "nightvision_3.ppe",
  nil: "nil.ppe",
  pas_b400_acidic: "pas_b400_acidic.ppe",
  poltergeist_scan: "poltergeist_scan.ppe",
  psi: "psi.ppe",
  psy_antenna: "psy_antenna.ppe",
  psychic: "psychic.ppe",
  radiation: "radiation.ppe",
  sleep_fade: "sleep_fade.ppe",
  snd_shock: "snd_shock.ppe",
  steam_mine: "steam_mine.ppe",
  surge_fade: "surge_fade.ppe",
  surge_shock: "surge_shock.ppe",
  surge_shock_old: "surge_shock_old.ppe",
  teleport: "teleport.ppe",
  thermal: "thermal.ppe",
  thermal_mine: "thermal_mine.ppe"
} as const;

export type TAnimations = typeof animations;

export type TAnimation = TAnimations[keyof TAnimations];
