/* eslint sort-keys-fix/sort-keys-fix: "error"*/

/**
 * Translation enum captions.
 * todo: Include all translations, build translation collecting script.
 */
export const captions = {
  st_jup_a10_name: "st_jup_a10_name",
  st_jup_a12_name: "st_jup_a12_name",
  st_jup_a6_name: "st_jup_a6_name",
  st_jup_a9_name: "st_jup_a9_name",
  st_jup_b19_name: "st_jup_b19_name",
  st_jup_b1_name: "st_jup_b1_name",
  st_jup_b200_name: "st_jup_b200_name",
  st_jup_b201_name: "st_jup_b201_name",
  st_jup_b202_name: "st_jup_b202_name",
  st_jup_b205_name: "st_jup_b205_name",
  st_jup_b206_name: "st_jup_b206_name",
  st_jup_b208_name: "st_jup_b208_name",
  st_jup_b209_name: "st_jup_b209_name",
  st_jup_b211_name: "st_jup_b211_name",
  st_jup_b212_name: "st_jup_b212_name",
  st_jup_b25_name: "st_jup_b25_name",
  st_jup_b32_has_af: "st_jup_b32_has_af",
  st_jup_b32_name: "st_jup_b32_name",
  st_jup_b32_no_af: "st_jup_b32_no_af",
  st_jup_b46_name: "st_jup_b46_name",
  st_jup_b6_name: "st_jup_b6_name",
  st_jup_b9_name: "st_jup_b9_name",
  st_pri_a16_name: "st_pri_a16_name",
  st_pri_a17_name: "st_pri_a17_name",
  st_pri_a18_name: "st_pri_a18_name ",
  st_pri_a21_name: "st_pri_a21_name",
  st_pri_a25_name: "st_pri_a25_name",
  st_pri_a28_name: "st_pri_a28_name",
  st_pri_b301_name: "st_pri_b301_name",
  st_pri_b303_name: "st_pri_b303_name",
  st_pri_b304_name: "st_pri_b304_name",
  st_pri_b306_name: "st_pri_b306_name",
  st_pri_b35_name: "st_pri_b35_name",
  st_pri_b36_name: "st_pri_b36_name",
  st_sleep_hours: "st_sleep_hours",
  st_ui_pda_legend_mechanic: "st_ui_pda_legend_mechanic",
  st_ui_pda_legend_medic: "st_ui_pda_legend_medic",
  st_ui_pda_legend_scout: "st_ui_pda_legend_scout",
  st_ui_pda_legend_trader: "st_ui_pda_legend_trader",
  st_ui_pda_legend_vip: "st_ui_pda_legend_vip",
  st_ui_pda_sleep_place: "st_ui_pda_sleep_place",
  st_zat_a2_name: "st_zat_a2_name",
  st_zat_b100_name: "st_zat_b100_name",
  st_zat_b101_name: "st_zat_b101_name",
  st_zat_b103_name: "st_zat_b103_name",
  st_zat_b104_name: "st_zat_b104_name",
  st_zat_b106_name: "st_zat_b106_name",
  st_zat_b12_name: "st_zat_b12_name",
  st_zat_b14_name: "st_zat_b14_name",
  st_zat_b18_name: "st_zat_b18_name",
  st_zat_b20_name: "st_zat_b20_name",
  st_zat_b28_name: "st_zat_b28_name",
  st_zat_b33_name: "st_zat_b33_name",
  st_zat_b38_name: "st_zat_b38_name",
  st_zat_b39_name: "st_zat_b39_name",
  st_zat_b40_name: "st_zat_b40_name",
  st_zat_b52_name: "st_zat_b52_name",
  st_zat_b53_name: "st_zat_b53_name",
  st_zat_b54_name: "st_zat_b54_name",
  st_zat_b55_name: "st_zat_b55_name",
  st_zat_b56_name: "st_zat_b56_name",
  st_zat_b5_name: "st_zat_b5_name",
  st_zat_b7_name: "st_zat_b7_name",
  ui_mm_back: "ui_mm_back",
  ui_mm_cancel: "ui_mm_cancel",
  ui_mm_credits: "ui_mm_credits",
  ui_mm_debug_tools: "ui_mm_debug_tools",
  ui_mm_disconnect: "ui_mm_disconnect",
  ui_mm_last_save: "ui_mm_last_save",
  ui_mm_load_game: "ui_mm_load_game",
  ui_mm_logout: "ui_mm_logout",
  ui_mm_master: "ui_mm_master",
  ui_mm_network_game: "ui_mm_network_game",
  ui_mm_newgame: "ui_mm_newgame",
  ui_mm_novice: "ui_mm_novice",
  ui_mm_options_n: "ui_mm_options_n",
  ui_mm_quit2windows: "ui_mm_quit2windows",
  ui_mm_quit_game: "ui_mm_quit_game",
  ui_mm_return_game: "ui_mm_return_game",
  ui_mm_save_game: "ui_mm_save_game",
  ui_mm_stalker: "ui_mm_stalker",
  ui_mm_veteran: "ui_mm_veteran",
  ui_mp_internet: "ui_mp_internet",
  ui_mp_localnet: "ui_mp_localnet"
};
