/* eslint sort-keys-fix/sort-keys-fix: "error"*/

// todo: Probably separate for quests and generic.
export const info_portions = {
  actor_information_dealer: "actor_information_dealer",
  actor_is_sleeping: "actor_is_sleeping",
  actor_marked_by_zone_3_times: "actor_marked_by_zone_3_times",
  actor_was_in_many_bad_places: "actor_was_in_many_bad_places",
  actor_wealthy: "actor_wealthy",
  balance_advocate_gained: "balance_advocate_gained",
  battle_systems_master_achievement_gained: "battle_systems_master_achievement_gained",
  detective_achievement_gained: "detective_achievement_gained",
  diplomat_achievement_gained: "diplomat_achievement_gained",
  herald_of_justice_achievement_gained: "herald_of_justice_achievement_gained",
  high_tech_master_achievement_gained: "high_tech_master_achievement_gained",
  /**
   * Info up.
   */
  info_up_a_novice_outfit: "info_up_a_novice_outfit",
  info_up_ab_pkm: "info_up_ab_pkm",
  info_up_ab_svu: "info_up_ab_svu",
  info_up_abcd_pkm: "info_up_abcd_pkm",
  info_up_abcd_svu: "info_up_abcd_svu",
  info_up_ac_ak74u: "info_up_ac_ak74u",
  info_up_ac_desert_eagle: "info_up_ac_desert_eagle",
  info_up_ac_mp5: "info_up_ac_mp5",
  info_up_ac_spas12: "info_up_ac_spas12",
  info_up_ac_wincheaster1300: "info_up_ac_wincheaster1300",
  info_up_aceg_scientific_outfit: "info_up_aceg_scientific_outfit",
  info_up_bd_desert_eagle: "info_up_bd_desert_eagle",
  info_up_bd_mp5: "info_up_bd_mp5",
  info_up_bd_wincheaster1300: "info_up_bd_wincheaster1300",
  info_up_bdfh_scientific_outfit: "info_up_bdfh_scientific_outfit",
  info_up_cd_pkm: "info_up_cd_pkm",
  info_up_cd_svu: "info_up_cd_svu",
  info_up_fh_scientific_outfit: "info_up_fh_scientific_outfit",
  /**
   * Jupiter quests.
   */
  /**
   * Jupiter a10.
   */
  jup_a10_bandit_about_percent_asked: "jup_a10_bandit_about_percent_asked",
  jup_a10_bandit_take_all_money: "jup_a10_bandit_take_all_money",
  jup_a10_bandit_take_money: "jup_a10_bandit_take_money",
  jup_a10_debt_wo_percent: "jup_a10_debt_wo_percent",
  jup_a10_threatened: "jup_a10_threatened",
  jup_a10_vano_agree_go_und: "jup_a10_vano_agree_go_und",
  jup_a10_vano_give_task_end: "jup_a10_vano_give_task_end",
  /**
   * Jupiter a12.
   */
  jup_a12_actor_choose: "jup_a12_actor_choose",
  jup_a12_actor_choose_power: "jup_a12_actor_choose_power",
  jup_a12_actor_choose_ransom: "jup_a12_actor_choose_ransom",
  jup_a12_actor_choose_self: "jup_a12_actor_choose_self",
  jup_a12_actor_did_not_pay_to_cashier: "jup_a12_actor_did_not_pay_to_cashier",
  jup_a12_actor_enemy_to_bandits: "jup_a12_actor_enemy_to_bandits",
  jup_a12_actor_guided_base: "jup_a12_actor_guided_base",
  jup_a12_actor_has_pass_to_containers: "jup_a12_actor_has_pass_to_containers",
  jup_a12_actor_is_ready: "jup_a12_actor_is_ready",
  jup_a12_actor_paid_to_cashier: "jup_a12_actor_paid_to_cashier",
  jup_a12_actor_switched_from_ransom_to_power: "jup_a12_actor_switched_from_ransom_to_power",
  jup_a12_bandit_cashier_dead: "jup_a12_bandit_cashier_dead",
  jup_a12_bandit_guard_can_be_easily_killed: "jup_a12_bandit_guard_can_be_easily_killed",
  jup_a12_bandit_guard_killed: "jup_a12_bandit_guard_killed",
  jup_a12_bandit_out: "jup_a12_bandit_out",
  jup_a12_bandit_payment_started: "jup_a12_bandit_payment_started",
  jup_a12_bandit_taunt: "jup_a12_bandit_taunt",
  jup_a12_chief_bandit_kill_prisoner: "jup_a12_chief_bandit_kill_prisoner",
  jup_a12_chief_bandit_meet: "jup_a12_chief_bandit_meet",
  jup_a12_chief_bandit_threat_prisoner: "jup_a12_chief_bandit_threat_prisoner",
  jup_a12_chief_bandit_wait_threat_prisoner: "jup_a12_chief_bandit_wait_threat_prisoner",
  jup_a12_merc_attack_started: "jup_a12_merc_attack_started",
  jup_a12_merc_cover_attacked_containers: "jup_a12_merc_cover_attacked_containers",
  jup_a12_merc_cover_in_merc_camp: "jup_a12_merc_cover_in_merc_camp",
  jup_a12_merc_cover_on_position: "jup_a12_merc_cover_on_position",
  jup_a12_merc_cover_to_position: "jup_a12_merc_cover_to_position",
  jup_a12_merc_left_attacked_containers: "jup_a12_merc_left_attacked_containers",
  jup_a12_merc_left_to_position: "jup_a12_merc_left_to_position",
  jup_a12_merc_right_attacked_containers: "jup_a12_merc_right_attacked_containers",
  jup_a12_merc_right_to_position: "jup_a12_merc_right_to_position",
  jup_a12_mercs_done: "jup_a12_mercs_done",
  jup_a12_mercs_go_to_positions: "jup_a12_mercs_go_to_positions",
  jup_a12_prisoner_free_with_stalkers: "jup_a12_prisoner_free_with_stalkers",
  jup_a12_spawn_merc_squad: "jup_a12_spawn_merc_squad",
  jup_a12_stalker_assaulter_1_argue: "jup_a12_stalker_assaulter_1_argue",
  jup_a12_stalker_assaulter_2_argue: "jup_a12_stalker_assaulter_2_argue",
  jup_a12_stalker_assaulter_3_argue: "jup_a12_stalker_assaulter_3_argue",
  jup_a12_stalker_assaulter_argued: "jup_a12_stalker_assaulter_argued",
  jup_a12_stalker_assaulter_has_af: "jup_a12_stalker_assaulter_has_af",
  jup_a12_stalker_assaulter_told_story: "jup_a12_stalker_assaulter_told_story",
  jup_a12_stalker_diplomat_after_talked: "jup_a12_stalker_diplomat_after_talked",
  jup_a12_stalker_diplomat_argued: "jup_a12_stalker_diplomat_argued",
  jup_a12_stalker_prisoner_cheats_to_base: "jup_a12_stalker_prisoner_cheats_to_base",
  jup_a12_stalker_prisoner_dead: "jup_a12_stalker_prisoner_dead",
  jup_a12_stalker_prisoner_free: "jup_a12_stalker_prisoner_free",
  jup_a12_stalker_prisoner_free_dialog_done: "jup_a12_stalker_prisoner_free_dialog_done",
  jup_a12_stalker_prisoner_friends_talked: "jup_a12_stalker_prisoner_friends_talked",
  jup_a12_stalker_prisoner_helped: "jup_a12_stalker_prisoner_helped",
  jup_a12_stalker_prisoner_hide_end: "jup_a12_stalker_prisoner_hide_end",
  jup_a12_stalker_prisoner_hit_by_actor: "jup_a12_stalker_prisoner_hit_by_actor",
  jup_a12_stalker_prisoner_out_of_containers: "jup_a12_stalker_prisoner_out_of_containers",
  jup_a12_stalker_prisoner_out_of_hangar: "jup_a12_stalker_prisoner_out_of_hangar",
  jup_a12_stalker_prisoner_out_of_prison: "jup_a12_stalker_prisoner_out_of_prison",
  jup_a12_stalker_prisoner_questioned: "jup_a12_stalker_prisoner_questioned",
  jup_a12_stalker_prisoner_stood_up: "jup_a12_stalker_prisoner_stood_up",
  jup_a12_stalker_prisoner_thanked_actor: "jup_a12_stalker_prisoner_thanked_actor",
  jup_a12_stalker_prisoner_wait_for_dialog: "jup_a12_stalker_prisoner_wait_for_dialog",
  jup_a12_stalkers_on_base: "jup_a12_stalkers_on_base",
  jup_a12_task_given: "jup_a12_task_given",
  jup_a12_task_start: "jup_a12_task_start",
  jup_a12_ui: "jup_a12_ui",
  jup_a12_wo_shooting: "jup_a12_wo_shooting",
  /**
   * Jupiter a6.
   */
  jup_a6_duty_leader_bunker_guards_work: "jup_a6_duty_leader_bunker_guards_work",
  jup_a6_duty_leader_employ_work: "jup_a6_duty_leader_employ_work",
  jup_a6_freedom_leader_bunker_guards_work: "jup_a6_freedom_leader_bunker_guards_work",
  jup_a6_freedom_leader_employ_work: "jup_a6_freedom_leader_employ_work",
  /**
   * Jupiter a9.
   */
  jup_a9_cam_1_end: "jup_a9_cam_1_end",
  jup_a9_cam_2_end: "jup_a9_cam_2_end",
  jup_a9_cam_3_end: "jup_a9_cam_3_end",
  jup_a9_set_default_counter: "jup_a9_set_default_counter",
  jup_a9_tech_conservation_info: "jup_a9_tech_conservation_info",
  jup_a9_tech_way_info: "jup_a9_tech_way_info",
  jup_a9_way_to_pripyat_gas_info_started: "jup_a9_way_to_pripyat_gas_info_started",
  jup_a9_way_to_pripyat_power_info_started: "jup_a9_way_to_pripyat_power_info_started",
  jup_a9_way_to_pripyat_search_started: "jup_a9_way_to_pripyat_search_started",
  jup_a9_way_to_pripyat_way_info_started: "jup_a9_way_to_pripyat_way_info_started",
  /**
   * Jupiter b15.
   */
  jup_b15_zulus_b301_after_fight_done: "jup_b15_zulus_b301_after_fight_done",
  jup_b15_zulus_b301_reward_dialog_done: "jup_b15_zulus_b301_reward_dialog_done",

  jup_b16_oasis_artefact_to_scientist: "jup_b16_oasis_artefact_to_scientist",
  /**
   * Jupiter b16.
   */
  jup_b16_oasis_found: "jup_b16_oasis_found",
  jup_b16_oasis_talked: "jup_b16_oasis_talked",
  jup_b16_task_done: "jup_b16_task_done",
  /**
   * Jupiter b19.
   */
  jup_b19_actor_damaged_zombied: "jup_b19_actor_damaged_zombied",
  jup_b19_agreed_to_go: "jup_b19_agreed_to_go",
  jup_b19_arrived: "jup_b19_arrived",
  jup_b19_destroy_yar: "jup_b19_destroy_yar",
  jup_b19_destroy_yar_done: "jup_b19_destroy_yar_done",
  jup_b19_done_bye_complete: "jup_b19_done_bye_complete",
  jup_b19_done_why_mercs_complete: "jup_b19_done_why_mercs_complete",
  jup_b19_done_why_my_complete: "jup_b19_done_why_my_complete",
  jup_b19_enable_ui_done: "jup_b19_enable_ui_done",
  jup_b19_merc_spawned: "jup_b19_merc_spawned",
  jup_b19_mercs_damaged_zombied: "jup_b19_mercs_damaged_zombied",
  jup_b19_mercs_dead: "jup_b19_mercs_dead",
  jup_b19_ready_to_go: "jup_b19_ready_to_go",
  jup_b19_yar_dont_teleport_actor_to_yanov: "jup_b19_yar_dont_teleport_actor_to_yanov",
  jup_b19_yar_hate_zombied: "jup_b19_yar_hate_zombied",
  jup_b19_yar_hate_zombied_done: "jup_b19_yar_hate_zombied_done",
  jup_b19_yar_in_pripyat_about_told: "jup_b19_yar_in_pripyat_about_told",
  jup_b19_yar_in_pripyat_met: "jup_b19_yar_in_pripyat_met",
  jup_b19_yar_switch_smart_terrain: "jup_b19_yar_switch_smart_terrain",
  jup_b19_yar_teleport_actor_to_yanov: "jup_b19_yar_teleport_actor_to_yanov",
  /**
   * Jupiter b1.
   */
  jup_b1_complete_end: "jup_b1_complete_end",
  jup_b1_task_done: "jup_b1_task_done",
  /**
   * Jupiter b202.
   */
  jup_b202_actor_items_returned: "jup_b202_actor_items_returned",
  /**
   * Jupiter b206.
   */
  jup_b206_anomalous_grove_done: "jup_b206_anomalous_grove_done",
  jup_b206_anomalous_grove_has_plant_done: "jup_b206_anomalous_grove_has_plant_done",
  jup_b206_anomalous_grove_started: "jup_b206_anomalous_grove_started",
  jup_b206_nuclear_physicist_get_outfit_done: "jup_b206_nuclear_physicist_get_outfit_done",
  jup_b206_play_particle: "jup_b206_play_particle",
  jup_b206_soldier_outfit_mentioned: "jup_b206_soldier_outfit_mentioned",
  jup_b206_spawn_plant: "jup_b206_spawn_plant",
  jup_b206_task_done: "jup_b206_task_done",
  /**
   * Jupiter b207.
   */
  jup_b207_about_dealers_pda_kardan: "jup_b207_about_dealers_pda_kardan",
  jup_b207_about_dealers_pda_novikov: "jup_b207_about_dealers_pda_novikov",
  jup_b207_attack_end: "jup_b207_attack_end",
  jup_b207_attack_started: "jup_b207_attack_started",
  jup_b207_dealers_pda_sold_owl: "jup_b207_dealers_pda_sold_owl",
  jup_b207_duty_asked_to_leave: "jup_b207_duty_asked_to_leave",
  jup_b207_duty_knows_about_depot: "jup_b207_duty_knows_about_depot",
  jup_b207_duty_wins: "jup_b207_duty_wins",
  jup_b207_freedom_in_depot: "jup_b207_freedom_in_depot",
  jup_b207_freedom_know_about_depot: "jup_b207_freedom_know_about_depot",
  jup_b207_freedom_knows_about_depot: "jup_b207_freedom_knows_about_depot",
  jup_b207_freedom_refused_to_leave: "jup_b207_freedom_refused_to_leave",
  jup_b207_freedom_wins: "jup_b207_freedom_wins",
  jup_b207_morgan_ambush: "jup_b207_morgan_ambush",
  jup_b207_morgan_blackmailed: "jup_b207_morgan_blackmailed",
  jup_b207_morgan_gived_blackmail_reward: "jup_b207_morgan_gived_blackmail_reward",
  jup_b207_morgan_gived_depot: "jup_b207_morgan_gived_depot",
  jup_b207_sell_dealers_pda_duty: "jup_b207_sell_dealers_pda_duty",
  jup_b207_sell_dealers_pda_freedom: "jup_b207_sell_dealers_pda_freedom",
  jup_b207_task_start: "jup_b207_task_start",
  /**
   * Jupiter b208.
   */
  jup_b208_burer_1_dead: "jup_b208_burer_1_dead",
  jup_b208_burer_2_dead: "jup_b208_burer_2_dead",
  jup_b208_burers_dead: "jup_b208_burers_dead",
  jup_b208_burers_hunt_about: "jup_b208_burers_hunt_about",
  jup_b208_burers_hunt_done: "jup_b208_burers_hunt_done",
  jup_b208_burers_hunt_give: "jup_b208_burers_hunt_give",
  jup_b208_burers_hunt_started: "jup_b208_burers_hunt_started",
  /**
   * Jupiter b209.
   */
  jup_b209_task_done: "jup_b209_task_done",
  /**
   * Jupiter b211.
   */
  jup_b211_scene_done: "jup_b211_scene_done",
  jup_b212_jupiter_chimera_dead: "jup_b212_jupiter_chimera_dead",
  jup_b212_jupiter_chimera_free: "jup_b212_jupiter_chimera_free",
  jup_b212_jupiter_chimera_hunt_done: "jup_b212_jupiter_chimera_hunt_done",
  jup_b212_jupiter_chimera_hunt_give: "jup_b212_jupiter_chimera_hunt_give",
  jup_b212_jupiter_chimera_hunt_started: "jup_b212_jupiter_chimera_hunt_started",
  jup_b212_jupiter_chimera_hunt_told: "jup_b212_jupiter_chimera_hunt_told",
  jup_b217_stalker_tech_jupiter_delivery_done: "jup_b217_stalker_tech_jupiter_delivery_done",
  jup_b217_stalker_tech_jupiter_evacuation_done: "jup_b217_stalker_tech_jupiter_evacuation_done",
  jup_b217_stalker_tech_jupiter_losses_done: "jup_b217_stalker_tech_jupiter_losses_done",
  jup_b217_stalker_tech_jupiter_meeting_done: "jup_b217_stalker_tech_jupiter_meeting_done",
  jup_b217_stalker_tech_jupiter_power_done: "jup_b217_stalker_tech_jupiter_power_done",
  jup_b217_stalker_tech_jupiter_way_done: "jup_b217_stalker_tech_jupiter_way_done",
  jup_b217_tech_instrument_1_brought: "jup_b217_tech_instrument_1_brought",
  jup_b217_tech_instrument_2_brought: "jup_b217_tech_instrument_2_brought",
  jup_b217_tech_instrument_3_brought: "jup_b217_tech_instrument_3_brought",
  jup_b218_monolith_hired: "jup_b218_monolith_hired",
  jup_b218_soldier_hired: "jup_b218_soldier_hired",
  jup_b218_soldier_need_outfit: "jup_b218_soldier_need_outfit",
  /**
   * Jupiter b220.
   */
  jup_b220_trapper_about_retire_told: "jup_b220_trapper_about_retire_told",
  jup_b220_trapper_jupiter_chimera_why_me_done: "jup_b220_trapper_jupiter_chimera_why_me_done",
  jup_b220_trapper_zaton_chimera_hunted_told: "jup_b220_trapper_zaton_chimera_hunted_told",
  /**
   * Jupiter b25.
   */
  jup_b25_accuse_flint_gived: "jup_b25_accuse_flint_gived",
  jup_b25_blame_story_end: "jup_b25_blame_story_end",
  jup_b25_first_blame: "jup_b25_first_blame",
  jup_b25_flint_blame_done_to_duty: "jup_b25_flint_blame_done_to_duty",
  jup_b25_flint_blame_done_to_freedom: "jup_b25_flint_blame_done_to_freedom",
  jup_b25_found_senya: "jup_b25_found_senya",
  jup_b25_freedom_flint_gone: "jup_b25_freedom_flint_gone",
  jup_b25_play_reaction: "jup_b25_play_reaction",
  jup_b25_second_blame: "jup_b25_second_blame",
  jup_b25_second_story: "jup_b25_second_story",
  jup_b25_senya_spawned: "jup_b25_senya_spawned",
  jup_b25_story_artefact_played: "jup_b25_story_artefact_played",
  jup_b25_story_artefact_talked: "jup_b25_story_artefact_talked",
  jup_b25_story_bloodsucker_played: "jup_b25_story_bloodsucker_played",
  jup_b25_story_bloodsucker_talked: "jup_b25_story_bloodsucker_talked",
  jup_b25_story_controller_played: "jup_b25_story_controller_played",
  jup_b25_story_guide_played: "jup_b25_story_guide_played",
  jup_b25_story_guide_talked: "jup_b25_story_guide_talked",
  jup_b25_story_oasis_played: "jup_b25_story_oasis_played",
  jup_b25_story_scientist_played: "jup_b25_story_scientist_played",
  jup_b25_story_scientist_talked: "jup_b25_story_scientist_talked",
  jup_b25_story_zaton_played: "jup_b25_story_zaton_played",
  jup_b25_third_blame: "jup_b25_third_blame",
  jup_b25_third_story: "jup_b25_third_story",
  /**
   * Jupiter b32.
   */
  jup_b32_scanner_1_placed: "jup_b32_scanner_1_placed",
  jup_b32_scanner_2_placed: "jup_b32_scanner_2_placed",
  jup_b32_scanner_3_placed: "jup_b32_scanner_3_placed",
  jup_b32_scanner_4_placed: "jup_b32_scanner_4_placed",
  jup_b32_scanner_5_placed: "jup_b32_scanner_5_placed",
  jup_b32_scanner_reward: "jup_b32_scanner_reward",
  jup_b32_scanners_tranferred: "jup_b32_scanners_tranferred",
  jup_b32_task_addon_start: "jup_b32_task_addon_start",
  jup_b32_task_done: "jup_b32_task_done",
  jup_b32_task_end: "jup_b32_task_end",
  jup_b32_task_start: "jup_b32_task_start",
  jup_b32_tutorial_done: "jup_b32_tutorial_done",
  jup_b43_stalker_assistant_b301_about_zulus_done: "jup_b43_stalker_assistant_b301_about_zulus_done",
  /**
   * Jupiter b46.
   */
  jup_b46_duty_founder_pda_to_duty: "jup_b46_duty_founder_pda_to_duty",
  jup_b46_duty_founder_pda_to_freedom: "jup_b46_duty_founder_pda_to_freedom",
  jup_b46_duty_founder_pda_to_owl: "jup_b46_duty_founder_pda_to_owl",
  jup_b46_task_done: "jup_b46_task_done",
  /**
   * Jupiter b47.
   */
  jup_b47_task_end: "jup_b47_task_end",
  /**
   * Jupiter b4.
   */
  jup_b4_monolith_squad_in_duty: "jup_b4_monolith_squad_in_duty",
  jup_b4_monolith_squad_in_freedom: "jup_b4_monolith_squad_in_freedom",
  /**
   * Jupiter b52.
   */
  jup_b52_actor_items_can_be_stolen: "jup_b52_actor_items_can_be_stolen",
  /**
   * Jupiter b6.
   */
  jup_b6_complete_end: "jup_b6_complete_end",
  jup_b6_scientist_biochemist_anomalous_grove_done: "jup_b6_scientist_biochemist_anomalous_grove_done",
  jup_b6_scientist_biochemist_anomalous_plant_done: "jup_b6_scientist_biochemist_anomalous_plant_done",
  jup_b6_scientist_biochemist_soldier_outfit_done: "jup_b6_scientist_biochemist_soldier_outfit_done",
  jup_b6_scientist_medic_soldier_outfit_done: "jup_b6_scientist_medic_soldier_outfit_done",
  jup_b6_scientist_nuclear_physicist_soldier_outfit_done: "jup_b6_scientist_nuclear_physicist_soldier_outfit_done",
  jup_b6_task_done: "jup_b6_task_done",
  /**
   * Jupiter pri zulus death.
   */
  jup_pri_zulus_death: "jup_pri_zulus_death",
  /**
   * Jupiter end.
   */
  keeper_of_secrets_achievement_gained: "keeper_of_secrets_achievement_gained",
  kingpin_gained: "kingpin_gained",
  leader_achievement_gained: "leader_achievement_gained",
  mutant_hunter_achievement_gained: "mutant_hunter_achievement_gained",
  one_of_the_lads_gained: "one_of_the_lads_gained",
  pioneer_achievement_gained: "pioneer_achievement_gained",
  /**
   * Pripyat quests.
   */
  pri_a12_stalker_prisoner_free: "pri_a12_stalker_prisoner_free",
  pri_a16_vano_was_alive_when_removed: "pri_a16_vano_was_alive_when_removed",
  pri_a16_wanderer_was_alive_when_removed: "pri_a16_wanderer_was_alive_when_removed",
  pri_a17_actor_attack_bad: "pri_a17_actor_attack_bad",
  pri_a17_actor_attack_military: "pri_a17_actor_attack_military",
  pri_a17_actor_attack_military_antibug: "pri_a17_actor_attack_military_antibug",
  pri_a17_actor_attack_well: "pri_a17_actor_attack_well",
  pri_a17_actor_bring_gauss_rifle: "pri_a17_actor_bring_gauss_rifle",
  pri_a17_actor_has_gauss_rifle: "pri_a17_actor_has_gauss_rifle",
  pri_a17_at_home: "pri_a17_at_home",
  pri_a17_atk_mon_pat: "pri_a17_atk_mon_pat",
  pri_a17_die_at_last: "pri_a17_die_at_last",
  pri_a17_get_in_cover: "pri_a17_get_in_cover",
  pri_a17_give_task_get_gauss_rifle: "pri_a17_give_task_get_gauss_rifle",
  pri_a17_go_home: "pri_a17_go_home",
  pri_a17_good_shot: "pri_a17_good_shot",
  pri_a17_ice_dead: "pri_a17_ice_dead",
  pri_a17_ice_is_fucked: "pri_a17_ice_is_fucked",
  pri_a17_military_base_commander_task_dialog_end: "pri_a17_military_base_commander_task_dialog_end",
  pri_a17_military_recon_squad_ambush_dialog_end: "pri_a17_military_recon_squad_ambush_dialog_end",
  pri_a17_mon_ambush_killed: "pri_a17_mon_ambush_killed",
  pri_a17_mon_ambush_start: "pri_a17_mon_ambush_start",
  pri_a17_mon_atk: "pri_a17_mon_atk",
  pri_a17_mon_pat_1: "pri_a17_mon_pat_1",
  pri_a17_mon_pat_2: "pri_a17_mon_pat_2",
  pri_a17_mon_pat_3: "pri_a17_mon_pat_3",
  pri_a17_mon_pat_4: "pri_a17_mon_pat_4",
  pri_a17_mon_pat_sound1: "pri_a17_mon_pat_sound1",
  pri_a17_mon_pat_sound2: "pri_a17_mon_pat_sound2",
  pri_a17_mon_pat_sound3: "pri_a17_mon_pat_sound3",
  pri_a17_mon_pat_sound4: "pri_a17_mon_pat_sound4",
  pri_a17_mon_pat_sound5: "pri_a17_mon_pat_sound5",
  pri_a17_mon_preacher_dead: "pri_a17_mon_preacher_dead",
  pri_a17_nice_tar_end: "pri_a17_nice_tar_end",
  pri_a17_ord_tar_end: "pri_a17_ord_tar_end",
  pri_a17_patrol_dead: "pri_a17_patrol_dead",
  pri_a17_pod_at_position: "pri_a17_pod_at_position",
  pri_a17_pod_dead: "pri_a17_pod_dead",
  pri_a17_pod_in_cover_1: "pri_a17_pod_in_cover_1",
  pri_a17_recon_go: "pri_a17_recon_go",
  pri_a17_recon_squad_dead: "pri_a17_recon_squad_dead",
  pri_a17_reward_bad: "pri_a17_reward_bad",
  pri_a17_reward_norm: "pri_a17_reward_norm",
  pri_a17_reward_well: "pri_a17_reward_well",
  pri_a17_spawn_1_ended: "pri_a17_spawn_1_ended",
  pri_a17_spawn_2_ended: "pri_a17_spawn_2_ended",
  pri_a17_spawn_monolith: "pri_a17_spawn_monolith",
  pri_a17_squad_go_1: "pri_a17_squad_go_1",
  pri_a17_squad_move: "pri_a17_squad_move",
  pri_a17_stage_1_ended: "pri_a17_stage_1_ended",
  pri_a17_stage_2_ended: "pri_a17_stage_2_ended",
  pri_a17_stage_3_ended: "pri_a17_stage_3_ended",
  pri_a17_tar_sound1_end: "pri_a17_tar_sound1_end",
  pri_a17_taras_dead: "pri_a17_taras_dead",
  pri_a17_taras_final_talk: "pri_a17_taras_final_talk",
  pri_a17_told_about_operation: "pri_a17_told_about_operation",
  pri_a17_val_at_position: "pri_a17_val_at_position",
  pri_a17_val_dead: "pri_a17_val_dead",
  pri_a17_val_final_talk: "pri_a17_val_final_talk",
  pri_a17_val_in_cover_1: "pri_a17_val_in_cover_1",
  pri_a28_actor_in_zone_stay: "pri_a28_actor_in_zone_stay",
  pri_a28_army_leaved_alive: "pri_a28_army_leaved_alive",
  pri_a28_koval_dead: "pri_a28_koval_dead",
  pri_a28_sokolov_left_alive: "pri_a28_sokolov_left_alive",
  pri_a28_strelok_dead: "pri_a28_strelok_dead",
  pri_b301_bye_zulus: "pri_b301_bye_zulus",
  pri_b301_end_counter: "pri_b301_end_counter",
  pri_b301_fade: "pri_b301_fade",
  pri_b301_go_on_base: "pri_b301_go_on_base",
  pri_b301_monster_death: "pri_b301_monster_death",
  pri_b301_reward_dialog_unable: "pri_b301_reward_dialog_unable",
  pri_b301_save_zulus_complete: "pri_b301_save_zulus_complete",
  pri_b301_set_default_counter: "pri_b301_set_default_counter",
  pri_b301_teleport: "pri_b301_teleport",
  pri_b301_zulus_destroy: "pri_b301_zulus_destroy",
  pri_b301_zulus_full_destroy: "pri_b301_zulus_full_destroy",
  pri_b301_zulus_go_back: "pri_b301_zulus_go_back",
  pri_b301_zulus_spawn: "pri_b301_zulus_spawn",
  pri_b301_zulus_spawn_again: "pri_b301_zulus_spawn_again",
  pri_b305_all_strelok_notes_given: "pri_b305_all_strelok_notes_given",
  pri_b306_lift_generator_started: "pri_b306_lift_generator_started",
  pri_b306_lift_used: "pri_b306_lift_used",
  pri_b306_task_end: "pri_b306_task_end",
  pri_b306_task_start: "pri_b306_task_start",
  pri_b35_about_mercs_dialog: "pri_b35_about_mercs_dialog",
  pri_b35_actor_is_guided: "pri_b35_actor_is_guided",
  pri_b35_actor_know_about_mercenaries: "pri_b35_actor_know_about_mercenaries",
  pri_b35_actor_rest: "pri_b35_actor_rest",
  pri_b35_assistant_start_dialog_done: "pri_b35_assistant_start_dialog_done",
  pri_b35_attack_started: "pri_b35_attack_started",
  pri_b35_envoy_escape: "pri_b35_envoy_escape",
  pri_b35_envoy_out: "pri_b35_envoy_out",
  pri_b35_envoy_sighted: "pri_b35_envoy_sighted",
  pri_b35_kovalski_knows_about_mercs: "pri_b35_kovalski_knows_about_mercs",
  pri_b35_merc_leader_escape: "pri_b35_merc_leader_escape",
  pri_b35_merc_leader_out: "pri_b35_merc_leader_out",
  pri_b35_merc_leader_sighted: "pri_b35_merc_leader_sighted",
  pri_b35_primary: "pri_b35_primary",
  pri_b35_rendevous_done: "pri_b35_rendevous_done",
  pri_b35_rendevous_in_process: "pri_b35_rendevous_in_process",
  pri_b35_reward_given: "pri_b35_reward_given",
  pri_b35_secondary: "pri_b35_secondary",
  pri_b35_target_envoy: "pri_b35_target_envoy",
  pri_b35_target_merc: "pri_b35_target_merc",
  pri_b35_task_continue: "pri_b35_task_continue",
  pri_b35_task_refuse: "pri_b35_task_refuse",
  pri_b35_task_running: "pri_b35_task_running",
  pri_b35_task_start: "pri_b35_task_start",
  pri_b35_ui: "pri_b35_ui",
  pri_b36_ahtung: "pri_b36_ahtung",
  /**
   * Pripyat end.
   */
  research_man_gained: "research_man_gained",
  sim_bandit_attack_harder: "sim_bandit_attack_harder",
  sim_duty_help_harder: "sim_duty_help_harder",
  sim_freedom_help_harder: "sim_freedom_help_harder",
  sim_stalker_help_harder: "sim_stalker_help_harder",
  skilled_stalker_achievement_gained: "skilled_stalker_achievement_gained",
  sleep_active: "sleep_active",
  stalkers_toolkit_dialog: "stalkers_toolkit_dialog",
  tutorial_sleep: "tutorial_sleep",
  /**
   * Zaton quests.
   */
  zat_a23_stalker_tech_told_about_battery: "zat_a23_stalker_tech_told_about_battery",
  zat_a2_linker_b14_quest_strange_item_done: "zat_a2_linker_b14_quest_strange_item_done",
  zat_a2_linker_b14_quest_strange_item_lost_artefact: "zat_a2_linker_b14_quest_strange_item_lost_artefact",
  zat_a2_linker_b14_quest_wrong_done: "zat_a2_linker_b14_quest_wrong_done",
  zat_a2_linker_b52_about_nimble_dialog_done: "zat_a2_linker_b52_about_nimble_dialog_done",
  zat_a2_stalker_barmen_b52_about_nimble_dialog_done: "zat_a2_stalker_barmen_b52_about_nimble_dialog_done",
  zat_a2_stalker_barmen_b52_about_snag: "zat_a2_stalker_barmen_b52_about_snag",
  zat_a2_stalker_barmen_hit_from_actor: "zat_a2_stalker_barmen_hit_from_actor",
  zat_a2_stalker_barmen_setup: "zat_a2_stalker_barmen_setup",
  zat_a2_toolkit_search: "zat_a2_toolkit_search",
  zat_a9_actor_conservation_info_play_sound: "zat_a9_actor_conservation_info_play_sound",
  zat_a9_actor_delivery_info_play_sound: "zat_a9_actor_delivery_info_play_sound",
  zat_a9_actor_evacuation_info_play_sound: "zat_a9_actor_evacuation_info_play_sound",
  zat_a9_actor_has_jup_a9_actor_losses_info: "zat_a9_actor_has_jup_a9_actor_losses_info",
  zat_a9_actor_has_jup_a9_actor_power_info: "zat_a9_actor_has_jup_a9_actor_power_info",
  zat_a9_actor_has_jup_a9_conservation_info: "zat_a9_actor_has_jup_a9_conservation_info",
  zat_a9_actor_has_jup_a9_delivery_info: "zat_a9_actor_has_jup_a9_delivery_info",
  zat_a9_actor_has_jup_a9_evacuation_info: "zat_a9_actor_has_jup_a9_evacuation_info",
  zat_a9_actor_has_jup_a9_meeting_info: "zat_a9_actor_has_jup_a9_meeting_info",
  zat_a9_actor_has_jup_a9_way_info: "zat_a9_actor_has_jup_a9_way_info",
  zat_a9_actor_losses_info_play_sound: "zat_a9_actor_losses_info_play_sound",
  zat_a9_actor_meeting_info_play_sound: "zat_a9_actor_meeting_info_play_sound",
  zat_a9_actor_power_info_play_sound: "zat_a9_actor_power_info_play_sound",
  zat_a9_actor_way_info_play_sound: "zat_a9_actor_way_info_play_sound",
  zat_b100_cameff_played: "zat_b100_cameff_played",
  zat_b100_heli_2_searched: "zat_b100_heli_2_searched",
  zat_b100_heli_2_searching: "zat_b100_heli_2_searching",
  zat_b100_poltergeist_dead_01: "zat_b100_poltergeist_dead_01",
  zat_b100_poltergeist_dead_02: "zat_b100_poltergeist_dead_02",
  zat_b100_poltergeist_spawned_01: "zat_b100_poltergeist_spawned_01",
  zat_b100_poltergeist_spawned_02: "zat_b100_poltergeist_spawned_02",
  zat_b100_sound_played: "zat_b100_sound_played",
  zat_b103_actor_take_toolkit: "zat_b103_actor_take_toolkit",
  zat_b103_actor_took_kardan_task: "zat_b103_actor_took_kardan_task",
  zat_b103_actor_warned_by_merc: "zat_b103_actor_warned_by_merc",
  zat_b103_merc_about_supplies_mentioned: "zat_b103_merc_about_supplies_mentioned",
  zat_b103_merc_ammo_got: "zat_b103_merc_ammo_got",
  zat_b103_merc_bring_supplies: "zat_b103_merc_bring_supplies",
  zat_b103_merc_fight: "zat_b103_merc_fight",
  zat_b103_merc_food_got: "zat_b103_merc_food_got",
  zat_b103_merc_medkit_got: "zat_b103_merc_medkit_got",
  zat_b103_merc_supplies_got: "zat_b103_merc_supplies_got",
  zat_b103_merc_task_done: "zat_b103_merc_task_done",
  zat_b103_merc_used_actor: "zat_b103_merc_used_actor",
  zat_b103_toolkit_known: "zat_b103_toolkit_known",
  zat_b104_task_end: "zat_b104_task_end",
  zat_b106_found_soroka: "zat_b106_found_soroka",
  zat_b106_found_soroka_done: "zat_b106_found_soroka_done",
  zat_b106_search_soroka: "zat_b106_search_soroka",
  zat_b106_stalker_gonta_b52_about_nimble_dialog_done: "zat_b106_stalker_gonta_b52_about_nimble_dialog_done",
  zat_b12_key_1_use: "zat_b12_key_1_use",
  zat_b12_key_2_use: "zat_b12_key_2_use",
  zat_b14_actor_enemy: "zat_b14_actor_enemy",
  zat_b14_actor_in_up_point_zone: "zat_b14_actor_in_up_point_zone",
  zat_b14_actor_know_about_svyaznoy: "zat_b14_actor_know_about_svyaznoy",
  zat_b14_bad_stalker_1_2_spawn: "zat_b14_bad_stalker_1_2_spawn",
  zat_b14_cut_scene_1_point_01: "zat_b14_cut_scene_1_point_01",
  zat_b14_cut_scene_1_point_02: "zat_b14_cut_scene_1_point_02",
  zat_b14_cut_scene_1_point_03: "zat_b14_cut_scene_1_point_03",
  zat_b14_cut_scene_1_start: "zat_b14_cut_scene_1_start",
  zat_b14_cut_scene_end: "zat_b14_cut_scene_end",
  zat_b14_cut_scene_linker_have_artefact: "zat_b14_cut_scene_linker_have_artefact",
  zat_b14_cut_scene_stalker_not_have_artefact: "zat_b14_cut_scene_stalker_not_have_artefact",
  zat_b14_cut_scene_stalker_transfer_artefact: "zat_b14_cut_scene_stalker_transfer_artefact",
  zat_b14_den_of_the_bloodsucker_find_keys_give: "zat_b14_den_of_the_bloodsucker_find_keys_give",
  zat_b14_den_of_the_bloodsucker_open_conteiner_give: "zat_b14_den_of_the_bloodsucker_open_conteiner_give",
  zat_b14_dialog_done: "zat_b14_dialog_done",
  zat_b14_dialog_last_chance_done: "zat_b14_dialog_last_chance_done",
  zat_b14_door_1_unlock: "zat_b14_door_1_unlock",
  zat_b14_general_stalker_spawn: "zat_b14_general_stalker_spawn",
  zat_b14_give_item_linker: "zat_b14_give_item_linker",
  zat_b14_give_item_stalker: "zat_b14_give_item_stalker",
  zat_b14_learn_about_strange_occurrence_by_stalkers_give_task:
    "zat_b14_learn_about_strange_occurrence_by_stalkers_give_task",
  zat_b14_learn_about_strange_occurrence_give_task: "zat_b14_learn_about_strange_occurrence_give_task",
  zat_b14_not_give_item_linker: "zat_b14_not_give_item_linker",
  zat_b14_not_give_item_stalker: "zat_b14_not_give_item_stalker",
  zat_b14_recon_place: "zat_b14_recon_place",
  zat_b14_robbery_give_artefact: "zat_b14_robbery_give_artefact",
  zat_b14_robbery_not_give_artefact: "zat_b14_robbery_not_give_artefact",
  zat_b14_robbery_nowpn_actor: "zat_b14_robbery_nowpn_actor",
  zat_b14_robbery_punch_play_sound: "zat_b14_robbery_punch_play_sound",
  zat_b14_smart_terrain_open: "zat_b14_smart_terrain_open",
  zat_b14_spawn_friends_stalker: "zat_b14_spawn_friends_stalker",
  zat_b14_stalker_at_bar_start_done: "zat_b14_stalker_at_bar_start_done",
  zat_b14_stalker_change_smart: "zat_b14_stalker_change_smart",
  zat_b14_stalker_cut_scene_ready: "zat_b14_stalker_cut_scene_ready",
  zat_b14_stalker_robbery: "zat_b14_stalker_robbery",
  zat_b14_stalker_robbery_cutscene_end: "zat_b14_stalker_robbery_cutscene_end",
  zat_b14_stalker_robbery_cutscene_start: "zat_b14_stalker_robbery_cutscene_start",
  zat_b14_stalker_work_end: "zat_b14_stalker_work_end",
  zat_b14_stalkers_bandits_free: "zat_b14_stalkers_bandits_free",
  zat_b14_strange_item: "zat_b14_strange_item",
  zat_b14_take_item: "zat_b14_take_item",
  zat_b14_ui_disable: "zat_b14_ui_disable",
  zat_b14_ui_enable: "zat_b14_ui_enable",
  zat_b18_noah_about_catastrophe_told: "zat_b18_noah_about_catastrophe_told",
  zat_b18_noah_about_dog_told: "zat_b18_noah_about_dog_told",
  zat_b18_noah_breakdown: "zat_b18_noah_breakdown",
  zat_b18_noah_dead: "zat_b18_noah_dead",
  zat_b18_noah_gave_first_artefact: "zat_b18_noah_gave_first_artefact",
  zat_b18_noah_gave_second_artefact: "zat_b18_noah_gave_second_artefact",
  zat_b18_noah_go_away: "zat_b18_noah_go_away",
  zat_b18_noah_met: "zat_b18_noah_met",
  zat_b18_noah_remembers: "zat_b18_noah_remembers",
  zat_b18_noah_shot_door: "zat_b18_noah_shot_door",
  zat_b18_noah_told_about_arc: "zat_b18_noah_told_about_arc",
  zat_b18_reset_memory: "zat_b18_reset_memory",
  zat_b215_gave_maps: "zat_b215_gave_maps",
  zat_b22_actor_gone: "zat_b22_actor_gone",
  zat_b22_actor_in: "zat_b22_actor_in",
  zat_b22_barmen_gave_reward: "zat_b22_barmen_gave_reward",
  zat_b22_deal_with_medic_vampire_completed: "zat_b22_deal_with_medic_vampire_completed",
  zat_b22_deal_with_medic_vampire_reversed: "zat_b22_deal_with_medic_vampire_reversed",
  zat_b22_medic_dialog_info_1: "zat_b22_medic_dialog_info_1",
  zat_b22_medic_dialog_info_2: "zat_b22_medic_dialog_info_2",
  zat_b22_medic_dialog_info_3: "zat_b22_medic_dialog_info_3",
  zat_b22_questline_reversed: "zat_b22_questline_reversed",
  zat_b22_stalker_cop_place: "zat_b22_stalker_cop_place",
  zat_b22_stalker_medic_b52_about_nimble_dialog_done: "zat_b22_stalker_medic_b52_about_nimble_dialog_done",
  zat_b22_stalker_medic_body_searched: "zat_b22_stalker_medic_body_searched",
  zat_b22_stalker_medic_wounded_heavy: "zat_b22_stalker_medic_wounded_heavy",
  zat_b22_stalker_vampire: "zat_b22_stalker_vampire",
  zat_b22_stalker_vampire_story: "zat_b22_stalker_vampire_story",
  zat_b29_adv_task_given: "zat_b29_adv_task_given",
  zat_b29_adv_task_timeout: "zat_b29_adv_task_timeout",
  zat_b29_af_16: "zat_b29_af_16",
  zat_b29_af_17: "zat_b29_af_17",
  zat_b29_af_18: "zat_b29_af_18",
  zat_b29_af_19: "zat_b29_af_19",
  zat_b29_af_20: "zat_b29_af_20",
  zat_b29_af_21: "zat_b29_af_21",
  zat_b29_af_22: "zat_b29_af_22",
  zat_b29_af_23: "zat_b29_af_23",
  zat_b29_bring_af_17: "zat_b29_bring_af_17",
  zat_b29_bring_af_18: "zat_b29_bring_af_18",
  zat_b29_bring_af_19: "zat_b29_bring_af_19",
  zat_b29_bring_af_20: "zat_b29_bring_af_20",
  zat_b29_bring_af_21: "zat_b29_bring_af_21",
  zat_b29_bring_af_22: "zat_b29_bring_af_22",
  zat_b29_bring_af_23: "zat_b29_bring_af_23",
  zat_b29_exclusive_conditions: "zat_b29_exclusive_conditions",
  zat_b29_first_rival_taken_out: "zat_b29_first_rival_taken_out",
  zat_b29_linker_fears_actor: "zat_b29_linker_fears_actor",
  zat_b29_linker_info: "zat_b29_linker_info",
  zat_b29_linker_take_af_from_rival: "zat_b29_linker_take_af_from_rival",
  zat_b29_quest_af_given: "zat_b29_quest_af_given",
  zat_b29_redice: "zat_b29_redice",
  zat_b29_respawn: "zat_b29_respawn",
  zat_b29_rival_1_1: "zat_b29_rival_1_1",
  zat_b29_rival_1_2: "zat_b29_rival_1_2",
  zat_b29_rival_1_3: "zat_b29_rival_1_3",
  zat_b29_rival_1_4: "zat_b29_rival_1_4",
  zat_b29_rival_1_5: "zat_b29_rival_1_5",
  zat_b29_rival_1_base: "zat_b29_rival_1_base",
  zat_b29_rival_2_1: "zat_b29_rival_2_1",
  zat_b29_rival_2_2: "zat_b29_rival_2_2",
  zat_b29_rival_2_3: "zat_b29_rival_2_3",
  zat_b29_rival_2_4: "zat_b29_rival_2_4",
  zat_b29_rival_2_5: "zat_b29_rival_2_5",
  zat_b29_rival_2_base: "zat_b29_rival_2_base",
  zat_b29_rival_sound_played: "zat_b29_rival_sound_played",
  zat_b29_rivals_search: "zat_b29_rivals_search",
  zat_b29_second_rival_taken_out: "zat_b29_second_rival_taken_out",
  zat_b29_stalker_rival_1_found_af: "zat_b29_stalker_rival_1_found_af",
  zat_b29_stalker_rival_2_found_af: "zat_b29_stalker_rival_2_found_af",
  zat_b29_stalkers_rivals_found_af: "zat_b29_stalkers_rivals_found_af",
  zat_b29_task_fail: "zat_b29_task_fail",
  zat_b29_task_start: "zat_b29_task_start",
  zat_b30_about_compass_told: "zat_b30_about_compass_told",
  zat_b30_actor_against_barmen: "zat_b30_actor_against_barmen",
  zat_b30_actor_against_owl: "zat_b30_actor_against_owl",
  zat_b30_actor_gave_detector: "zat_b30_actor_gave_detector",
  zat_b30_actor_in_tempting_business: "zat_b30_actor_in_tempting_business",
  zat_b30_actor_with_af: "zat_b30_actor_with_af",
  zat_b30_actor_with_sultan: "zat_b30_actor_with_sultan",
  zat_b30_barmen_going_under_sultan: "zat_b30_barmen_going_under_sultan",
  zat_b30_barmen_got_af: "zat_b30_barmen_got_af",
  zat_b30_barmen_under_sultan: "zat_b30_barmen_under_sultan",
  zat_b30_barmen_under_sultan_told: "zat_b30_barmen_under_sultan_told",
  zat_b30_compass_task_start: "zat_b30_compass_task_start",
  zat_b30_compass_to_barmen: "zat_b30_compass_to_barmen",
  zat_b30_compass_to_barmen_reversed: "zat_b30_compass_to_barmen_reversed",
  zat_b30_compass_to_sultan: "zat_b30_compass_to_sultan",
  zat_b30_compass_to_sultan_reversed: "zat_b30_compass_to_sultan_reversed",
  zat_b30_first_detector: "zat_b30_first_detector",
  zat_b30_jup_b6_scientist_tech_about_owl: "zat_b30_jup_b6_scientist_tech_about_owl",
  zat_b30_need_artefact_from_noah: "zat_b30_need_artefact_from_noah",
  zat_b30_owl_detectors_approached: "zat_b30_owl_detectors_approached",
  zat_b30_owl_in_trouble: "zat_b30_owl_in_trouble",
  zat_b30_owl_in_trouble_dialog_done: "zat_b30_owl_in_trouble_dialog_done",
  zat_b30_owl_quest_done: "zat_b30_owl_quest_done",
  zat_b30_owl_stalker_trader_more_documets_done: "zat_b30_owl_stalker_trader_more_documets_done",
  zat_b30_owl_to_sultan: "zat_b30_owl_to_sultan",
  zat_b30_rival_1_wo_detector: "zat_b30_rival_1_wo_detector",
  zat_b30_rival_2_wo_detector: "zat_b30_rival_2_wo_detector",
  zat_b30_second_detector: "zat_b30_second_detector",
  zat_b30_sultan_got_af: "zat_b30_sultan_got_af",
  zat_b30_sultan_know_about_detectors: "zat_b30_sultan_know_about_detectors",
  zat_b30_sultan_loose: "zat_b30_sultan_loose",
  zat_b30_sultan_refuses_af: "zat_b30_sultan_refuses_af",
  zat_b30_task_percents_running: "zat_b30_task_percents_running",
  zat_b30_task_start: "zat_b30_task_start",
  zat_b33_actor_is_down: "zat_b33_actor_is_down",
  zat_b33_fifth_item: "zat_b33_fifth_item",
  zat_b33_find_package: "zat_b33_find_package",
  zat_b33_first_item: "zat_b33_first_item",
  zat_b33_fourth_item: "zat_b33_fourth_item",
  zat_b33_package_returned: "zat_b33_package_returned",
  zat_b33_refuse_task: "zat_b33_refuse_task",
  zat_b33_safe_container: "zat_b33_safe_container",
  zat_b33_second_item: "zat_b33_second_item",
  zat_b33_share_start: "zat_b33_share_start",
  zat_b33_snork_jump_05: "zat_b33_snork_jump_05",
  zat_b33_stalker_snag_b52_my_gun_dialog_done: "zat_b33_stalker_snag_b52_my_gun_dialog_done",
  zat_b33_task_gived: "zat_b33_task_gived",
  zat_b33_third_item: "zat_b33_third_item",
  zat_b38_actor_know_about_lair: "zat_b38_actor_know_about_lair",
  zat_b38_bloodscuker_1_death: "zat_b38_bloodscuker_1_death",
  zat_b38_bloodscuker_1_hit: "zat_b38_bloodscuker_1_hit",
  zat_b38_bloodscuker_2_death: "zat_b38_bloodscuker_2_death",
  zat_b38_bloodscuker_2_hit: "zat_b38_bloodscuker_2_hit",
  zat_b38_bloodscukers_sleepers_stand_up: "zat_b38_bloodscukers_sleepers_stand_up",
  zat_b38_bloodsucker_1_angry: "zat_b38_bloodsucker_1_angry",
  zat_b38_bloodsucker_1_set_state: "zat_b38_bloodsucker_1_set_state",
  zat_b38_bloodsucker_2_angry: "zat_b38_bloodsucker_2_angry",
  zat_b38_bloodsucker_2_set_state: "zat_b38_bloodsucker_2_set_state",
  zat_b38_bloodsucker_fear_1_play: "zat_b38_bloodsucker_fear_1_play",
  zat_b38_cop_about_lair_dialog_done: "zat_b38_cop_about_lair_dialog_done",
  zat_b38_cop_hit_from_actor: "zat_b38_cop_hit_from_actor",
  zat_b38_cop_spawn_again: "zat_b38_cop_spawn_again",
  zat_b38_cop_spawn_again2: "zat_b38_cop_spawn_again2",
  zat_b38_den_of_the_bloodsucker_complete: "zat_b38_den_of_the_bloodsucker_complete",
  zat_b38_den_of_the_bloodsucker_inform_stalkers_give: "zat_b38_den_of_the_bloodsucker_inform_stalkers_give",
  zat_b38_den_of_the_bloodsucker_inform_stalkers_give_task: "zat_b38_den_of_the_bloodsucker_inform_stalkers_give_task",
  zat_b38_den_of_the_bloodsucker_tell_barman_about_all_give:
    "zat_b38_den_of_the_bloodsucker_tell_barman_about_all_give",
  zat_b38_disappearance_stalkers_check_basement_give: "zat_b38_disappearance_stalkers_check_basement_give",
  zat_b38_disappearance_stalkers_clean_den_of_the_bloodsucker_give:
    "zat_b38_disappearance_stalkers_clean_den_of_the_bloodsucker_give",
  zat_b38_disappearance_stalkers_complete: "zat_b38_disappearance_stalkers_complete",
  zat_b38_disappearance_stalkers_deal_with_medic_give: "zat_b38_disappearance_stalkers_deal_with_medic_give",
  zat_b38_disappearance_stalkers_fail: "zat_b38_disappearance_stalkers_fail",
  zat_b38_disappearance_stalkers_find_cop_near_port_krans_give:
    "zat_b38_disappearance_stalkers_find_cop_near_port_krans_give",
  zat_b38_disappearance_stalkers_find_out_where_is_cop_give:
    "zat_b38_disappearance_stalkers_find_out_where_is_cop_give",
  zat_b38_disappearance_stalkers_find_to_be_missing_hunter_give:
    "zat_b38_disappearance_stalkers_find_to_be_missing_hunter_give",
  zat_b38_disappearance_stalkers_find_to_be_missing_hunter_give_task:
    "zat_b38_disappearance_stalkers_find_to_be_missing_hunter_give_task",
  zat_b38_disappearance_stalkers_get_out_from_den_of_the_bloodsucker_give:
    "zat_b38_disappearance_stalkers_get_out_from_den_of_the_bloodsucker_give",
  zat_b38_disappearance_stalkers_jump_down_give: "zat_b38_disappearance_stalkers_jump_down_give",
  zat_b38_disappearance_stalkers_meet_cop_24h_past_give: "zat_b38_disappearance_stalkers_meet_cop_24h_past_give",
  zat_b38_disappearance_stalkers_meet_cop_later_give: "zat_b38_disappearance_stalkers_meet_cop_later_give",
  zat_b38_disappearance_stalkers_meet_cop_next_day_give: "zat_b38_disappearance_stalkers_meet_cop_next_day_give",
  zat_b38_disappearance_stalkers_meet_ment_give: "zat_b38_disappearance_stalkers_meet_ment_give",
  zat_b38_disappearance_stalkers_reversed: "zat_b38_disappearance_stalkers_reversed",
  zat_b38_disappearance_stalkers_tell_barmen_about_medic_give:
    "zat_b38_disappearance_stalkers_tell_barmen_about_medic_give",
  zat_b38_lift_open: "zat_b38_lift_open",
  zat_b38_lock_sound_play: "zat_b38_lock_sound_play",
  zat_b38_lock_sound_stop: "zat_b38_lock_sound_stop",
  zat_b38_show_spot_dead_body: "zat_b38_show_spot_dead_body",
  zat_b38_spawn_all: "zat_b38_spawn_all",
  zat_b38_spawn_npc_cop_again: "zat_b38_spawn_npc_cop_again",
  zat_b38_spawn_npc_cop_again2: "zat_b38_spawn_npc_cop_again2",
  zat_b38_stalker_cop_b52_about_nimble: "zat_b38_stalker_cop_b52_about_nimble",
  zat_b38_stalker_cop_cave_end: "zat_b38_stalker_cop_cave_end",
  zat_b38_stalker_cop_come_here_2_play: "zat_b38_stalker_cop_come_here_2_play",
  zat_b38_stalker_cop_death: "zat_b38_stalker_cop_death",
  zat_b38_stalker_cop_destroy: "zat_b38_stalker_cop_destroy",
  zat_b38_stalker_cop_destroy2: "zat_b38_stalker_cop_destroy2",
  zat_b38_stalker_cop_fear_1: "zat_b38_stalker_cop_fear_1",
  zat_b38_stalker_cop_fear_2: "zat_b38_stalker_cop_fear_2",
  zat_b38_stalker_cop_find_lair_pda_play: "zat_b38_stalker_cop_find_lair_pda_play",
  zat_b38_stalker_cop_task_dialog_done: "zat_b38_stalker_cop_task_dialog_done",
  zat_b38_stalker_medic_bloodsucker_dialog_done: "zat_b38_stalker_medic_bloodsucker_dialog_done",
  zat_b38_stalker_medic_setup: "zat_b38_stalker_medic_setup",
  zat_b38_stalkers_den_of_the_bloodsucker_universal_dialog_done:
    "zat_b38_stalkers_den_of_the_bloodsucker_universal_dialog_done",
  zat_b38_underground_door_open: "zat_b38_underground_door_open",
  zat_b3_all_instruments_brought: "zat_b3_all_instruments_brought",
  zat_b3_stalker_mechanic_b52_about_nimble_dialog_done: "zat_b3_stalker_mechanic_b52_about_nimble_dialog_done",
  zat_b3_tech_have_couple_dose: "zat_b3_tech_have_couple_dose",
  zat_b3_tech_have_one_dose: "zat_b3_tech_have_one_dose",
  zat_b3_tech_instrument_1_brought: "zat_b3_tech_instrument_1_brought",
  zat_b3_tech_instrument_2_brought: "zat_b3_tech_instrument_2_brought",
  zat_b3_tech_instrument_3_brought: "zat_b3_tech_instrument_3_brought",
  zat_b3_tech_see_produce_62: "zat_b3_tech_see_produce_62",
  zat_b44_tech_buddies_both_told: "zat_b44_tech_buddies_both_told",
  zat_b51_done_item_1_1: "zat_b51_done_item_1_1",
  zat_b51_done_item_1_2: "zat_b51_done_item_1_2",
  zat_b51_done_item_1_3: "zat_b51_done_item_1_3",
  zat_b51_done_item_2_1: "zat_b51_done_item_2_1",
  zat_b51_done_item_2_2: "zat_b51_done_item_2_2",
  zat_b51_done_item_2_3: "zat_b51_done_item_2_3",
  zat_b51_done_item_3_1: "zat_b51_done_item_3_1",
  zat_b51_done_item_3_2: "zat_b51_done_item_3_2",
  zat_b51_done_item_3_3: "zat_b51_done_item_3_3",
  zat_b51_done_item_4_1: "zat_b51_done_item_4_1",
  zat_b51_done_item_4_2: "zat_b51_done_item_4_2",
  zat_b51_done_item_4_3: "zat_b51_done_item_4_3",
  zat_b51_done_item_5_1: "zat_b51_done_item_5_1",
  zat_b51_done_item_6_1: "zat_b51_done_item_6_1",
  zat_b51_done_item_7_1: "zat_b51_done_item_7_1",
  zat_b51_finished_categories_all: "zat_b51_finished_categories_all",
  zat_b51_finished_category_1: "zat_b51_finished_category_1",
  zat_b51_finished_category_2: "zat_b51_finished_category_2",
  zat_b51_finished_category_3: "zat_b51_finished_category_3",
  zat_b51_finished_category_4: "zat_b51_finished_category_4",
  zat_b51_finished_category_5: "zat_b51_finished_category_5",
  zat_b51_finished_category_6: "zat_b51_finished_category_6",
  zat_b51_finished_category_7: "zat_b51_finished_category_7",
  zat_b51_finishing_category_1: "zat_b51_finishing_category_1",
  zat_b51_finishing_category_2: "zat_b51_finishing_category_2",
  zat_b51_finishing_category_3: "zat_b51_finishing_category_3",
  zat_b51_finishing_category_4: "zat_b51_finishing_category_4",
  zat_b51_finishing_category_5: "zat_b51_finishing_category_5",
  zat_b51_finishing_category_6: "zat_b51_finishing_category_6",
  zat_b51_finishing_category_7: "zat_b51_finishing_category_7",
  zat_b51_nimble_can_go: "zat_b51_nimble_can_go",
  zat_b51_nimble_intro: "zat_b51_nimble_intro",
  zat_b51_order_in_process: "zat_b51_order_in_process",
  zat_b51_order_ready: "zat_b51_order_ready",
  zat_b51_order_refused: "zat_b51_order_refused",
  zat_b51_order_unavailable: "zat_b51_order_unavailable",
  zat_b51_ordered_item_1_1: "zat_b51_ordered_item_1_1",
  zat_b51_ordered_item_1_2: "zat_b51_ordered_item_1_2",
  zat_b51_ordered_item_1_3: "zat_b51_ordered_item_1_3",
  zat_b51_ordered_item_2_1: "zat_b51_ordered_item_2_1",
  zat_b51_ordered_item_2_2: "zat_b51_ordered_item_2_2",
  zat_b51_ordered_item_2_3: "zat_b51_ordered_item_2_3",
  zat_b51_ordered_item_3_1: "zat_b51_ordered_item_3_1",
  zat_b51_ordered_item_3_2: "zat_b51_ordered_item_3_2",
  zat_b51_ordered_item_3_3: "zat_b51_ordered_item_3_3",
  zat_b51_ordered_item_4_1: "zat_b51_ordered_item_4_1",
  zat_b51_ordered_item_4_2: "zat_b51_ordered_item_4_2",
  zat_b51_ordered_item_4_3: "zat_b51_ordered_item_4_3",
  zat_b51_ordered_item_5_1: "zat_b51_ordered_item_5_1",
  zat_b51_ordered_item_6_1: "zat_b51_ordered_item_6_1",
  zat_b51_ordered_item_7_1: "zat_b51_ordered_item_7_1",
  zat_b51_processing_category_1: "zat_b51_processing_category_1",
  zat_b51_processing_category_2: "zat_b51_processing_category_2",
  zat_b51_processing_category_3: "zat_b51_processing_category_3",
  zat_b51_processing_category_4: "zat_b51_processing_category_4",
  zat_b51_processing_category_5: "zat_b51_processing_category_5",
  zat_b51_processing_category_6: "zat_b51_processing_category_6",
  zat_b51_processing_category_7: "zat_b51_processing_category_7",
  zat_b51_stalker_nimble_b52_about_gun_questions_dialog_done:
    "zat_b51_stalker_nimble_b52_about_gun_questions_dialog_done",
  zat_b51_stalker_snag_b52_about_gun_questions_dialog_done: "zat_b51_stalker_snag_b52_about_gun_questions_dialog_done",
  zat_b51_told_about_item_1_1: "zat_b51_told_about_item_1_1",
  zat_b51_told_about_item_1_2: "zat_b51_told_about_item_1_2",
  zat_b51_told_about_item_1_3: "zat_b51_told_about_item_1_3",
  zat_b51_told_about_item_2_1: "zat_b51_told_about_item_2_1",
  zat_b51_told_about_item_2_2: "zat_b51_told_about_item_2_2",
  zat_b51_told_about_item_2_3: "zat_b51_told_about_item_2_3",
  zat_b51_told_about_item_3_1: "zat_b51_told_about_item_3_1",
  zat_b51_told_about_item_3_2: "zat_b51_told_about_item_3_2",
  zat_b51_told_about_item_3_3: "zat_b51_told_about_item_3_3",
  zat_b51_told_about_item_4_1: "zat_b51_told_about_item_4_1",
  zat_b51_told_about_item_4_2: "zat_b51_told_about_item_4_2",
  zat_b51_told_about_item_4_3: "zat_b51_told_about_item_4_3",
  zat_b51_told_about_item_5_1: "zat_b51_told_about_item_5_1",
  zat_b51_told_about_item_6_1: "zat_b51_told_about_item_6_1",
  zat_b51_told_about_item_7_1: "zat_b51_told_about_item_7_1",
  zat_b52_actor_go_offline: "zat_b52_actor_go_offline",
  zat_b52_actor_has_port_bandits_pda: "zat_b52_actor_has_port_bandits_pda",
  zat_b52_barman_know_there_snag: "zat_b52_barman_know_there_snag",
  zat_b52_item_1_a_taken: "zat_b52_item_1_a_taken",
  zat_b52_item_1_b_taken: "zat_b52_item_1_b_taken",
  zat_b52_item_1_c_taken: "zat_b52_item_1_c_taken",
  zat_b52_item_2_a_taken: "zat_b52_item_2_a_taken",
  zat_b52_item_2_b_taken: "zat_b52_item_2_b_taken",
  zat_b52_item_2_c_taken: "zat_b52_item_2_c_taken",
  zat_b52_item_3_a_taken: "zat_b52_item_3_a_taken",
  zat_b52_item_3_b_taken: "zat_b52_item_3_b_taken",
  zat_b52_item_3_c_taken: "zat_b52_item_3_c_taken",
  zat_b52_item_4_a_taken: "zat_b52_item_4_a_taken",
  zat_b52_item_4_b_taken: "zat_b52_item_4_b_taken",
  zat_b52_item_4_c_taken: "zat_b52_item_4_c_taken",
  zat_b52_item_no_taken: "zat_b52_item_no_taken",
  zat_b52_item_taken: "zat_b52_item_taken",
  zat_b52_meet_port_bandits: "zat_b52_meet_port_bandits",
  zat_b52_nimble_clear: "zat_b52_nimble_clear",
  zat_b52_port_bandits_spawn: "zat_b52_port_bandits_spawn",
  zat_b52_reputation_give: "zat_b52_reputation_give",
  zat_b52_reputation_task_open: "zat_b52_reputation_task_open",
  zat_b52_robbery_done: "zat_b52_robbery_done",
  zat_b52_robbery_no: "zat_b52_robbery_no",
  zat_b52_robbery_start: "zat_b52_robbery_start",
  zat_b52_robbery_yes: "zat_b52_robbery_yes",
  zat_b52_snag_jupiter: "zat_b52_snag_jupiter",
  zat_b52_snag_know_weapon: "zat_b52_snag_know_weapon",
  zat_b52_snag_no_place: "zat_b52_snag_no_place",
  zat_b52_snag_no_port_cranes: "zat_b52_snag_no_port_cranes",
  zat_b52_snag_port_bandits: "zat_b52_snag_port_bandits",
  zat_b52_snag_port_cranes: "zat_b52_snag_port_cranes",
  zat_b52_sultan_know_there_snag: "zat_b52_sultan_know_there_snag",
  zat_b57_balon_use: "zat_b57_balon_use",
  zat_b57_barmen_about_bloodsucker_lair_dialog_done: "zat_b57_barmen_about_bloodsucker_lair_dialog_done",
  zat_b57_bloodsucker_lair_clear: "zat_b57_bloodsucker_lair_clear",
  zat_b57_bloodsucker_spawn: "zat_b57_bloodsucker_spawn",
  zat_b57_den_of_the_bloodsucker_destroy_lair_give: "zat_b57_den_of_the_bloodsucker_destroy_lair_give",
  zat_b57_den_of_the_bloodsucker_place_gas_give: "zat_b57_den_of_the_bloodsucker_place_gas_give",
  zat_b57_den_of_the_bloodsucker_search_gas_give: "zat_b57_den_of_the_bloodsucker_search_gas_give",
  zat_b57_den_of_the_bloodsucker_spawn_gas: "zat_b57_den_of_the_bloodsucker_spawn_gas",
  zat_b57_den_of_the_bloodsucker_talk_shystriy: "zat_b57_den_of_the_bloodsucker_talk_shystriy",
  zat_b57_den_of_the_bloodsucker_tell_stalkers_about_destroy_lair_give:
    "zat_b57_den_of_the_bloodsucker_tell_stalkers_about_destroy_lair_give",
  zat_b57_den_of_the_bloodsucker_twist_vintil_give: "zat_b57_den_of_the_bloodsucker_twist_vintil_give",
  zat_b57_gas_running_play: "zat_b57_gas_running_play",
  zat_b57_gas_running_stop: "zat_b57_gas_running_stop",
  zat_b57_generic_dialog_done: "zat_b57_generic_dialog_done",
  zat_b57_nimble_reward_dialog_done: "zat_b57_nimble_reward_dialog_done",
  zat_b57_nimble_talk_about_gas: "zat_b57_nimble_talk_about_gas",
  zat_b57_roar_play: "zat_b57_roar_play",
  zat_b57_set_bloodsucker_attacker_1_state: "zat_b57_set_bloodsucker_attacker_1_state",
  zat_b57_set_bloodsucker_attacker_2_state: "zat_b57_set_bloodsucker_attacker_2_state",
  zat_b57_set_bloodsucker_attacker_3_state: "zat_b57_set_bloodsucker_attacker_3_state",
  zat_b57_set_bloodsucker_state: "zat_b57_set_bloodsucker_state",
  /**
   * Zaton b5.
   */
  zat_b5_actor_bandit_go_to_trader: "zat_b5_actor_bandit_go_to_trader",
  zat_b5_actor_go_to_trader: "zat_b5_actor_go_to_trader",
  zat_b5_actor_help_bandits: "zat_b5_actor_help_bandits",
  zat_b5_actor_help_dealer: "zat_b5_actor_help_dealer",
  zat_b5_actor_help_stalkers: "zat_b5_actor_help_stalkers",
  zat_b5_actor_speak_barmen: "zat_b5_actor_speak_barmen",
  zat_b5_actor_speak_linker: "zat_b5_actor_speak_linker",
  zat_b5_actor_stalker_go_to_trader: "zat_b5_actor_stalker_go_to_trader",
  zat_b5_actor_together_dealer: "zat_b5_actor_together_dealer",
  zat_b5_actor_with_bandits: "zat_b5_actor_with_bandits",
  zat_b5_actor_with_dealer: "zat_b5_actor_with_dealer",
  zat_b5_actor_with_stalkers: "zat_b5_actor_with_stalkers",
  zat_b5_bandit_hit: "zat_b5_bandit_hit",
  zat_b5_bandit_in_fight: "zat_b5_bandit_in_fight",
  zat_b5_bandit_speak_1_done: "zat_b5_bandit_speak_1_done",
  zat_b5_bandits_death: "zat_b5_bandits_death",
  zat_b5_come_to_bandits_complete: "zat_b5_come_to_bandits_complete",
  zat_b5_come_to_bandits_done: "zat_b5_come_to_bandits_done",
  zat_b5_come_to_dealer_done: "zat_b5_come_to_dealer_done",
  zat_b5_come_to_stalkers: "zat_b5_come_to_stalkers",
  zat_b5_cover_dealer_done: "zat_b5_cover_dealer_done",
  zat_b5_dealer_easy_revard: "zat_b5_dealer_easy_revard",
  zat_b5_dealer_full_revard: "zat_b5_dealer_full_revard",
  zat_b5_dealer_speak_1_done: "zat_b5_dealer_speak_1_done",
  zat_b5_dealer_speak_2_done: "zat_b5_dealer_speak_2_done",
  zat_b5_meat: "zat_b5_meat",
  zat_b5_meat_online: "zat_b5_meat_online",
  zat_b5_protect_dealer_done: "zat_b5_protect_dealer_done",
  zat_b5_spawn_enemy: "zat_b5_spawn_enemy",
  zat_b5_speak_dealer_done: "zat_b5_speak_dealer_done",
  zat_b5_stalker_attack_dealer: "zat_b5_stalker_attack_dealer",
  zat_b5_stalker_death: "zat_b5_stalker_death",
  zat_b5_stalker_hit: "zat_b5_stalker_hit",
  zat_b5_stalker_leader_end: "zat_b5_stalker_leader_end",
  zat_b5_stalkers_death: "zat_b5_stalkers_death",
  zat_b5_start: "zat_b5_start",
  zat_b5_start_quest_stalkers: "zat_b5_start_quest_stalkers",
  zat_b5_sultan_close_by_trader: "zat_b5_sultan_close_by_trader",
  zat_b5_sultan_dead: "zat_b5_sultan_dead",
  zat_b5_sultan_speak_for_stalkers: "zat_b5_sultan_speak_for_stalkers",
  zat_b5_trader_death: "zat_b5_trader_death",
  zat_b5_trader_death_info: "zat_b5_trader_death_info",
  /**
   * Zaton b7.
   */
  zat_b7_actor_help_bandits: "zat_b7_actor_help_bandits",
  zat_b7_actor_help_stalkers: "zat_b7_actor_help_stalkers",
  zat_b7_actor_killed_victims_self: "zat_b7_actor_killed_victims_self",
  zat_b7_actor_now_duty_illicit_dealer: "zat_b7_actor_now_duty_illicit_dealer",
  zat_b7_actor_really_helped_bandits: "zat_b7_actor_really_helped_bandits",
  zat_b7_actor_really_helped_stalkers: "zat_b7_actor_really_helped_stalkers",
  zat_b7_actor_refused_to_be_robbed: "zat_b7_actor_refused_to_be_robbed",
  zat_b7_actor_robbed: "zat_b7_actor_robbed",
  zat_b7_actor_teleport: "zat_b7_actor_teleport",
  zat_b7_actor_with_bandits: "zat_b7_actor_with_bandits",
  zat_b7_actor_with_stalkers: "zat_b7_actor_with_stalkers",
  zat_b7_attack_started: "zat_b7_attack_started",
  zat_b7_bandit_boss_sultan_b52_about_nimble_dialog_done: "zat_b7_bandit_boss_sultan_b52_about_nimble_dialog_done",
  zat_b7_bandit_boss_sultan_b52_about_snag: "zat_b7_bandit_boss_sultan_b52_about_snag",
  zat_b7_bandit_boss_sultan_b7_give_task_dialog_told: "zat_b7_bandit_boss_sultan_b7_give_task_dialog_told",
  zat_b7_raider_plan: "zat_b7_raider_plan",
  zat_b7_sound_play: "zat_b7_sound_play",
  zat_b7_stalker_raider_leader_alive: "zat_b7_stalker_raider_leader_alive",
  zat_b7_stalker_raider_leader_on_position: "zat_b7_stalker_raider_leader_on_position",
  zat_b7_stalker_victim_leader_alive: "zat_b7_stalker_victim_leader_alive",
  zat_b7_stalkers_raiders_attack: "zat_b7_stalkers_raiders_attack",
  zat_b7_stalkers_raiders_attack_started: "zat_b7_stalkers_raiders_attack_started",
  zat_b7_stalkers_raiders_meet: "zat_b7_stalkers_raiders_meet",
  zat_b7_stalkers_raiders_reward_given: "zat_b7_stalkers_raiders_reward_given",
  zat_b7_stalkers_victims_know_about_raid: "zat_b7_stalkers_victims_know_about_raid",
  zat_b7_stalkers_victims_prepare: "zat_b7_stalkers_victims_prepare",
  zat_b7_stalkers_victims_reward_given: "zat_b7_stalkers_victims_reward_given",
  zat_b7_stalkers_victims_task_given: "zat_b7_stalkers_victims_task_given",
  zat_b7_task_end: "zat_b7_task_end",
  zat_b7_victims_disappeared: "zat_b7_victims_disappeared",
} as const;

export type TInfoPortions = typeof info_portions;

export type TInfoPortion = TInfoPortions[keyof TInfoPortions];
