export enum EGameEvent {
  ACTOR_NET_SPAWN = "ACTOR_NET_SPAWN",
  ACTOR_NET_DESTROY = "ACTOR_NET_DESTROY",
  ACTOR_UPDATE = "ACTOR_UPDATE",
  HIT = "HIT",
  MONSTER_HIT = "MONSTER_HIT",
  NPC_HIT = "NPC_HIT",
  ENEMY_SEE_ACTOR = "ENEMY_SEE_ACTOR",
  ACTOR_SEE_ENEMY = "ACTOR_SEE_ENEMY",
  NPC_SHOT_ACTOR = "NPC_SHOT_ACTOR",
  MAIN_MENU_ON = "MAIN_MENU_ON",
  MAIN_MENU_OFF = "MAIN_MENU_OFF",
}
