import { describe, expect, it } from "@jest/globals";

import { baseStates } from "@/engine/core/animation/states/base";
import { EStalkerState } from "@/engine/core/animation/types";
import { assertArraysIntersecting } from "@/fixtures/engine";
import { mockFromLuaTable } from "@/fixtures/lua";

describe("base states list", () => {
  it("should list all needed animations", () => {
    expect(baseStates.length()).toBe(103);

    assertArraysIntersecting(mockFromLuaTable(baseStates).getKeysArray(), [
      EStalkerState.IDLE,
      EStalkerState.SMART_COVER,
      EStalkerState.WALK,
      EStalkerState.WALK_NOWEAP,
      EStalkerState.RUN,
      EStalkerState.SPRINT,
      EStalkerState.PATROL,
      EStalkerState.PATROL_FIRE,
      EStalkerState.RAID,
      EStalkerState.RAID_FIRE,
      EStalkerState.SNEAK,
      EStalkerState.SNEAK_RUN,
      EStalkerState.SNEAK_NO_WPN,
      EStalkerState.SNEAK_FIRE,
      EStalkerState.ASSAULT,
      EStalkerState.ASSAULT_FIRE,
      EStalkerState.RUSH,
      EStalkerState.WAIT,
      EStalkerState.WAIT_TRADE,
      EStalkerState.WAIT_NA,
      EStalkerState.GUARD,
      EStalkerState.GUARD_CHASOVOY,
      EStalkerState.GUARD_NA,
      EStalkerState.GUARD_FIRE,
      EStalkerState.THREAT,
      EStalkerState.THREAT_DANGER,
      EStalkerState.GIVE_ORDERS,
      EStalkerState.THREAT_HELI,
      EStalkerState.THREAT_NA,
      EStalkerState.THREAT_FIRE,
      EStalkerState.THREAT_SNIPER_FIRE,
      EStalkerState.HIDE,
      EStalkerState.HIDE_NA,
      EStalkerState.HIDE_FIRE,
      EStalkerState.HIDE_SNIPER_FIRE,
      EStalkerState.CAUTION,
      EStalkerState.CHOOSE,
      EStalkerState.PRESS,
      EStalkerState.WARD,
      EStalkerState.WARDING_SHORT,
      EStalkerState.WARD_NOWEAP,
      EStalkerState.WARD_NOWEAP_SHORT,
      EStalkerState.FOLD_ARMS,
      EStalkerState.SEARCH,
      EStalkerState.STOOP_NO_WEAP,
      EStalkerState.SALUT,
      EStalkerState.SALUT_FREE,
      EStalkerState.PRISONER,
      EStalkerState.HIDE_NO_WPN,
      EStalkerState.SIT,
      EStalkerState.SIT_KNEE,
      EStalkerState.SIT_ASS,
      EStalkerState.SLEEP_SIT,
      EStalkerState.EAT_BREAD,
      EStalkerState.EAT_VODKA,
      EStalkerState.EAT_ENERGY,
      EStalkerState.EAT_KOLBASA,
      EStalkerState.PLAY_GUITAR,
      EStalkerState.PLAY_HARMONICA,
      EStalkerState.SLEEP,
      EStalkerState.HELLO,
      EStalkerState.HELLO_WPN,
      EStalkerState.REFUSE,
      EStalkerState.CLAIM,
      EStalkerState.BACKOFF,
      EStalkerState.BACKOFF2,
      EStalkerState.PUNCH,
      EStalkerState.SEARCH_CORPSE,
      EStalkerState.HELP_WOUNDED,
      EStalkerState.HELP_WOUNDED_WITH_MEDKIT,
      EStalkerState.DYNAMITE,
      EStalkerState.BINOCULAR,
      EStalkerState.HIDE_RAC,
      EStalkerState.WAIT_RAC,
      EStalkerState.WAIT_RAC_NOWEAP,
      EStalkerState.WAIT_RAC_STC,
      EStalkerState.GUARD_RAC,
      EStalkerState.PROBE_STAND,
      EStalkerState.PROBE_STAND_DETECTOR_ADVANCED,
      EStalkerState.PROBE_STAND_DETECTOR_ELITE,
      EStalkerState.PROBE_WAY,
      EStalkerState.PROBE_WAY_DETECTOR_ADVANCED,
      EStalkerState.PROBE_WAY_DETECTOR_ELITE,
      EStalkerState.PROBE_CROUCH,
      EStalkerState.PROBE_CROUCH_DETECTOR_ADVANCED,
      EStalkerState.PROBE_CROUCH_DETECTOR_ELITE,
      EStalkerState.SCANER_STAND,
      EStalkerState.SCANER_WAY,
      EStalkerState.SCANER_CROUCH,
      EStalkerState.HANDS_UP,
      EStalkerState.WOUNDED,
      EStalkerState.WOUNDED_HEAVY,
      EStalkerState.WOUNDED_HEAVY_2,
      EStalkerState.WOUNDED_HEAVY_3,
      EStalkerState.WOUNDED_ZOMBIE,
      EStalkerState.TRANS_0,
      EStalkerState.TRANS_1,
      EStalkerState.TRANS_ZOMBIED,
      EStalkerState.TALK_DEFAULT,
      EStalkerState.PSY_PAIN,
      EStalkerState.PSY_ARMED,
      EStalkerState.PSY_SHOOT,
      EStalkerState.LAY_ON_BED,
    ]);
  });
});
