import { LTX_EXTEND, quoted } from "#/utils";

export const config = {
  zone_mine_thermal: {
    [LTX_EXTEND]: "zone_base",
    GroupControlSection: "spawn_group_zone",
    $def_sphere: 2,
    $prefetch: 16,
    class: "ZS_MBALD",
    accamulate_time: 250,
    attenuation: 1,
    awaking_time: 100,
    blowout_light: "on",
    blowout_particles: "static\\zharka_static",
    blowout_sound: "anomaly\\zhar_blow",
    blowout_time: 7000,
    blowout_wind: "off",
    disable_idle_time: 50_000,
    disable_time: 10_000,
    disable_time_small: -1,
    ef_anomaly_type: 1,
    ef_weapon_type: 13,
    effective_radius: 1.0,
    entrance_sound: "ambient\\zhar",
    hit_big_particles: "damage_fx\\burn_creatures00",
    hit_impulse_scale: 0.0,
    hit_small_particles: "damage_fx\\burn_creatures",
    hit_sound: "ambient\\zhar",
    hit_type: "light_burn",
    idle_big_particles: "damage_fx\\burn_creatures00",
    idle_light: "off",
    idle_light_anim: "koster_01",
    idle_light_height: 0.7,
    idle_light_range: 8.0,
    idle_particles: "static\\buble_distort",
    idle_particles_dont_stop: true,
    idle_small_particles: "damage_fx\\burn_creatures",
    idle_sound: "anomaly\\fire_idle",
    ignore_artefacts: true,
    ignore_nonalive: false,
    ignore_small: false,
    light_color: [1.9, 1.6, 1.3],
    light_height: 2,
    light_range: 9.0,
    light_time: 10,
    max_start_power: 1.0,
    postprocess: "postprocess_thermal_mine",
    shape_edge_color: [32, 32, 32, 255],
    shape_transp_color: [255, 0, 0, 60],
  },
  zone_mine_thermal_weak: {
    [LTX_EXTEND]: "zone_mine_thermal",
    $spawn: quoted("zones\\mine_thermal_weak"),
    max_start_power: "0.2",
    use_secondary_hit: true,
    secondary_hit_power: 0.008,
  },
  zone_mine_thermal_average: {
    [LTX_EXTEND]: "zone_mine_thermal",
    $spawn: quoted("zones\\mine_thermal_average"),
    max_start_power: 0.2,
    use_secondary_hit: true,
    secondary_hit_power: 0.008,
  },
  zone_mine_thermal_strong: {
    [LTX_EXTEND]: "zone_mine_thermal",
    $spawn: quoted("zones\\mine_thermal_strong"),
    max_start_power: 0.2,
    use_secondary_hit: true,
    secondary_hit_power: 0.008,
  },
  zone_mine_steam: {
    [LTX_EXTEND]: "zone_base",
    postprocess: "postprocess_steam_mine",
    blowout_particles: "static\\zharka_static_steam",
    hit_small_particles: "damage_fx\\smoke",
    hit_big_particles: "damage_fx\\smoke",
    idle_small_particles: "damage_fx\\smoke",
    idle_big_particles: "damage_fx\\smoke",
    idle_sound: "anomaly\\steam",
    blowout_sound: "anomaly\\steam_blowout",
    hit_sound: "anomaly\\steam_hit",
    entrance_sound: "anomaly\\steam_hit",
    blowout_light: "off",
  },
  zone_mine_steam_weak: {
    [LTX_EXTEND]: ["zone_mine_thermal_weak", "zone_mine_steam"],
    $spawn: quoted("zones\\scenes\\mine_steam_weak"),
    max_start_power: 0.17,
    use_secondary_hit: true,
    secondary_hit_power: 0.01,
  },
  zone_mine_steam_average: {
    [LTX_EXTEND]: ["zone_mine_thermal_average", "zone_mine_steam"],
    $spawn: quoted("zones\\scenes\\mine_steam_average"),
    max_start_power: 0.17,
    use_secondary_hit: true,
    secondary_hit_power: 0.01,
  },
  zone_mine_steam_strong: {
    [LTX_EXTEND]: ["zone_mine_thermal_strong", "zone_mine_steam"],
    $spawn: quoted("zones\\scenes\\mine_steam_strong"),
    max_start_power: 0.17,
    use_secondary_hit: true,
    secondary_hit_power: 0.01,
  },
  zone_zharka_static: {
    [LTX_EXTEND]: ["zone_mine_thermal"],
    postprocess: "postprocess_flame",
    idle_sound: "ambient\\fire2",
  },
  zone_zharka_static_weak: {
    [LTX_EXTEND]: ["zone_zharka_static"],
    $spawn: quoted("zones\\mp\\zharka_statik_weak"),
    max_start_power: 0.5,
  },
  zone_zharka_static_average: {
    [LTX_EXTEND]: ["zone_zharka_static"],
    $spawn: quoted("zones\\mp\\zharka_statik_average"),
    max_start_power: 1.2,
  },
  zone_zharka_static_strong: {
    [LTX_EXTEND]: ["zone_zharka_static"],
    $spawn: quoted("zones\\mp\\zharka_statik_strong"),
    max_start_power: 2,
  },
};
