cli:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - cli/**

binaries:
  - changed-files:
      - any-glob-to-any-file: cli/bin/**

test:
  - changed-files:
      - any-glob-to-any-file:
          - src/**/*.test.ts
          - src/fixtures/**

configs:
  - changed-files:
      - any-glob-to-any-file: src/engine/configs/**

ai:
  - changed-files:
      - any-glob-to-any-file: src/engine/core/ai/**

animation:
  - changed-files:
      - any-glob-to-any-file: src/engine/core/animation/**

managers:
  - changed-files:
      - any-glob-to-any-file: src/engine/core/managers/**

schemes:
  - changed-files:
      - any-glob-to-any-file: src/engine/core/schemes/**

extensions:
  - changed-files:
      - any-glob-to-any-file: src/engine/extensions/**

ui:
  - changed-files:
      - any-glob-to-any-file:
          - src/engine/forms/**
          - src/engine/core/ui/**

scripts:
  - changed-files:
      - any-glob-to-any-file: src/engine/scripts/**

translations:
  - changed-files:
      - any-glob-to-any-file: src/engine/translations/**

resources:
  - changed-files:
      - any-glob-to-any-file: src/resources/**

typedefs:
  - changed-files:
      - any-glob-to-any-file: src/typedefs/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - package-lock.json
