import { JSXNode, render } from "jsx-xml";

/**
 * Render received node to text for saving.
 */
export function renderJsxToXmlText(
  node: JSXNode,
  comment: string = `<!-- Generated by xrf util at: ${new Date().toString()} -->\n\n`
): string {
  return (
    comment +
    render(node, {
      createOptions: { headless: true },
      endOptions: { allowEmpty: true, pretty: true },
    })
  );
}
