import { JSXNode, render } from "jsx-xml";

/**
 * Render received node to text for saving.
 */
export function renderJsxToXmlText(
  node: JSXNode,
  comment: string = `<!-- Generated by xrf util at: ${new Date().toString()} -->\n\n`
): string {
  if (typeof node === "string") {
    return comment + node.trim().replace(/\r\n|\r|\n/g, "\r\n") + "\r\n";
  }

  return (
    comment +
    render(node, {
      createOptions: { headless: true },
      endOptions: {
        allowEmpty: true,
        pretty: true,
        newline: "\r\n",
      },
    })
  );
}
