/* eslint sort-keys-fix/sort-keys-fix: "error" */

/**
 * todo;
 */
export const classIds = {
  actor: 90,
  art_bast_artefact: 0,
  art_black_drops: 1,
  art_cta: 3,
  art_dummy: 4,
  art_electric_ball: 5,
  art_faded_ball: 6,
  art_galantine: 7,
  art_gravi: 8,
  art_gravi_black: 2,
  art_mercury_ball: 9,
  art_needles: 10,
  art_rusty_hair: 11,
  art_thorn: 12,
  art_zuda: 13,
  artefact: 41,
  artefact_s: 102,
  bloodsucker: 14,
  bloodsucker_s: 108,
  boar: 15,
  boar_s: 109,
  burer: 16,
  burer_s: 110,
  car: 52,
  cat: 17,
  cat_s: 111,
  chimera: 29,
  chimera_s: 112,
  controller: 18,
  controller_s: 113,
  crow: 19,
  destrphys_s: 93,
  device_detector_advanced: 53,
  device_detector_elite: 54,
  device_detector_scientific: 57,
  device_detector_simple: 58,
  device_flare: 55,
  device_pda: 56,
  device_torch: 59,
  device_torch_s: 146,
  dog_black: 20,
  dog_red: 23,
  dog_s: 116,
  equ_exo: 60,
  equ_military: 61,
  equ_scientific: 62,
  equ_stalker: 63,
  equ_stalker_s: 65,
  flesh: 24,
  flesh_group: 25,
  flesh_s: 117,
  fracture: 26,
  fracture_s: 119,
  game: 70,
  game_cl_artefact_hunt: 45,
  game_cl_capture_the_artefact: 46,
  game_cl_deathmatch: 47,
  game_cl_single: 48,
  game_cl_team_deathmatch: 49,
  game_sv_artefact_hunt: 129,
  game_sv_capture_the_artefact: 130,
  game_sv_deathmatch: 131,
  game_sv_single: 132,
  game_sv_team_deathmatch: 133,
  game_ui_artefact_hunt: 147,
  game_ui_capture_the_artefact: 148,
  game_ui_deathmatch: 149,
  game_ui_single: 150,
  game_ui_team_deathmatch: 151,
  gigant_s: 118,
  graph_point: 28,
  hanging_lamp: 94,
  helicopter: 50,
  helmet: 64,
  hlamp_s: 125,
  hud_manager: 74,
  inventory_box: 95,
  inventory_box_s: 140,
  level: 69,
  level_changer: 84,
  level_changer_s: 85,
  main_menu: 86,
  mp_players_bag: 87,
  nogravity_zone: 211,
  obj_antirad: 75,
  obj_antirad_s: 135,
  obj_attachable: 76,
  obj_bandage: 77,
  obj_bandage_s: 136,
  obj_bolt: 78,
  obj_bottle: 79,
  obj_bottle_s: 137,
  obj_breakable: 91,
  obj_climable: 92,
  obj_document: 80,
  obj_explosive: 81,
  obj_explosive_s: 138,
  obj_food: 82,
  obj_food_s: 139,
  obj_medkit: 83,
  obj_medkit_s: 142,
  obj_pda_s: 144,
  obj_phskeleton: 100,
  obj_phys_destroyable: 99,
  obj_physic: 96,
  online_offline_group: 88,
  online_offline_group_s: 89,
  phantom: 30,
  poltergeist: 31,
  poltergeist_s: 120,
  projector: 98,
  pseudo_gigant: 27,
  pseudodog_s: 121,
  psy_dog: 22,
  psy_dog_phantom: 21,
  psy_dog_phantom_s: 114,
  psy_dog_s: 115,
  rat: 32,
  script_actor: 134,
  script_heli: 51,
  script_object: 103,
  script_phys: 97,
  script_restr: 127,
  script_stalker: 35,
  script_zone: 101,
  smart_cover: 104,
  smart_terrain: 105,
  smart_zone: 106,
  smartcover_s: 107,
  snork: 33,
  snork_s: 122,
  space_restrictor: 126,
  spectator: 128,
  stalker: 34,
  team_base_zone: 214,
  torrid_zone: 215,
  trader: 36,
  tushkano: 37,
  tushkano_s: 123,
  wpn_ak74: 173,
  wpn_ak74_s: 152,
  wpn_ammo: 39,
  wpn_ammo_m209: 42,
  wpn_ammo_m209_s: 141,
  wpn_ammo_og7b: 43,
  wpn_ammo_og7b_s: 143,
  wpn_ammo_s: 40,
  wpn_ammo_vog25: 44,
  wpn_ammo_vog25_s: 145,
  wpn_auto_shotgun_s: 153,
  wpn_binoc: 159,
  wpn_binocular: 174,
  wpn_binocular_s: 154,
  wpn_bm16: 175,
  wpn_bm16_s: 155,
  wpn_fn2000: 176,
  wpn_fort: 177,
  wpn_grenade_f1: 66,
  wpn_grenade_f1_s: 67,
  wpn_grenade_fake: 68,
  wpn_grenade_launcher: 178,
  wpn_grenade_launcher_s: 156,
  wpn_grenade_rgd5: 71,
  wpn_grenade_rgd5_s: 72,
  wpn_grenade_rpg7: 73,
  wpn_groza: 179,
  wpn_groza_s: 157,
  wpn_hpsa: 180,
  wpn_hpsa_s: 158,
  wpn_knife: 181,
  wpn_lr300: 182,
  wpn_lr300_s: 160,
  wpn_pm: 183,
  wpn_pm_s: 161,
  wpn_rg6: 184,
  wpn_rg6_s: 162,
  wpn_rpg7: 185,
  wpn_rpg7_s: 163,
  wpn_scope: 186,
  wpn_scope_s: 164,
  wpn_shotgun: 187,
  wpn_shotgun_s: 165,
  wpn_silencer: 188,
  wpn_silencer_s: 166,
  wpn_stat_mgun: 189,
  wpn_svd: 190,
  wpn_svd_s: 167,
  wpn_svu: 191,
  wpn_svu_s: 168,
  wpn_usp45: 192,
  wpn_usp45_s: 169,
  wpn_val: 193,
  wpn_val_s: 170,
  wpn_vintorez: 194,
  wpn_vintorez_s: 171,
  wpn_walther: 195,
  wpn_walther_s: 172,
  wpn_wmagaz: 196,
  wpn_wmaggl: 197,
  zombie: 38,
  zombie_s: 124,
  zone: 216,
  zone_acid_fog: 204,
  zone_bfuzz: 205,
  zone_bfuzz_s: 198,
  zone_campfire: 206,
  zone_dead: 207,
  zone_galant_s: 199,
  zone_galantine: 208,
  zone_mbald_s: 200,
  zone_mincer: 210,
  zone_mincer_s: 201,
  zone_mosquito_bald: 209,
  zone_radio_s: 202,
  zone_radioactive: 212,
  zone_rusty_hair: 213,
  zone_torrid_s: 203,
};

/**
 * todo;
 */
export const monsterClassIds = {
  // --		[class_ids.cat_s] 					: true,
  // --		[class_ids.fracture_s] 				: true,
  // --		[class_ids.zombie_s] 				: true,
  [classIds.bloodsucker_s]: true,
  [classIds.boar_s]: true,
  [classIds.burer_s]: true,
  [classIds.chimera_s]: true,
  [classIds.controller_s]: true,
  [classIds.dog_s]: true,
  [classIds.flesh_s]: true,
  [classIds.gigant_s]: true,
  [classIds.poltergeist_s]: true,
  [classIds.pseudodog_s]: true,
  [classIds.psy_dog_phantom_s]: true,
  [classIds.psy_dog_s]: true,
  [classIds.snork_s]: true,
  [classIds.tushkano_s]: true,
} as const;

/**
 * todo;
 */
export const stalkerClassIds = {
  [classIds.script_actor]: true,
  [classIds.script_stalker]: true,
} as const;

/**
 * todo;
 */
export const weaponClassIds = {
  [classIds.wpn_vintorez_s]: true,
  [classIds.wpn_ak74_s]: true,
  [classIds.wpn_lr300_s]: true,
  [classIds.wpn_hpsa_s]: true,
  [classIds.wpn_pm_s]: true,
  [classIds.wpn_shotgun_s]: true,
  [classIds.wpn_auto_shotgun_s]: true,
  [classIds.wpn_bm16_s]: true,
  [classIds.wpn_svd_s]: true,
  [classIds.wpn_svu_s]: true,
  [classIds.wpn_rg6_s]: true,
  [classIds.wpn_rpg7_s]: true,
  [classIds.wpn_val_s]: true,
  [classIds.wpn_walther_s]: true,
  [classIds.wpn_usp45_s]: true,
  [classIds.wpn_groza_s]: true,
  [classIds.wpn_knife]: true,
  [classIds.wpn_grenade_f1_s]: true,
  [classIds.wpn_grenade_rgd5_s]: true,
  [classIds.wpn_grenade_launcher]: true,
  [classIds.wpn_grenade_fake]: true,
} as const;

/**
 * todo;
 */
export const artefactClassIds = {
  [classIds.art_bast_artefact]: true,
  [classIds.art_black_drops]: true,
  [classIds.art_dummy]: true,
  [classIds.art_electric_ball]: true,
  [classIds.art_faded_ball]: true,
  [classIds.art_galantine]: true,
  [classIds.art_gravi]: true,
  [classIds.art_gravi_black]: true,
  [classIds.art_mercury_ball]: true,
  [classIds.art_needles]: true,
  [classIds.art_rusty_hair]: true,
  [classIds.art_thorn]: true,
  [classIds.art_zuda]: true,
  [classIds.artefact]: true,
  [classIds.artefact_s]: true,
} as const;

/**
 * todo;
 */
export const gameClassId = {
  CL_AHUNT: "CL_AHUNT",
  CL_CTA: "CL_CTA",
  CL_DM: "CL_DM",
  CL_SINGL: "CL_SINGL",
  CL_TDM: "CL_TDM",
  SV_AHUNT: "SV_AHUNT",
  SV_CTA: "SV_CTA",
  SV_DM: "SV_DM",
  SV_SINGL: "SV_SINGL",
  SV_TDM: "SV_TDM",
  UI_AHUNT: "UI_AHUNT",
  UI_CTA: "UI_CTA",
  UI_DM: "UI_DM",
  UI_SINGL: "UI_SINGL",
  UI_TDM: "UI_TDM",
} as const;

/**
 * todo;
 */
export type TGameClassId = (typeof gameClassId)[keyof typeof gameClassId];

/**
 * todo;
 * C++ declared class identifiers from client side.
 */
export enum EClientObjectClass {
  CAI_Bloodsucker = "CAI_Bloodsucker",
  CAI_Boar = "CAI_Boar",
  CAI_Dog = "CAI_Dog",
  CAI_Flesh = "CAI_Flesh",
  CAI_PseudoDog = "CAI_PseudoDog",
  CAI_Stalker = "CAI_Stalker",
  CActor = "CActor",
  CAdvancedDetector = "CAdvancedDetector",
  CAntirad = "CAntirad",
  CBottleItem = "CBottleItem",
  CBurer = "CBurer",
  CCat = "CCat",
  CChimera = "CChimera",
  CController = "CController",
  CDestroyablePhysicsObject = "CDestroyablePhysicsObject",
  CElectricBall = "CElectricBall",
  CEliteDetector = "CEliteDetector",
  CExplosiveItem = "CExplosiveItem",
  CF1 = "CF1",
  CFoodItem = "CFoodItem",
  CFracture = "CFracture",
  CGrenadeLauncher = "CGrenadeLauncher",
  CHairsZone = "CHairsZone",
  CHelicopter = "CHelicopter",
  CHelmet = "CHelmet",
  CInventoryBox = "CInventoryBox",
  CLevelChanger = "CLevelChanger",
  CMedkit = "CMedkit",
  CMincer = "CMincer",
  CMosquitoBald = "CMosquitoBald",
  CPda = "CPda",
  CPhysicObject = "CPhysicObject",
  CPoltergeist = "CPoltergeist",
  CPseudoGigant = "CPseudoGigant",
  CPsyDog = "CPsyDog",
  CPsyDogPhantom = "CPsyDogPhantom",
  CRGD5 = "CRGD5",
  CRadioactiveZone = "CRadioactiveZone",
  CScientificDetector = "CScientificDetector",
  CScope = "CScope",
  CSilencer = "CSilencer",
  CSimpleDetector = "CSimpleDetector",
  CSnork = "CSnork",
  CStalkerOutfit = "CStalkerOutfit",
  CTorch = "CTorch",
  CTorridZone = "CTorridZone",
  CTushkano = "CTushkano",
  CWeaponAK74 = "CWeaponAK74",
  CWeaponAmmo = "CWeaponAmmo",
  CWeaponAutomaticShotgun = "CWeaponAutomaticShotgun",
  CWeaponBM16 = "CWeaponBM16",
  CWeaponGroza = "CWeaponGroza",
  CWeaponHPSA = "CWeaponHPSA",
  CWeaponKnife = "CWeaponKnife",
  CWeaponBinoculars = "CWeaponBinoculars",
  CWeaponLR300 = "CWeaponLR300",
  CWeaponPM = "CWeaponPM",
  CWeaponRG6 = "CWeaponRG6",
  CWeaponRPG7 = "CWeaponRPG7",
  CWeaponSVD = "CWeaponSVD",
  CWeaponSVU = "CWeaponSVU",
  CWeaponShotgun = "CWeaponShotgun",
  CWeaponUSP45 = "CWeaponUSP45",
  CWeaponVal = "CWeaponVal",
  CWeaponVintorez = "CWeaponVintorez",
  CWeaponWalther = "CWeaponWalther",
  CZombie = "CZombie",
  ce_smart_zone = "ce_smart_zone",
  hanging_lamp = "hanging_lamp",
  smart_cover_object = "smart_cover_object",
}

/**
 * todo;
 */
export enum EConfigClassId {
  SMART_TERRAIN = "SMRTTRRN",
}
