/* eslint sort-keys-fix/sort-keys-fix: "error" */

/**
 * List of available game treasures in original COP.
 */
export const treasures = {
  jup_hiding_place_1: "jup_hiding_place_1",
  jup_hiding_place_10: "jup_hiding_place_10",
  jup_hiding_place_11: "jup_hiding_place_11",
  jup_hiding_place_12: "jup_hiding_place_12",
  jup_hiding_place_13: "jup_hiding_place_13",
  jup_hiding_place_14: "jup_hiding_place_14",
  jup_hiding_place_15: "jup_hiding_place_15",
  jup_hiding_place_16: "jup_hiding_place_16",
  jup_hiding_place_17: "jup_hiding_place_17",
  jup_hiding_place_18: "jup_hiding_place_18",
  jup_hiding_place_19: "jup_hiding_place_19",
  jup_hiding_place_2: "jup_hiding_place_2",
  jup_hiding_place_20: "jup_hiding_place_20",
  jup_hiding_place_21: "jup_hiding_place_21",
  jup_hiding_place_22: "jup_hiding_place_22",
  jup_hiding_place_23: "jup_hiding_place_23",
  jup_hiding_place_24: "jup_hiding_place_24",
  jup_hiding_place_25: "jup_hiding_place_25",
  jup_hiding_place_26: "jup_hiding_place_26",
  jup_hiding_place_27: "jup_hiding_place_27",
  jup_hiding_place_28: "jup_hiding_place_28",
  jup_hiding_place_29: "jup_hiding_place_29",
  jup_hiding_place_3: "jup_hiding_place_3",
  jup_hiding_place_30: "jup_hiding_place_30",
  jup_hiding_place_31: "jup_hiding_place_31",
  jup_hiding_place_32: "jup_hiding_place_32",
  jup_hiding_place_33: "jup_hiding_place_33",
  jup_hiding_place_34: "jup_hiding_place_34",
  jup_hiding_place_35: "jup_hiding_place_35",
  jup_hiding_place_36: "jup_hiding_place_36",
  jup_hiding_place_37: "jup_hiding_place_37",
  jup_hiding_place_38: "jup_hiding_place_38",
  jup_hiding_place_39: "jup_hiding_place_39",
  jup_hiding_place_4: "jup_hiding_place_4",
  jup_hiding_place_40: "jup_hiding_place_40",
  jup_hiding_place_41: "jup_hiding_place_41",
  jup_hiding_place_42: "jup_hiding_place_42",
  jup_hiding_place_43: "jup_hiding_place_43",
  jup_hiding_place_44: "jup_hiding_place_44",
  jup_hiding_place_45: "jup_hiding_place_45",
  jup_hiding_place_46: "jup_hiding_place_46",
  jup_hiding_place_47: "jup_hiding_place_47",
  jup_hiding_place_48: "jup_hiding_place_48",
  jup_hiding_place_49: "jup_hiding_place_49",
  jup_hiding_place_5: "jup_hiding_place_5",
  jup_hiding_place_50: "jup_hiding_place_50",
  jup_hiding_place_6: "jup_hiding_place_6",
  jup_hiding_place_7: "jup_hiding_place_7",
  jup_hiding_place_8: "jup_hiding_place_8",
  jup_hiding_place_9: "jup_hiding_place_9",
  zat_hiding_place_1: "zat_hiding_place_1",
  zat_hiding_place_10: "zat_hiding_place_10",
  zat_hiding_place_11: "zat_hiding_place_11",
  zat_hiding_place_12: "zat_hiding_place_12",
  zat_hiding_place_13: "zat_hiding_place_13",
  zat_hiding_place_14: "zat_hiding_place_14",
  zat_hiding_place_15: "zat_hiding_place_15",
  zat_hiding_place_16: "zat_hiding_place_16",
  zat_hiding_place_17: "zat_hiding_place_17",
  zat_hiding_place_18: "zat_hiding_place_18",
  zat_hiding_place_19: "zat_hiding_place_19",
  zat_hiding_place_2: "zat_hiding_place_2",
  zat_hiding_place_20: "zat_hiding_place_20",
  zat_hiding_place_21: "zat_hiding_place_21",
  zat_hiding_place_22: "zat_hiding_place_22",
  zat_hiding_place_23: "zat_hiding_place_23",
  zat_hiding_place_24: "zat_hiding_place_24",
  zat_hiding_place_25: "zat_hiding_place_25",
  zat_hiding_place_26: "zat_hiding_place_26",
  zat_hiding_place_27: "zat_hiding_place_27",
  zat_hiding_place_28: "zat_hiding_place_28",
  zat_hiding_place_29: "zat_hiding_place_29",
  zat_hiding_place_3: "zat_hiding_place_3",
  zat_hiding_place_30: "zat_hiding_place_30",
  zat_hiding_place_31: "zat_hiding_place_31",
  zat_hiding_place_32: "zat_hiding_place_32",
  zat_hiding_place_33: "zat_hiding_place_33",
  zat_hiding_place_34: "zat_hiding_place_34",
  zat_hiding_place_35: "zat_hiding_place_35",
  zat_hiding_place_36: "zat_hiding_place_36",
  zat_hiding_place_37: "zat_hiding_place_37",
  zat_hiding_place_38: "zat_hiding_place_38",
  zat_hiding_place_39: "zat_hiding_place_39",
  zat_hiding_place_4: "zat_hiding_place_4",
  zat_hiding_place_40: "zat_hiding_place_40",
  zat_hiding_place_41: "zat_hiding_place_41",
  zat_hiding_place_42: "zat_hiding_place_42",
  zat_hiding_place_43: "zat_hiding_place_43",
  zat_hiding_place_44: "zat_hiding_place_44",
  zat_hiding_place_45: "zat_hiding_place_45",
  zat_hiding_place_46: "zat_hiding_place_46",
  zat_hiding_place_47: "zat_hiding_place_47",
  zat_hiding_place_48: "zat_hiding_place_48",
  zat_hiding_place_49: "zat_hiding_place_49",
  zat_hiding_place_5: "zat_hiding_place_5",
  zat_hiding_place_50: "zat_hiding_place_50",
  zat_hiding_place_51: "zat_hiding_place_51",
  zat_hiding_place_52: "zat_hiding_place_52",
  zat_hiding_place_53: "zat_hiding_place_53",
  zat_hiding_place_54: "zat_hiding_place_54",
  zat_hiding_place_55: "zat_hiding_place_55",
  zat_hiding_place_6: "zat_hiding_place_6",
  zat_hiding_place_7: "zat_hiding_place_7",
  zat_hiding_place_8: "zat_hiding_place_8",
  zat_hiding_place_9: "zat_hiding_place_9",
} as const;

/**
 * Type definition of available treasures list.
 */
export type TTreasures = typeof treasures;

/**
 * Type definition of single treasure identifier.
 */
export type TTreasure = TTreasures[keyof TTreasures];
