export const enhancedDropConfig = {
  ADD_RANDOM_DISPERSION: 2.5,
  ADD_RANDOM_RATE_OWNED: 1,
  ADD_RANDOM_RATE_TRADER: 1.5,
  ADD_RANDOM_RATE_WORLD: 0.75,
  ADD_RANDOM_CHANCE: 20,
  ADD_RANDOM_COUNT: 1,
  ADD_RANDOM_RARE_CHANCE: 12,
  ADD_RANDOM_RARE_COUNT: 3,
  ADD_RANDOM_EPIC_CHANCE: 6,
  ADD_RANDOM_EPIC_COUNT: 7,
  ADD_RANDOM_LEGENDARY_CHANCE: 1,
  ADD_RANDOM_LEGENDARY_COUNT: 30,
};
