/* eslint sort-keys-fix/sort-keys-fix: "error" */

/**
 * Vanilla task identifiers declared by task-manager configs and referenced by game logic.
 *
 * @virtual
 */
export const taskIds = {
  hide_from_surge: "hide_from_surge",
  jup_a10_actor_agree_back_vano_duties: "jup_a10_actor_agree_back_vano_duties",
  jup_a12_free_prisoner: "jup_a12_free_prisoner",
  jup_a9_way_to_pripyat_gas_info: "jup_a9_way_to_pripyat_gas_info",
  jup_a9_way_to_pripyat_power_info: "jup_a9_way_to_pripyat_power_info",
  jup_a9_way_to_pripyat_search: "jup_a9_way_to_pripyat_search",
  jup_a9_way_to_pripyat_tech: "jup_a9_way_to_pripyat_tech",
  jup_a9_way_to_pripyat_way_info: "jup_a9_way_to_pripyat_way_info",
  jup_b10_ufo: "jup_b10_ufo",
  jup_b16_oasis: "jup_b16_oasis",
  jup_b19_airing_to_kopatci: "jup_b19_airing_to_kopatci",
  jup_b1_task: "jup_b1_task",
  jup_b200_tech_materials: "jup_b200_tech_materials",
  jup_b202_actor_items_stolen: "jup_b202_actor_items_stolen",
  jup_b206_anomalous_grove: "jup_b206_anomalous_grove",
  jup_b208_burers_hunt: "jup_b208_burers_hunt",
  jup_b209_hypotheses: "jup_b209_hypotheses",
  jup_b211_swamp_bloodsuckers_hunt: "jup_b211_swamp_bloodsuckers_hunt",
  jup_b212_jupiter_chimera_hunt: "jup_b212_jupiter_chimera_hunt",
  jup_b217_tech_instruments: "jup_b217_tech_instruments",
  jup_b218_actor_outfit: "jup_b218_actor_outfit",
  jup_b218_monolith: "jup_b218_monolith",
  jup_b218_pripyat_group: "jup_b218_pripyat_group",
  jup_b218_soldier: "jup_b218_soldier",
  jup_b218_stalker: "jup_b218_stalker",
  jup_b25_accuse_flint: "jup_b25_accuse_flint",
  jup_b32_addon_task_1: "jup_b32_addon_task_1",
  jup_b32_addon_task_2: "jup_b32_addon_task_2",
  jup_b32_get_scanners_addon_task: "jup_b32_get_scanners_addon_task",
  jup_b32_get_scanners_task: "jup_b32_get_scanners_task",
  jup_b32_task_1: "jup_b32_task_1",
  jup_b32_task_2: "jup_b32_task_2",
  jup_b32_task_3: "jup_b32_task_3",
  jup_b32_task_reward: "jup_b32_task_reward",
  jup_b43_stalker_assistant_contract: "jup_b43_stalker_assistant_contract",
  jup_b46_duty_founder_pda: "jup_b46_duty_founder_pda",
  jup_b46_spatial_bubble: "jup_b46_spatial_bubble",
  jup_b4_monolith_squad_help: "jup_b4_monolith_squad_help",
  jup_b6_employ_stalkers: "jup_b6_employ_stalkers",
  jup_b6_task: "jup_b6_task",
  jup_b8_heli_4_crash: "jup_b8_heli_4_crash",
  jup_b9_heli_1_crash: "jup_b9_heli_1_crash",
  pas_b400_pripyat: "pas_b400_pripyat",
  pri_a17_task_find_gauss_rifle: "pri_a17_task_find_gauss_rifle",
  pri_a18_inspect_monolith: "pri_a18_inspect_monolith",
  pri_a19_lab_x8_investigation: "pri_a19_lab_x8_investigation",
  pri_a20_check_recon_squad_task: "pri_a20_check_recon_squad_task",
  pri_a21_find_sentry_task: "pri_a21_find_sentry_task",
  pri_a22_rfi_source: "pri_a22_rfi_source",
  pri_a22_talk_with_kovalski: "pri_a22_talk_with_kovalski",
  pri_a28_evacuation: "pri_a28_evacuation",
  pri_a28_recover_medic: "pri_a28_recover_medic",
  pri_b305_check_unknown_signal: "pri_b305_check_unknown_signal",
  pri_b305_kovalskiy_talk: "pri_b305_kovalskiy_talk",
  pri_b306_task: "pri_b306_task",
  pri_b35_task: "pri_b35_task",
  zat_a2_reach_base: "zat_a2_reach_base",
  zat_b100_heli_2_crash: "zat_b100_heli_2_crash",
  zat_b101_heli_5_crash: "zat_b101_heli_5_crash",
  zat_b103_merc_bring_supplies: "zat_b103_merc_bring_supplies",
  zat_b106_hunt_himera: "zat_b106_hunt_himera",
  zat_b106_search_soroka: "zat_b106_search_soroka",
  zat_b107_evacuation_jupiter: "zat_b107_evacuation_jupiter",
  zat_b107_evacuation_pripyat: "zat_b107_evacuation_pripyat",
  zat_b107_evacuation_zaton: "zat_b107_evacuation_zaton",
  zat_b14_learn_about_strange_occurrence: "zat_b14_learn_about_strange_occurrence",
  zat_b14_learn_about_strange_occurrence_by_stalkers: "zat_b14_learn_about_strange_occurrence_by_stalkers",
  zat_b207_depot_reward_task: "zat_b207_depot_reward_task",
  zat_b207_morgan_depot_task: "zat_b207_morgan_depot_task",
  zat_b20_cross_teleport: "zat_b20_cross_teleport",
  zat_b20_plateau_way: "zat_b20_plateau_way",
  zat_b28_heli_3_crash: "zat_b28_heli_3_crash",
  zat_b29_adv_task: "zat_b29_adv_task",
  zat_b30_compass_to_barmen_task: "zat_b30_compass_to_barmen_task",
  zat_b30_percent_task: "zat_b30_percent_task",
  zat_b30_sultan_task: "zat_b30_sultan_task",
  zat_b30_task: "zat_b30_task",
  zat_b33_zaporojec: "zat_b33_zaporojec",
  zat_b3_tech_instruments: "zat_b3_tech_instruments",
  zat_b40_reconnoitre_merc_camp: "zat_b40_reconnoitre_merc_camp",
  zat_b44_tech_buddies: "zat_b44_tech_buddies",
  zat_b52_reputation: "zat_b52_reputation",
  zat_b5_barmen_reward: "zat_b5_barmen_reward",
  zat_b5_come_to_bandits: "zat_b5_come_to_bandits",
  zat_b5_come_to_dealer: "zat_b5_come_to_dealer",
  zat_b5_come_to_stalkers: "zat_b5_come_to_stalkers",
  zat_b7_stalkers_raiders: "zat_b7_stalkers_raiders",
  zat_b7_stalkers_victims: "zat_b7_stalkers_victims",
} as const;

export type TTaskIds = typeof taskIds;

export type TTaskId = TTaskIds[keyof TTaskIds];
