import { ILtxConfigDescriptor, ILtxFieldDescriptor, renderField } from "#/utils";

/**
 * todo;
 */
function renderLtxSection(name: string, object: Record<string, ILtxFieldDescriptor<unknown>>): string {
  return Object.entries(object).reduce(
    (result, [key, value]) => result + renderField(key, value) + "\n",
    `\n[${name}]\n`
  );
}

/**
 * todo;
 */
export function renderJsonToLtx(object: ILtxConfigDescriptor): string {
  const header: string = `; Generated by xrts+tstl util at: ${new Date().toString()}\n`;

  return Object.entries(object).reduce((result, [key, object]) => {
    return result + renderLtxSection(key, object);
  }, header);
}
