import { anim, CSightParams, look, move } from "xray16";

import { EStalkerState, EWeaponAnimation, IStateDescriptor } from "@/engine/core/objects/state/types";
import { getStateLibAnimationPoints } from "@/engine/core/objects/state_lib/state_lib_animpoint";
import { getStateLibScenarios } from "@/engine/core/objects/state_lib/state_manager_scenario";
import { addStateLibPriA15 } from "@/engine/core/objects/state_lib/state_mgr_pri_a15";
import { copyTable } from "@/engine/core/utils/table";

/**
 * List of default state descriptors to use in scripts.
 */
export const states: LuaTable<EStalkerState, IStateDescriptor> = {
  idle: {
    weapon: null,
    movement: null,
    mental: null,
    bodystate: null,
    animstate: null,
    animation: null,
  },
  smartcover: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: null,
    mental: null,
    bodystate: null,
    animstate: null,
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  walk: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.walk,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  walk_noweap: {
    weapon: EWeaponAnimation.NONE,
    movement: move.walk,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  run: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.run,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  sprint: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.run,
    mental: anim.panic,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  patrol: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.walk,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  patrol_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.walk,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  raid: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.walk,
    mental: anim.danger,
    special_danger_move: true,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  raid_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.walk,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  sneak: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.walk,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
  },
  sneak_run: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.run,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
  },
  sneak_no_wpn: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.walk,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
  },
  sneak_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.walk,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
  },
  assault: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.run,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  assault_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.run,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  rush: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.run,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  wait: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "idle",
  },
  wait_trade: {
    weapon: EWeaponAnimation.NONE,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "idle",
  },
  wait_na: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  guard: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "idle",
  },
  guard_chasovoy: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "idle_chasovoy",
  },
  guard_na: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  guard_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  threat: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: true,
  },
  threat_danger: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "bloodsucker_search",
  },
  give_orders: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "give_orders",
  },
  threat_heli: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  threat_na: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: true,
  },
  threat_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  threat_sniper_fire: {
    weapon: EWeaponAnimation.SNIPER_FIRE,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
  },
  hide: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: "hide",
  },
  hide_na: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
  },
  hide_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
  },
  hide_sniper_fire: {
    weapon: EWeaponAnimation.SNIPER_FIRE,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
  },
  caution: {
    weapon: null,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "caution",
  },
  choose: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "choosing",
  },
  press: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "press",
  },
  ward: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "warding",
  },
  ward_short: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "warding_short",
  },
  ward_noweap: {
    weapon: EWeaponAnimation.NONE,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "warding",
  },
  ward_noweap_short: {
    weapon: EWeaponAnimation.NONE,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "warding_short",
  },
  fold_arms: {
    weapon: EWeaponAnimation.NONE,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "fold_arms",
  },

  search: {
    weapon: null,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "poisk",
  },
  stoop_no_weap: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "stoop_no_weap",
  },
  salut: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "salut",
  },
  salut_free: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "salut_free",
  },
  prisoner: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: null,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "prisoner",
  },

  hide_no_wpn: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: "hide",
  },
  // -- ������� ���������
  sit: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "sit",
    animation: null,
  },
  sit_knee: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "sit_knee",
    animation: null,
  },
  sit_ass: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "sit_ass",
    animation: null,
  },

  play_guitar: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "sit_knee",
    animation: "play_guitar",
  },
  play_harmonica: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "sit_ass",
    animation: "play_harmonica",
  },

  sleep: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "sleeping",
  },

  hello: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "hello",
  },
  hello_wpn: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "hello",
  },

  refuse: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "refuse",
  },
  claim: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "claim",
  },
  backoff: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "backoff",
  },
  backoff2: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "backoff",
  },
  punch: {
    weapon: null,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "punch",
  },

  search_corpse: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: "search_corpse",
  },

  help_wounded: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: "help_wounded",
  },

  dynamite: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: "dynamite",
  },

  binocular: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "binocular",
  },
  hide_rac: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: "cr_raciya",
  },
  wait_rac: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "raciya",
  },
  wait_rac_noweap: {
    weapon: EWeaponAnimation.NONE,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "raciya",
  },
  wait_rac_stc: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "raciya_stc",
  },
  guard_rac: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "raciya",
  },

  probe_stand: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "probe_stand",
  },
  probe_stand_detector_advanced: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "probe_stand_detector_advanced",
  },
  probe_stand_detector_elite: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "probe_stand_detector_elite",
  },
  probe_way: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "probe_way",
  },
  probe_way_detector_advanced: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "probe_way_detector_advanced",
  },
  probe_way_detector_elite: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "probe_way_detector_elite",
  },
  probe_crouch: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "probe_crouch",
  },
  probe_crouch_detector_advanced: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "probe_crouch_detector_advanced",
  },
  probe_crouch_detector_elite: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "probe_crouch_detector_elite",
  },

  scaner_stand: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "scaner_stand",
  },
  scaner_way: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "scaner_way",
  },

  scaner_crouch: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "scaner_crouch",
  },

  hands_up: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "hands_up",
  },

  // -- �������
  wounded: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    direction: look.cur_dir,
    animstate: null,
    animation: "wounded",
  },
  wounded_heavy: {
    weapon: EWeaponAnimation.DROP,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    direction: look.cur_dir, // --CSightParams.eSightTypeAnimationDirection
    animstate: null,
    animation: "wounded_heavy_1",
  },
  wounded_heavy_2: {
    weapon: EWeaponAnimation.DROP,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    direction: look.cur_dir,
    animstate: null,
    animation: "wounded_heavy_2",
  },
  wounded_heavy_3: {
    weapon: EWeaponAnimation.DROP,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    direction: look.cur_dir,
    animstate: null,
    animation: "wounded_heavy_3",
  },
  wounded_zombie: {
    weapon: EWeaponAnimation.DROP,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    direction: look.cur_dir,
    animstate: null,
    animation: "wounded_zombie",
  },
  trans_0: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "trans_0",
  },
  trans_1: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "trans_1",
  },
  trans_zombied: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "trans_zombied",
  },
  talk_default: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "talk_default",
  },
  psy_pain: {
    weapon: EWeaponAnimation.DROP,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "psy_armed",
  },
  psy_armed: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "psy_armed",
  },
  psy_shoot: {
    weapon: EWeaponAnimation.FIRE,
    weapon_slot: 1,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "psy_shoot",
  },
  lay_on_bed: {
    weapon: EWeaponAnimation.DROP,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    direction: look.cur_dir,
    animstate: null,
    animation: "wounded_heavy_1",
  },
} as any;

copyTable(states, getStateLibAnimationPoints());
copyTable(states, getStateLibScenarios());
copyTable(states, addStateLibPriA15());
