import { stalker_ids } from "xray16";

import { TNumberId } from "@/engine/lib/types";

/**
 * Base index in game core.
 * 74 by default.
 */
const BASE: TNumberId = stalker_ids.property_script || 74;

/**
 * todo;
 */
export enum EEvaluatorId {
  IS_CORPSE_EXISTING = BASE + 50,
  IS_WOUNDED_EXISTING = BASE + 55,
  IS_STATE_IDLE_COMBAT = BASE + 101,
  IS_STATE_IDLE_ALIFE = BASE + 102,
  IS_STATE_LOGIC_ACTIVE = BASE + 104,
  IS_STATE_IDLE_ITEMS = BASE + 105,
  IS_SMART_COVER_NEEDED = BASE + 401,
  CAN_USE_SMART_COVER_IN_COMBAT = BASE + 402,
  IS_ANIMPOINT_NEEDED = BASE + 501,
  IS_ANIMPOINT_REACHED = BASE + 502,
  IS_ANIMPOINT_ACTIVE = BASE + 503,
  IS_MEET_CONTACT = BASE + 1031,
  NEED_COVER = BASE + 1071,
  IS_CAMPING_ENDED = BASE + 1081,
  IS_CLOSE_COMBAT = BASE + 1082,
  IS_SCRIPTED_COMBAT = BASE + 1110,
  IS_ABUSED = BASE + 1120,
  IS_WOUNDED = BASE + 2010,
  CAN_FIGHT = BASE + 2011,
  IS_PATROL_ENDED = BASE + 2250,
  IS_PATROL_COMMANDER = BASE + 2251,
  IS_COMBAT_ZOMBIED_ENABLED = BASE + 3110,
  IS_COMBAT_CAMPING_ENABLED = BASE + 3130,
  SEE_ENEMY = BASE + 3131,
  NEED_SLEEPER = BASE + 4191,
  NEED_WALKER = BASE + 4371,
  NEED_REMARK = BASE + 4521,
  NEED_COMPANION = BASE + 4551,
}
