--- --------------------------------------------------------------------------------------------------------------------
--- Global entrypoint for xray engine scripts
--- --------------------------------------------------------------------------------------------------------------------

-- Enable modules requiring
package.path = package.path .. string.format("%sgamedata\\?.script;", getFS():update_path("$fs_root$", ""))

--- --------------------------------------------------------------------------------------------------------------------

require("scripts.core.managers.ProfilingManager").ProfilingManager:getInstance():initialize();

require("scripts.inject.lua_globals")
require("scripts.inject.declaration")

require("scripts._extern")
