/* eslint sort-keys-fix/sort-keys-fix: "error" */

/**
 * todo;
 */
export const itemsArtefactsCaptions = {
  st_af_baloon_descr: "st_af_baloon_descr",
  st_af_baloon_name: "st_af_baloon_name",
  st_af_blood_descr: "st_af_blood_descr",
  st_af_blood_name: "st_af_blood_name",
  st_af_cristall_descr: "st_af_cristall_descr",
  st_af_cristall_flower_descr: "st_af_cristall_flower_descr",
  st_af_cristall_flower_name: "st_af_cristall_flower_name",
  st_af_cristall_name: "st_af_cristall_name",
  st_af_dummy_battery_descr: "st_af_dummy_battery_descr",
  st_af_dummy_battery_name: "st_af_dummy_battery_name",
  st_af_dummy_dummy_descr: "st_af_dummy_dummy_descr",
  st_af_dummy_dummy_name: "st_af_dummy_dummy_name",
  st_af_dummy_glassbeads_descr: "st_af_dummy_glassbeads_descr",
  st_af_dummy_glassbeads_name: "st_af_dummy_glassbeads_name",
  st_af_electra_flash_descr: "st_af_electra_flash_descr",
  st_af_electra_flash_name: "st_af_electra_flash_name",
  st_af_electra_moonlight_descr: "st_af_electra_moonlight_descr",
  st_af_electra_moonlight_name: "st_af_electra_moonlight_name",
  st_af_electra_sparkler_descr: "st_af_electra_sparkler_descr",
  st_af_electra_sparkler_name: "st_af_electra_sparkler_name",
  st_af_eye_descr: "st_af_eye_descr",
  st_af_eye_name: "st_af_eye_name",
  st_af_fire_descr: "st_af_fire_descr",
  st_af_fire_name: "st_af_fire_name",
  st_af_fireball_descr: "st_af_fireball_descr",
  st_af_fireball_name: "st_af_fireball_name",
  st_af_fuzz_kolobok_descr: "st_af_fuzz_kolobok_descr",
  st_af_fuzz_kolobok_name: "st_af_fuzz_kolobok_name",
  st_af_glass_descr: "st_af_glass_descr",
  st_af_glass_name: "st_af_glass_name",
  st_af_gold_fish_descr: "st_af_gold_fish_descr",
  st_af_gold_fish_name: "st_af_gold_fish_name",
  st_af_gravi_descr: "st_af_gravi_descr",
  st_af_gravi_name: "st_af_gravi_name",
  st_af_ice_descr: "st_af_ice_descr",
  st_af_ice_name: "st_af_ice_name",
  st_af_medusa_descr: "st_af_medusa_descr",
  st_af_medusa_name: "st_af_medusa_name",
  st_af_mincer_meat_descr: "st_af_mincer_meat_descr",
  st_af_mincer_meat_name: "st_af_mincer_meat_name",
  st_af_night_star_descr: "st_af_night_star_descr",
  st_af_night_star_name: "st_af_night_star_name",
  st_af_soul_descr: "st_af_soul_descr",
  st_af_soul_name: "st_af_soul_name",
  st_af_vyvert_descr: "st_af_vyvert_descr",
  st_af_vyvert_name: "st_af_vyvert_name",
  st_compass: "st_compass",
  st_compass_descr: "st_compass_descr",
  st_oasis_heart: "st_oasis_heart",
  st_oasis_heart_descr: "st_oasis_heart_descr",
};
