/* eslint sort-keys-fix/sort-keys-fix: "error" */

export const zaton_info_portions = {
  zat_a1_tutorial_end: "zat_a1_tutorial_end",
  zat_a23_stalker_tech_told_about_battery: "zat_a23_stalker_tech_told_about_battery",
  zat_a2_linker_b14_quest_strange_item_done: "zat_a2_linker_b14_quest_strange_item_done",
  zat_a2_linker_b14_quest_strange_item_lost_artefact: "zat_a2_linker_b14_quest_strange_item_lost_artefact",
  zat_a2_linker_b14_quest_wrong_done: "zat_a2_linker_b14_quest_wrong_done",
  zat_a2_linker_b52_about_nimble_dialog_done: "zat_a2_linker_b52_about_nimble_dialog_done",
  zat_a2_mechanic_toolkit_search: "zat_a2_mechanic_toolkit_search",
  zat_a2_stalker_barmen_b52_about_nimble_dialog_done: "zat_a2_stalker_barmen_b52_about_nimble_dialog_done",
  zat_a2_stalker_barmen_b52_about_snag: "zat_a2_stalker_barmen_b52_about_snag",
  zat_a2_stalker_barmen_hit_from_actor: "zat_a2_stalker_barmen_hit_from_actor",
  zat_a2_stalker_barmen_setup: "zat_a2_stalker_barmen_setup",
  zat_a2_toolkit_search: "zat_a2_toolkit_search",
  zat_a9_actor_conservation_info_play_sound: "zat_a9_actor_conservation_info_play_sound",
  zat_a9_actor_delivery_info_play_sound: "zat_a9_actor_delivery_info_play_sound",
  zat_a9_actor_evacuation_info_play_sound: "zat_a9_actor_evacuation_info_play_sound",
  zat_a9_actor_has_jup_a9_actor_losses_info: "zat_a9_actor_has_jup_a9_actor_losses_info",
  zat_a9_actor_has_jup_a9_actor_power_info: "zat_a9_actor_has_jup_a9_actor_power_info",
  zat_a9_actor_has_jup_a9_conservation_info: "zat_a9_actor_has_jup_a9_conservation_info",
  zat_a9_actor_has_jup_a9_delivery_info: "zat_a9_actor_has_jup_a9_delivery_info",
  zat_a9_actor_has_jup_a9_evacuation_info: "zat_a9_actor_has_jup_a9_evacuation_info",
  zat_a9_actor_has_jup_a9_meeting_info: "zat_a9_actor_has_jup_a9_meeting_info",
  zat_a9_actor_has_jup_a9_way_info: "zat_a9_actor_has_jup_a9_way_info",
  zat_a9_actor_losses_info_play_sound: "zat_a9_actor_losses_info_play_sound",
  zat_a9_actor_meeting_info_play_sound: "zat_a9_actor_meeting_info_play_sound",
  zat_a9_actor_power_info_play_sound: "zat_a9_actor_power_info_play_sound",
  zat_a9_actor_way_info_play_sound: "zat_a9_actor_way_info_play_sound",
  zat_b100_cameff_played: "zat_b100_cameff_played",
  zat_b100_heli_2_searched: "zat_b100_heli_2_searched",
  zat_b100_heli_2_searching: "zat_b100_heli_2_searching",
  zat_b100_poltergeist_dead_01: "zat_b100_poltergeist_dead_01",
  zat_b100_poltergeist_dead_02: "zat_b100_poltergeist_dead_02",
  zat_b100_poltergeist_spawned_01: "zat_b100_poltergeist_spawned_01",
  zat_b100_poltergeist_spawned_02: "zat_b100_poltergeist_spawned_02",
  zat_b100_sound_played: "zat_b100_sound_played",
  zat_b101_heli_5_searched: "zat_b101_heli_5_searched",
  zat_b101_heli_5_searching: "zat_b101_heli_5_searching",
  zat_b103_actor_take_toolkit: "zat_b103_actor_take_toolkit",
  zat_b103_actor_took_kardan_task: "zat_b103_actor_took_kardan_task",
  zat_b103_actor_warned_by_merc: "zat_b103_actor_warned_by_merc",
  zat_b103_merc_about_supplies_mentioned: "zat_b103_merc_about_supplies_mentioned",
  zat_b103_merc_ammo_got: "zat_b103_merc_ammo_got",
  zat_b103_merc_bring_supplies: "zat_b103_merc_bring_supplies",
  zat_b103_merc_fight: "zat_b103_merc_fight",
  zat_b103_merc_food_got: "zat_b103_merc_food_got",
  zat_b103_merc_medkit_got: "zat_b103_merc_medkit_got",
  zat_b103_merc_supplies_got: "zat_b103_merc_supplies_got",
  zat_b103_merc_task_done: "zat_b103_merc_task_done",
  zat_b103_merc_used_actor: "zat_b103_merc_used_actor",
  zat_b103_toolkit_known: "zat_b103_toolkit_known",
  zat_b104_task_end: "zat_b104_task_end",
  zat_b106_chimera_dead: "zat_b106_chimera_dead",
  zat_b106_found_soroka: "zat_b106_found_soroka",
  zat_b106_found_soroka_done: "zat_b106_found_soroka_done",
  zat_b106_one_hit: "zat_b106_one_hit",
  zat_b106_search_soroka: "zat_b106_search_soroka",
  zat_b106_stalker_gonta_b52_about_nimble_dialog_done: "zat_b106_stalker_gonta_b52_about_nimble_dialog_done",
  /**
   * Zaton b12.
   */
  zat_b12_documents_sold_1: "zat_b12_documents_sold_1",
  zat_b12_documents_sold_2: "zat_b12_documents_sold_2",
  zat_b12_documents_sold_3: "zat_b12_documents_sold_3",
  zat_b12_key_1_use: "zat_b12_key_1_use",
  zat_b12_key_2_use: "zat_b12_key_2_use",
  zat_b14_actor_enemy: "zat_b14_actor_enemy",
  zat_b14_actor_in_up_point_zone: "zat_b14_actor_in_up_point_zone",
  zat_b14_actor_know_about_svyaznoy: "zat_b14_actor_know_about_svyaznoy",
  zat_b14_bad_stalker_1_2_spawn: "zat_b14_bad_stalker_1_2_spawn",
  zat_b14_cut_scene_1_point_01: "zat_b14_cut_scene_1_point_01",
  zat_b14_cut_scene_1_point_02: "zat_b14_cut_scene_1_point_02",
  zat_b14_cut_scene_1_point_03: "zat_b14_cut_scene_1_point_03",
  zat_b14_cut_scene_1_start: "zat_b14_cut_scene_1_start",
  zat_b14_cut_scene_end: "zat_b14_cut_scene_end",
  zat_b14_cut_scene_linker_have_artefact: "zat_b14_cut_scene_linker_have_artefact",
  zat_b14_cut_scene_stalker_not_have_artefact: "zat_b14_cut_scene_stalker_not_have_artefact",
  zat_b14_cut_scene_stalker_transfer_artefact: "zat_b14_cut_scene_stalker_transfer_artefact",
  zat_b14_den_of_the_bloodsucker_find_keys_give: "zat_b14_den_of_the_bloodsucker_find_keys_give",
  zat_b14_den_of_the_bloodsucker_open_conteiner_give: "zat_b14_den_of_the_bloodsucker_open_conteiner_give",
  zat_b14_dialog_done: "zat_b14_dialog_done",
  zat_b14_dialog_last_chance_done: "zat_b14_dialog_last_chance_done",
  zat_b14_door_1_unlock: "zat_b14_door_1_unlock",
  zat_b14_general_stalker_spawn: "zat_b14_general_stalker_spawn",
  zat_b14_give_item_linker: "zat_b14_give_item_linker",
  zat_b14_give_item_stalker: "zat_b14_give_item_stalker",
  zat_b14_learn_about_strange_occurrence_by_stalkers_give_task:
    "zat_b14_learn_about_strange_occurrence_by_stalkers_give_task",
  zat_b14_learn_about_strange_occurrence_give_task: "zat_b14_learn_about_strange_occurrence_give_task",
  zat_b14_not_give_item_linker: "zat_b14_not_give_item_linker",
  zat_b14_not_give_item_stalker: "zat_b14_not_give_item_stalker",
  zat_b14_recon_place: "zat_b14_recon_place",
  zat_b14_robbery_give_artefact: "zat_b14_robbery_give_artefact",
  zat_b14_robbery_not_give_artefact: "zat_b14_robbery_not_give_artefact",
  zat_b14_robbery_nowpn_actor: "zat_b14_robbery_nowpn_actor",
  zat_b14_robbery_punch_play_sound: "zat_b14_robbery_punch_play_sound",
  zat_b14_smart_terrain_open: "zat_b14_smart_terrain_open",
  zat_b14_spawn_friends_stalker: "zat_b14_spawn_friends_stalker",
  zat_b14_stalker_at_bar_start_done: "zat_b14_stalker_at_bar_start_done",
  zat_b14_stalker_change_smart: "zat_b14_stalker_change_smart",
  zat_b14_stalker_cut_scene_ready: "zat_b14_stalker_cut_scene_ready",
  zat_b14_stalker_robbery: "zat_b14_stalker_robbery",
  zat_b14_stalker_robbery_cutscene_end: "zat_b14_stalker_robbery_cutscene_end",
  zat_b14_stalker_robbery_cutscene_start: "zat_b14_stalker_robbery_cutscene_start",
  zat_b14_stalker_work_end: "zat_b14_stalker_work_end",
  zat_b14_stalkers_bandits_free: "zat_b14_stalkers_bandits_free",
  zat_b14_strange_item: "zat_b14_strange_item",
  zat_b14_take_item: "zat_b14_take_item",
  zat_b14_ui_disable: "zat_b14_ui_disable",
  zat_b14_ui_enable: "zat_b14_ui_enable",
  zat_b18_noah_about_catastrophe_told: "zat_b18_noah_about_catastrophe_told",
  zat_b18_noah_about_dog_told: "zat_b18_noah_about_dog_told",
  zat_b18_noah_breakdown: "zat_b18_noah_breakdown",
  zat_b18_noah_dead: "zat_b18_noah_dead",
  zat_b18_noah_gave_first_artefact: "zat_b18_noah_gave_first_artefact",
  zat_b18_noah_gave_second_artefact: "zat_b18_noah_gave_second_artefact",
  zat_b18_noah_go_away: "zat_b18_noah_go_away",
  zat_b18_noah_met: "zat_b18_noah_met",
  zat_b18_noah_remembers: "zat_b18_noah_remembers",
  zat_b18_noah_shot_door: "zat_b18_noah_shot_door",
  zat_b18_noah_told_about_arc: "zat_b18_noah_told_about_arc",
  zat_b18_reset_memory: "zat_b18_reset_memory",
  zat_b215_gave_maps: "zat_b215_gave_maps",
  zat_b22_actor_gone: "zat_b22_actor_gone",
  zat_b22_actor_in: "zat_b22_actor_in",
  zat_b22_barmen_gave_reward: "zat_b22_barmen_gave_reward",
  zat_b22_deal_with_medic_vampire_completed: "zat_b22_deal_with_medic_vampire_completed",
  zat_b22_deal_with_medic_vampire_reversed: "zat_b22_deal_with_medic_vampire_reversed",
  zat_b22_medic_dialog_info_1: "zat_b22_medic_dialog_info_1",
  zat_b22_medic_dialog_info_2: "zat_b22_medic_dialog_info_2",
  zat_b22_medic_dialog_info_3: "zat_b22_medic_dialog_info_3",
  zat_b22_medic_pda: "zat_b22_medic_pda",
  zat_b22_questline_reversed: "zat_b22_questline_reversed",
  zat_b22_stalker_cop_place: "zat_b22_stalker_cop_place",
  zat_b22_stalker_medic_b52_about_nimble_dialog_done: "zat_b22_stalker_medic_b52_about_nimble_dialog_done",
  zat_b22_stalker_medic_body_searched: "zat_b22_stalker_medic_body_searched",
  zat_b22_stalker_medic_wounded_heavy: "zat_b22_stalker_medic_wounded_heavy",
  zat_b22_stalker_vampire: "zat_b22_stalker_vampire",
  zat_b22_stalker_vampire_story: "zat_b22_stalker_vampire_story",
  zat_b28_heli_3_searched: "zat_b28_heli_3_searched",
  zat_b28_heli_3_searching: "zat_b28_heli_3_searching",
  zat_b29_adv_task_given: "zat_b29_adv_task_given",
  zat_b29_adv_task_timeout: "zat_b29_adv_task_timeout",
  zat_b29_af_16: "zat_b29_af_16",
  zat_b29_af_17: "zat_b29_af_17",
  zat_b29_af_18: "zat_b29_af_18",
  zat_b29_af_19: "zat_b29_af_19",
  zat_b29_af_20: "zat_b29_af_20",
  zat_b29_af_21: "zat_b29_af_21",
  zat_b29_af_22: "zat_b29_af_22",
  zat_b29_af_23: "zat_b29_af_23",
  zat_b29_bring_af_17: "zat_b29_bring_af_17",
  zat_b29_bring_af_18: "zat_b29_bring_af_18",
  zat_b29_bring_af_19: "zat_b29_bring_af_19",
  zat_b29_bring_af_20: "zat_b29_bring_af_20",
  zat_b29_bring_af_21: "zat_b29_bring_af_21",
  zat_b29_bring_af_22: "zat_b29_bring_af_22",
  zat_b29_bring_af_23: "zat_b29_bring_af_23",
  zat_b29_exclusive_conditions: "zat_b29_exclusive_conditions",
  zat_b29_first_rival_taken_out: "zat_b29_first_rival_taken_out",
  zat_b29_linker_fears_actor: "zat_b29_linker_fears_actor",
  zat_b29_linker_info: "zat_b29_linker_info",
  zat_b29_linker_take_af_from_rival: "zat_b29_linker_take_af_from_rival",
  zat_b29_quest_af_given: "zat_b29_quest_af_given",
  zat_b29_redice: "zat_b29_redice",
  zat_b29_respawn: "zat_b29_respawn",
  zat_b29_rival_1_1: "zat_b29_rival_1_1",
  zat_b29_rival_1_2: "zat_b29_rival_1_2",
  zat_b29_rival_1_3: "zat_b29_rival_1_3",
  zat_b29_rival_1_4: "zat_b29_rival_1_4",
  zat_b29_rival_1_5: "zat_b29_rival_1_5",
  zat_b29_rival_1_base: "zat_b29_rival_1_base",
  zat_b29_rival_2_1: "zat_b29_rival_2_1",
  zat_b29_rival_2_2: "zat_b29_rival_2_2",
  zat_b29_rival_2_3: "zat_b29_rival_2_3",
  zat_b29_rival_2_4: "zat_b29_rival_2_4",
  zat_b29_rival_2_5: "zat_b29_rival_2_5",
  zat_b29_rival_2_base: "zat_b29_rival_2_base",
  zat_b29_rival_sound_played: "zat_b29_rival_sound_played",
  zat_b29_rivals_search: "zat_b29_rivals_search",
  zat_b29_second_rival_taken_out: "zat_b29_second_rival_taken_out",
  zat_b29_stalker_rival_1_found_af: "zat_b29_stalker_rival_1_found_af",
  zat_b29_stalker_rival_2_found_af: "zat_b29_stalker_rival_2_found_af",
  zat_b29_stalkers_rivals_found_af: "zat_b29_stalkers_rivals_found_af",
  zat_b29_task_fail: "zat_b29_task_fail",
  zat_b29_task_start: "zat_b29_task_start",
  /**
   * Zaton b30.
   */
  zat_b30_about_compass_told: "zat_b30_about_compass_told",
  zat_b30_actor_against_barmen: "zat_b30_actor_against_barmen",
  zat_b30_actor_against_owl: "zat_b30_actor_against_owl",
  zat_b30_actor_gave_detector: "zat_b30_actor_gave_detector",
  zat_b30_actor_in_tempting_business: "zat_b30_actor_in_tempting_business",
  zat_b30_actor_with_af: "zat_b30_actor_with_af",
  zat_b30_actor_with_sultan: "zat_b30_actor_with_sultan",
  zat_b30_barmen_going_under_sultan: "zat_b30_barmen_going_under_sultan",
  zat_b30_barmen_got_af: "zat_b30_barmen_got_af",
  zat_b30_barmen_under_sultan: "zat_b30_barmen_under_sultan",
  zat_b30_barmen_under_sultan_told: "zat_b30_barmen_under_sultan_told",
  zat_b30_compass_task_start: "zat_b30_compass_task_start",
  zat_b30_compass_to_barmen: "zat_b30_compass_to_barmen",
  zat_b30_compass_to_barmen_reversed: "zat_b30_compass_to_barmen_reversed",
  zat_b30_compass_to_sultan: "zat_b30_compass_to_sultan",
  zat_b30_compass_to_sultan_reversed: "zat_b30_compass_to_sultan_reversed",
  zat_b30_first_detector: "zat_b30_first_detector",
  zat_b30_jup_b6_scientist_tech_about_owl: "zat_b30_jup_b6_scientist_tech_about_owl",
  zat_b30_need_artefact_from_noah: "zat_b30_need_artefact_from_noah",
  zat_b30_owl_detectors_approached: "zat_b30_owl_detectors_approached",
  zat_b30_owl_in_trouble: "zat_b30_owl_in_trouble",
  zat_b30_owl_in_trouble_dialog_done: "zat_b30_owl_in_trouble_dialog_done",
  zat_b30_owl_quest_done: "zat_b30_owl_quest_done",
  zat_b30_owl_scat_1: "zat_b30_owl_scat_1",
  zat_b30_owl_scat_2: "zat_b30_owl_scat_2",
  zat_b30_owl_scat_3: "zat_b30_owl_scat_3",
  zat_b30_owl_stalker_about_halfart_jup_b6_asked: "zat_b30_owl_stalker_about_halfart_jup_b6_asked",
  zat_b30_owl_stalker_about_halfart_zat_b14_asked: "zat_b30_owl_stalker_about_halfart_zat_b14_asked",
  zat_b30_owl_stalker_trader_about_osis_art: "zat_b30_owl_stalker_trader_about_osis_art",
  zat_b30_owl_stalker_trader_more_documets_done: "zat_b30_owl_stalker_trader_more_documets_done",
  zat_b30_owl_to_sultan: "zat_b30_owl_to_sultan",
  zat_b30_rival_1_wo_detector: "zat_b30_rival_1_wo_detector",
  zat_b30_rival_2_wo_detector: "zat_b30_rival_2_wo_detector",
  zat_b30_second_detector: "zat_b30_second_detector",
  zat_b30_sultan_got_af: "zat_b30_sultan_got_af",
  zat_b30_sultan_know_about_detectors: "zat_b30_sultan_know_about_detectors",
  zat_b30_sultan_loose: "zat_b30_sultan_loose",
  zat_b30_sultan_refuses_af: "zat_b30_sultan_refuses_af",
  zat_b30_task_percents_running: "zat_b30_task_percents_running",
  zat_b30_task_start: "zat_b30_task_start",
  /**
   * Zaton b33.
   */
  zat_b33_actor_is_down: "zat_b33_actor_is_down",
  zat_b33_fifth_item: "zat_b33_fifth_item",
  zat_b33_fifth_item_gived: "zat_b33_fifth_item_gived",
  zat_b33_find_package: "zat_b33_find_package",
  zat_b33_first_item: "zat_b33_first_item",
  zat_b33_first_item_gived: "zat_b33_first_item_gived",
  zat_b33_fourth_item: "zat_b33_fourth_item",
  zat_b33_fourth_item_gived: "zat_b33_fourth_item_gived",
  zat_b33_package_returned: "zat_b33_package_returned",
  zat_b33_refuse_task: "zat_b33_refuse_task",
  zat_b33_safe_container: "zat_b33_safe_container",
  zat_b33_second_item: "zat_b33_second_item",
  zat_b33_second_item_gived: "zat_b33_second_item_gived",
  zat_b33_share_start: "zat_b33_share_start",
  zat_b33_snork_jump_05: "zat_b33_snork_jump_05",
  zat_b33_stalker_snag_b52_my_gun_dialog_done: "zat_b33_stalker_snag_b52_my_gun_dialog_done",
  zat_b33_task_gived: "zat_b33_task_gived",
  zat_b33_third_item: "zat_b33_third_item",
  zat_b33_third_item_gived: "zat_b33_third_item_gived",
  /**
   * Zaton b38 - bloodsuckers lair, disappearing stalkers.
   */
  zat_b38_actor_know_about_lair: "zat_b38_actor_know_about_lair",
  zat_b38_bloodscuker_1_death: "zat_b38_bloodscuker_1_death",
  zat_b38_bloodscuker_1_hit: "zat_b38_bloodscuker_1_hit",
  zat_b38_bloodscuker_2_death: "zat_b38_bloodscuker_2_death",
  zat_b38_bloodscuker_2_hit: "zat_b38_bloodscuker_2_hit",
  zat_b38_bloodscukers_sleepers_stand_up: "zat_b38_bloodscukers_sleepers_stand_up",
  zat_b38_bloodsucker_1_angry: "zat_b38_bloodsucker_1_angry",
  zat_b38_bloodsucker_1_set_state: "zat_b38_bloodsucker_1_set_state",
  zat_b38_bloodsucker_2_angry: "zat_b38_bloodsucker_2_angry",
  zat_b38_bloodsucker_2_set_state: "zat_b38_bloodsucker_2_set_state",
  zat_b38_bloodsucker_fear_1_play: "zat_b38_bloodsucker_fear_1_play",
  zat_b38_cop_about_lair_dialog_done: "zat_b38_cop_about_lair_dialog_done",
  zat_b38_cop_dead: "zat_b38_cop_dead",
  zat_b38_cop_hit_from_actor: "zat_b38_cop_hit_from_actor",
  zat_b38_cop_spawn_again: "zat_b38_cop_spawn_again",
  zat_b38_cop_spawn_again2: "zat_b38_cop_spawn_again2",
  zat_b38_den_of_the_bloodsucker_complete: "zat_b38_den_of_the_bloodsucker_complete",
  zat_b38_den_of_the_bloodsucker_inform_stalkers_give: "zat_b38_den_of_the_bloodsucker_inform_stalkers_give",
  zat_b38_den_of_the_bloodsucker_inform_stalkers_give_task: "zat_b38_den_of_the_bloodsucker_inform_stalkers_give_task",
  zat_b38_den_of_the_bloodsucker_tell_barman_about_all_give:
    "zat_b38_den_of_the_bloodsucker_tell_barman_about_all_give",
  zat_b38_disappearance_stalkers_check_basement_give: "zat_b38_disappearance_stalkers_check_basement_give",
  zat_b38_disappearance_stalkers_clean_den_of_the_bloodsucker_give:
    "zat_b38_disappearance_stalkers_clean_den_of_the_bloodsucker_give",
  zat_b38_disappearance_stalkers_complete: "zat_b38_disappearance_stalkers_complete",
  zat_b38_disappearance_stalkers_deal_with_medic_give: "zat_b38_disappearance_stalkers_deal_with_medic_give",
  zat_b38_disappearance_stalkers_fail: "zat_b38_disappearance_stalkers_fail",
  zat_b38_disappearance_stalkers_find_cop_near_port_krans_give:
    "zat_b38_disappearance_stalkers_find_cop_near_port_krans_give",
  zat_b38_disappearance_stalkers_find_out_where_is_cop_give:
    "zat_b38_disappearance_stalkers_find_out_where_is_cop_give",
  zat_b38_disappearance_stalkers_find_to_be_missing_hunter_give:
    "zat_b38_disappearance_stalkers_find_to_be_missing_hunter_give",
  zat_b38_disappearance_stalkers_find_to_be_missing_hunter_give_task:
    "zat_b38_disappearance_stalkers_find_to_be_missing_hunter_give_task",
  zat_b38_disappearance_stalkers_get_out_from_den_of_the_bloodsucker_give:
    "zat_b38_disappearance_stalkers_get_out_from_den_of_the_bloodsucker_give",
  zat_b38_disappearance_stalkers_jump_down_give: "zat_b38_disappearance_stalkers_jump_down_give",
  zat_b38_disappearance_stalkers_meet_cop_24h_past_give: "zat_b38_disappearance_stalkers_meet_cop_24h_past_give",
  zat_b38_disappearance_stalkers_meet_cop_later_give: "zat_b38_disappearance_stalkers_meet_cop_later_give",
  zat_b38_disappearance_stalkers_meet_cop_next_day_give: "zat_b38_disappearance_stalkers_meet_cop_next_day_give",
  zat_b38_disappearance_stalkers_meet_ment_give: "zat_b38_disappearance_stalkers_meet_ment_give",
  zat_b38_disappearance_stalkers_reversed: "zat_b38_disappearance_stalkers_reversed",
  zat_b38_disappearance_stalkers_tell_barmen_about_medic_give:
    "zat_b38_disappearance_stalkers_tell_barmen_about_medic_give",
  zat_b38_jump_tonnel_info: "zat_b38_jump_tonnel_info",
  zat_b38_lift_open: "zat_b38_lift_open",
  zat_b38_lock_sound_play: "zat_b38_lock_sound_play",
  zat_b38_lock_sound_stop: "zat_b38_lock_sound_stop",
  zat_b38_open_info: "zat_b38_open_info",
  zat_b38_show_spot_dead_body: "zat_b38_show_spot_dead_body",
  zat_b38_spawn_all: "zat_b38_spawn_all",
  zat_b38_spawn_npc_cop_again: "zat_b38_spawn_npc_cop_again",
  zat_b38_spawn_npc_cop_again2: "zat_b38_spawn_npc_cop_again2",
  zat_b38_stalker_cop_b52_about_nimble: "zat_b38_stalker_cop_b52_about_nimble",
  zat_b38_stalker_cop_cave_end: "zat_b38_stalker_cop_cave_end",
  zat_b38_stalker_cop_come_here_2_play: "zat_b38_stalker_cop_come_here_2_play",
  zat_b38_stalker_cop_death: "zat_b38_stalker_cop_death",
  zat_b38_stalker_cop_destroy: "zat_b38_stalker_cop_destroy",
  zat_b38_stalker_cop_destroy2: "zat_b38_stalker_cop_destroy2",
  zat_b38_stalker_cop_fear_1: "zat_b38_stalker_cop_fear_1",
  zat_b38_stalker_cop_fear_2: "zat_b38_stalker_cop_fear_2",
  zat_b38_stalker_cop_find_lair_pda_play: "zat_b38_stalker_cop_find_lair_pda_play",
  zat_b38_stalker_cop_task_dialog_done: "zat_b38_stalker_cop_task_dialog_done",
  zat_b38_stalker_medic_bloodsucker_dialog_done: "zat_b38_stalker_medic_bloodsucker_dialog_done",
  zat_b38_stalker_medic_setup: "zat_b38_stalker_medic_setup",
  zat_b38_stalkers_den_of_the_bloodsucker_universal_dialog_done:
    "zat_b38_stalkers_den_of_the_bloodsucker_universal_dialog_done",
  zat_b38_switch_info: "zat_b38_switch_info",
  zat_b38_underground_door_open: "zat_b38_underground_door_open",
  /**
   * Zaton b3 - tech quests.
   */
  zat_b3_all_instruments_brought: "zat_b3_all_instruments_brought",
  zat_b3_gauss_repaired: "zat_b3_gauss_repaired",
  zat_b3_stalker_mechanic_b52_about_nimble_dialog_done: "zat_b3_stalker_mechanic_b52_about_nimble_dialog_done",
  zat_b3_task_end: "zat_b3_task_end",
  zat_b3_tech_discount_1: "zat_b3_tech_discount_1",
  zat_b3_tech_drink_no_more: "zat_b3_tech_drink_no_more",
  zat_b3_tech_drinked_out: "zat_b3_tech_drinked_out",
  zat_b3_tech_have_couple_dose: "zat_b3_tech_have_couple_dose",
  zat_b3_tech_have_one_dose: "zat_b3_tech_have_one_dose",
  zat_b3_tech_instrument_1_brought: "zat_b3_tech_instrument_1_brought",
  zat_b3_tech_instrument_2_brought: "zat_b3_tech_instrument_2_brought",
  zat_b3_tech_instrument_3_brought: "zat_b3_tech_instrument_3_brought",
  zat_b3_tech_see_produce_62: "zat_b3_tech_see_produce_62",
  zat_b3_tech_surprise_anim_end: "zat_b3_tech_surprise_anim_end",
  zat_b3_tech_waked_up: "zat_b3_tech_waked_up",
  /**
   * Zaton b40.
   */
  zat_b40_all_item_saled: "zat_b40_all_item_saled",
  zat_b40_notebook_saled: "zat_b40_notebook_saled",
  zat_b40_pda_1_saled: "zat_b40_pda_1_saled",
  zat_b40_pda_2_saled: "zat_b40_pda_2_saled",
  /**
   * Zaton b44.
   */
  zat_b44_tech_buddies_both_told: "zat_b44_tech_buddies_both_told",
  /**
   * Zaton b51.
   */
  zat_b51_done_item_1_1: "zat_b51_done_item_1_1",
  zat_b51_done_item_1_2: "zat_b51_done_item_1_2",
  zat_b51_done_item_1_3: "zat_b51_done_item_1_3",
  zat_b51_done_item_2_1: "zat_b51_done_item_2_1",
  zat_b51_done_item_2_2: "zat_b51_done_item_2_2",
  zat_b51_done_item_2_3: "zat_b51_done_item_2_3",
  zat_b51_done_item_3_1: "zat_b51_done_item_3_1",
  zat_b51_done_item_3_2: "zat_b51_done_item_3_2",
  zat_b51_done_item_3_3: "zat_b51_done_item_3_3",
  zat_b51_done_item_4_1: "zat_b51_done_item_4_1",
  zat_b51_done_item_4_2: "zat_b51_done_item_4_2",
  zat_b51_done_item_4_3: "zat_b51_done_item_4_3",
  zat_b51_done_item_5_1: "zat_b51_done_item_5_1",
  zat_b51_done_item_6_1: "zat_b51_done_item_6_1",
  zat_b51_done_item_7_1: "zat_b51_done_item_7_1",
  zat_b51_finished_categories_all: "zat_b51_finished_categories_all",
  zat_b51_finished_category_1: "zat_b51_finished_category_1",
  zat_b51_finished_category_2: "zat_b51_finished_category_2",
  zat_b51_finished_category_3: "zat_b51_finished_category_3",
  zat_b51_finished_category_4: "zat_b51_finished_category_4",
  zat_b51_finished_category_5: "zat_b51_finished_category_5",
  zat_b51_finished_category_6: "zat_b51_finished_category_6",
  zat_b51_finished_category_7: "zat_b51_finished_category_7",
  zat_b51_finishing_category_1: "zat_b51_finishing_category_1",
  zat_b51_finishing_category_2: "zat_b51_finishing_category_2",
  zat_b51_finishing_category_3: "zat_b51_finishing_category_3",
  zat_b51_finishing_category_4: "zat_b51_finishing_category_4",
  zat_b51_finishing_category_5: "zat_b51_finishing_category_5",
  zat_b51_finishing_category_6: "zat_b51_finishing_category_6",
  zat_b51_finishing_category_7: "zat_b51_finishing_category_7",
  zat_b51_nimble_can_go: "zat_b51_nimble_can_go",
  zat_b51_nimble_intro: "zat_b51_nimble_intro",
  zat_b51_order_in_process: "zat_b51_order_in_process",
  zat_b51_order_ready: "zat_b51_order_ready",
  zat_b51_order_refused: "zat_b51_order_refused",
  zat_b51_order_unavailable: "zat_b51_order_unavailable",
  zat_b51_ordered_item_1_1: "zat_b51_ordered_item_1_1",
  zat_b51_ordered_item_1_2: "zat_b51_ordered_item_1_2",
  zat_b51_ordered_item_1_3: "zat_b51_ordered_item_1_3",
  zat_b51_ordered_item_2_1: "zat_b51_ordered_item_2_1",
  zat_b51_ordered_item_2_2: "zat_b51_ordered_item_2_2",
  zat_b51_ordered_item_2_3: "zat_b51_ordered_item_2_3",
  zat_b51_ordered_item_3_1: "zat_b51_ordered_item_3_1",
  zat_b51_ordered_item_3_2: "zat_b51_ordered_item_3_2",
  zat_b51_ordered_item_3_3: "zat_b51_ordered_item_3_3",
  zat_b51_ordered_item_4_1: "zat_b51_ordered_item_4_1",
  zat_b51_ordered_item_4_2: "zat_b51_ordered_item_4_2",
  zat_b51_ordered_item_4_3: "zat_b51_ordered_item_4_3",
  zat_b51_ordered_item_5_1: "zat_b51_ordered_item_5_1",
  zat_b51_ordered_item_6_1: "zat_b51_ordered_item_6_1",
  zat_b51_ordered_item_7_1: "zat_b51_ordered_item_7_1",
  zat_b51_processing_category_1: "zat_b51_processing_category_1",
  zat_b51_processing_category_2: "zat_b51_processing_category_2",
  zat_b51_processing_category_3: "zat_b51_processing_category_3",
  zat_b51_processing_category_4: "zat_b51_processing_category_4",
  zat_b51_processing_category_5: "zat_b51_processing_category_5",
  zat_b51_processing_category_6: "zat_b51_processing_category_6",
  zat_b51_processing_category_7: "zat_b51_processing_category_7",
  zat_b51_stalker_nimble_b52_about_gun_questions_dialog_done:
    "zat_b51_stalker_nimble_b52_about_gun_questions_dialog_done",
  zat_b51_stalker_snag_b52_about_gun_questions_dialog_done: "zat_b51_stalker_snag_b52_about_gun_questions_dialog_done",
  zat_b51_told_about_item_1_1: "zat_b51_told_about_item_1_1",
  zat_b51_told_about_item_1_2: "zat_b51_told_about_item_1_2",
  zat_b51_told_about_item_1_3: "zat_b51_told_about_item_1_3",
  zat_b51_told_about_item_2_1: "zat_b51_told_about_item_2_1",
  zat_b51_told_about_item_2_2: "zat_b51_told_about_item_2_2",
  zat_b51_told_about_item_2_3: "zat_b51_told_about_item_2_3",
  zat_b51_told_about_item_3_1: "zat_b51_told_about_item_3_1",
  zat_b51_told_about_item_3_2: "zat_b51_told_about_item_3_2",
  zat_b51_told_about_item_3_3: "zat_b51_told_about_item_3_3",
  zat_b51_told_about_item_4_1: "zat_b51_told_about_item_4_1",
  zat_b51_told_about_item_4_2: "zat_b51_told_about_item_4_2",
  zat_b51_told_about_item_4_3: "zat_b51_told_about_item_4_3",
  zat_b51_told_about_item_5_1: "zat_b51_told_about_item_5_1",
  zat_b51_told_about_item_6_1: "zat_b51_told_about_item_6_1",
  zat_b51_told_about_item_7_1: "zat_b51_told_about_item_7_1",
  zat_b52_actor_go_offline: "zat_b52_actor_go_offline",
  zat_b52_actor_has_port_bandits_pda: "zat_b52_actor_has_port_bandits_pda",
  zat_b52_barman_know_there_snag: "zat_b52_barman_know_there_snag",
  zat_b52_item_1_a_taken: "zat_b52_item_1_a_taken",
  zat_b52_item_1_b_taken: "zat_b52_item_1_b_taken",
  zat_b52_item_1_c_taken: "zat_b52_item_1_c_taken",
  zat_b52_item_2_a_taken: "zat_b52_item_2_a_taken",
  zat_b52_item_2_b_taken: "zat_b52_item_2_b_taken",
  zat_b52_item_2_c_taken: "zat_b52_item_2_c_taken",
  zat_b52_item_3_a_taken: "zat_b52_item_3_a_taken",
  zat_b52_item_3_b_taken: "zat_b52_item_3_b_taken",
  zat_b52_item_3_c_taken: "zat_b52_item_3_c_taken",
  zat_b52_item_4_a_taken: "zat_b52_item_4_a_taken",
  zat_b52_item_4_b_taken: "zat_b52_item_4_b_taken",
  zat_b52_item_4_c_taken: "zat_b52_item_4_c_taken",
  zat_b52_item_no_taken: "zat_b52_item_no_taken",
  zat_b52_item_taken: "zat_b52_item_taken",
  zat_b52_meet_port_bandits: "zat_b52_meet_port_bandits",
  zat_b52_nimble_clear: "zat_b52_nimble_clear",
  zat_b52_port_bandits_spawn: "zat_b52_port_bandits_spawn",
  zat_b52_reputation_give: "zat_b52_reputation_give",
  zat_b52_reputation_task_open: "zat_b52_reputation_task_open",
  zat_b52_robbery_done: "zat_b52_robbery_done",
  zat_b52_robbery_no: "zat_b52_robbery_no",
  zat_b52_robbery_start: "zat_b52_robbery_start",
  zat_b52_robbery_yes: "zat_b52_robbery_yes",
  zat_b52_snag_jupiter: "zat_b52_snag_jupiter",
  zat_b52_snag_know_weapon: "zat_b52_snag_know_weapon",
  zat_b52_snag_no_place: "zat_b52_snag_no_place",
  zat_b52_snag_no_port_cranes: "zat_b52_snag_no_port_cranes",
  zat_b52_snag_port_bandits: "zat_b52_snag_port_bandits",
  zat_b52_snag_port_cranes: "zat_b52_snag_port_cranes",
  zat_b52_sultan_know_there_snag: "zat_b52_sultan_know_there_snag",
  zat_b57_balon_use: "zat_b57_balon_use",
  zat_b57_barmen_about_bloodsucker_lair_dialog_done: "zat_b57_barmen_about_bloodsucker_lair_dialog_done",
  zat_b57_bloodsucker_lair_clear: "zat_b57_bloodsucker_lair_clear",
  zat_b57_bloodsucker_spawn: "zat_b57_bloodsucker_spawn",
  zat_b57_den_of_the_bloodsucker_destroy_lair_give: "zat_b57_den_of_the_bloodsucker_destroy_lair_give",
  zat_b57_den_of_the_bloodsucker_place_gas_give: "zat_b57_den_of_the_bloodsucker_place_gas_give",
  zat_b57_den_of_the_bloodsucker_search_gas_give: "zat_b57_den_of_the_bloodsucker_search_gas_give",
  zat_b57_den_of_the_bloodsucker_spawn_gas: "zat_b57_den_of_the_bloodsucker_spawn_gas",
  zat_b57_den_of_the_bloodsucker_talk_shystriy: "zat_b57_den_of_the_bloodsucker_talk_shystriy",
  zat_b57_den_of_the_bloodsucker_tell_stalkers_about_destroy_lair_give:
    "zat_b57_den_of_the_bloodsucker_tell_stalkers_about_destroy_lair_give",
  zat_b57_den_of_the_bloodsucker_twist_vintil_give: "zat_b57_den_of_the_bloodsucker_twist_vintil_give",
  zat_b57_gas_running_play: "zat_b57_gas_running_play",
  zat_b57_gas_running_stop: "zat_b57_gas_running_stop",
  zat_b57_generic_dialog_done: "zat_b57_generic_dialog_done",
  zat_b57_nimble_reward_dialog_done: "zat_b57_nimble_reward_dialog_done",
  zat_b57_nimble_talk_about_gas: "zat_b57_nimble_talk_about_gas",
  zat_b57_roar_play: "zat_b57_roar_play",
  zat_b57_set_bloodsucker_attacker_1_state: "zat_b57_set_bloodsucker_attacker_1_state",
  zat_b57_set_bloodsucker_attacker_2_state: "zat_b57_set_bloodsucker_attacker_2_state",
  zat_b57_set_bloodsucker_attacker_3_state: "zat_b57_set_bloodsucker_attacker_3_state",
  zat_b57_set_bloodsucker_state: "zat_b57_set_bloodsucker_state",
  /**
   * Zaton b5.
   */
  zat_b5_actor_bandit_go_to_trader: "zat_b5_actor_bandit_go_to_trader",
  zat_b5_actor_go_to_trader: "zat_b5_actor_go_to_trader",
  zat_b5_actor_help_bandits: "zat_b5_actor_help_bandits",
  zat_b5_actor_help_dealer: "zat_b5_actor_help_dealer",
  zat_b5_actor_help_stalkers: "zat_b5_actor_help_stalkers",
  zat_b5_actor_speak_barmen: "zat_b5_actor_speak_barmen",
  zat_b5_actor_speak_linker: "zat_b5_actor_speak_linker",
  zat_b5_actor_stalker_go_to_trader: "zat_b5_actor_stalker_go_to_trader",
  zat_b5_actor_together_dealer: "zat_b5_actor_together_dealer",
  zat_b5_actor_with_bandits: "zat_b5_actor_with_bandits",
  zat_b5_actor_with_dealer: "zat_b5_actor_with_dealer",
  zat_b5_actor_with_stalkers: "zat_b5_actor_with_stalkers",
  zat_b5_bandit_hit: "zat_b5_bandit_hit",
  zat_b5_bandit_in_fight: "zat_b5_bandit_in_fight",
  zat_b5_bandit_speak_1_done: "zat_b5_bandit_speak_1_done",
  zat_b5_bandits_death: "zat_b5_bandits_death",
  zat_b5_come_to_bandits_complete: "zat_b5_come_to_bandits_complete",
  zat_b5_come_to_bandits_done: "zat_b5_come_to_bandits_done",
  zat_b5_come_to_dealer_done: "zat_b5_come_to_dealer_done",
  zat_b5_come_to_stalkers: "zat_b5_come_to_stalkers",
  zat_b5_cover_dealer_done: "zat_b5_cover_dealer_done",
  zat_b5_dealer_easy_revard: "zat_b5_dealer_easy_revard",
  zat_b5_dealer_full_revard: "zat_b5_dealer_full_revard",
  zat_b5_dealer_speak_1_done: "zat_b5_dealer_speak_1_done",
  zat_b5_dealer_speak_2_done: "zat_b5_dealer_speak_2_done",
  zat_b5_meat: "zat_b5_meat",
  zat_b5_meat_online: "zat_b5_meat_online",
  zat_b5_protect_dealer_done: "zat_b5_protect_dealer_done",
  zat_b5_spawn_enemy: "zat_b5_spawn_enemy",
  zat_b5_speak_dealer_done: "zat_b5_speak_dealer_done",
  zat_b5_stalker_attack_dealer: "zat_b5_stalker_attack_dealer",
  zat_b5_stalker_death: "zat_b5_stalker_death",
  zat_b5_stalker_hit: "zat_b5_stalker_hit",
  zat_b5_stalker_leader_end: "zat_b5_stalker_leader_end",
  zat_b5_stalkers_death: "zat_b5_stalkers_death",
  zat_b5_start: "zat_b5_start",
  zat_b5_start_quest_stalkers: "zat_b5_start_quest_stalkers",
  zat_b5_sultan_close_by_trader: "zat_b5_sultan_close_by_trader",
  zat_b5_sultan_dead: "zat_b5_sultan_dead",
  zat_b5_sultan_speak_for_stalkers: "zat_b5_sultan_speak_for_stalkers",
  zat_b5_trader_death: "zat_b5_trader_death",
  zat_b5_trader_death_info: "zat_b5_trader_death_info",
  /**
   * Zaton b7.
   */
  zat_b7_actor_help_bandits: "zat_b7_actor_help_bandits",
  zat_b7_actor_help_stalkers: "zat_b7_actor_help_stalkers",
  zat_b7_actor_killed_victims_self: "zat_b7_actor_killed_victims_self",
  zat_b7_actor_now_duty_illicit_dealer: "zat_b7_actor_now_duty_illicit_dealer",
  zat_b7_actor_really_helped_bandits: "zat_b7_actor_really_helped_bandits",
  zat_b7_actor_really_helped_stalkers: "zat_b7_actor_really_helped_stalkers",
  zat_b7_actor_refused_to_be_robbed: "zat_b7_actor_refused_to_be_robbed",
  zat_b7_actor_robbed: "zat_b7_actor_robbed",
  zat_b7_actor_teleport: "zat_b7_actor_teleport",
  zat_b7_actor_with_bandits: "zat_b7_actor_with_bandits",
  zat_b7_actor_with_stalkers: "zat_b7_actor_with_stalkers",
  zat_b7_attack_started: "zat_b7_attack_started",
  zat_b7_bandit_boss_sultan_b52_about_nimble_dialog_done: "zat_b7_bandit_boss_sultan_b52_about_nimble_dialog_done",
  zat_b7_bandit_boss_sultan_b52_about_snag: "zat_b7_bandit_boss_sultan_b52_about_snag",
  zat_b7_bandit_boss_sultan_b7_give_task_dialog_told: "zat_b7_bandit_boss_sultan_b7_give_task_dialog_told",
  zat_b7_raider_plan: "zat_b7_raider_plan",
  zat_b7_sound_play: "zat_b7_sound_play",
  zat_b7_stalker_raider_leader_alive: "zat_b7_stalker_raider_leader_alive",
  zat_b7_stalker_raider_leader_on_position: "zat_b7_stalker_raider_leader_on_position",
  zat_b7_stalker_victim_leader_alive: "zat_b7_stalker_victim_leader_alive",
  zat_b7_stalkers_raiders_attack: "zat_b7_stalkers_raiders_attack",
  zat_b7_stalkers_raiders_attack_started: "zat_b7_stalkers_raiders_attack_started",
  zat_b7_stalkers_raiders_meet: "zat_b7_stalkers_raiders_meet",
  zat_b7_stalkers_raiders_reward_given: "zat_b7_stalkers_raiders_reward_given",
  zat_b7_stalkers_victims_know_about_raid: "zat_b7_stalkers_victims_know_about_raid",
  zat_b7_stalkers_victims_prepare: "zat_b7_stalkers_victims_prepare",
  zat_b7_stalkers_victims_reward_given: "zat_b7_stalkers_victims_reward_given",
  zat_b7_stalkers_victims_task_given: "zat_b7_stalkers_victims_task_given",
  zat_b7_task_end: "zat_b7_task_end",
  zat_b7_victims_disappeared: "zat_b7_victims_disappeared",
} as const;
