export enum EAchievement {
  PIONEER = "pioneer",
  MUTANT_HUNTER = "mutant_hunter",
  DETECTIVE = "detective",
  ONE_OF_THE_LADS = "one_of_the_lads",
  KINGPIN = "kingpin",
  HERALD_OF_JUSTICE = "herald_of_justice",
  SEEKER = "seeker",
  BATTLE_SYSTEMS_MASTER = "battle_systems_master",
  HIGH_TECH_MASTER = "high_tech_master",
  SKILLED_STALKER = "skilled_stalker",
  LEADER = "leader",
  DIPLOMAT = "diplomat",
  RESEARCH_MAN = "research_man",
  FRIEND_OF_DUTY = "friend_of_duty",
  FRIEND_OF_FREEDOM = "friend_of_freedom",
  BALANCE_ADVOCATE = "balance_advocate",
  WEALTHY = "wealthy",
  KEEPER_OF_SECRETS = "keeper_of_secrets",
  MARKED_BY_ZONE = "marked_by_zone",
  INFORMATION_DEALER = "information_dealer",
  FRIEND_OF_STALKERS = "friend_of_stalkers",
}
