import { anim, CSightParams, move } from "xray16";

import { EWeaponAnimation } from "@/engine/core/objects/state/animation_types";
import { EStalkerState, IStateDescriptor } from "@/engine/core/objects/state/state_types";
import { TName } from "@/engine/lib/types";

/**
 * todo;
 */
export const animpointStates: LuaTable<TName, IStateDescriptor> = $fromObject<TName, IStateDescriptor>({
  animpoint_stay_wall: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.ANIMPOINT_STAY_WALL,
    animation: EStalkerState.ANIMPOINT_STAY_WALL,
    direction: CSightParams.eSightTypeAnimationDirection,
    isForced: null,
  },
  animpoint_stay_table: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_stay_table",
    animation: "animpoint_stay_table",
    direction: CSightParams.eSightTypeAnimationDirection,
    isForced: null,
  },
  animpoint_sit_high: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_high",
    animation: "animpoint_sit_high",
    direction: CSightParams.eSightTypeAnimationDirection,
    isForced: null,
  },
  animpoint_sit_normal: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_normal",
    animation: "animpoint_sit_normal",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_low: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_low",
    animation: "animpoint_sit_low",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_ass: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_ass",
    animation: "animpoint_sit_ass",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_knee: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_knee",
    animation: "animpoint_sit_knee",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_wall_eat_bread: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.ANIMPOINT_STAY_WALL,
    animation: "animpoint_stay_wall_eat_bread",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_wall_eat_kolbasa: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.ANIMPOINT_STAY_WALL,
    animation: "animpoint_stay_wall_eat_kolbasa",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_table_eat_bread: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_stay_table",
    animation: "animpoint_stay_table_eat_bread",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_table_eat_kolbasa: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_stay_table",
    animation: "animpoint_stay_table_eat_kolbasa",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_high_eat_bread: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_high",
    animation: "animpoint_sit_high_eat_bread",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_high_eat_kolbasa: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_high",
    animation: "animpoint_sit_high_eat_kolbasa",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_normal_eat_bread: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_normal",
    animation: "animpoint_sit_normal_eat_bread",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_normal_eat_kolbasa: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_normal",
    animation: "animpoint_sit_normal_eat_kolbasa",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_low_eat_bread: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_low",
    animation: "animpoint_sit_low_eat_bread",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_low_eat_kolbasa: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_low",
    animation: "animpoint_sit_low_eat_kolbasa",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_ass_eat_bread: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_ass",
    animation: "animpoint_sit_ass_eat_bread",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_ass_eat_kolbasa: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_ass",
    animation: "animpoint_sit_ass_eat_kolbasa",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_knee_eat_bread: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_ass",
    animation: "animpoint_sit_ass_eat_bread",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_knee_eat_kolbasa: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_ass",
    animation: "animpoint_sit_ass_eat_kolbasa",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_wall_drink_vodka: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.ANIMPOINT_STAY_WALL,
    animation: "animpoint_stay_wall_drink_vodka",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_wall_drink_energy: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.ANIMPOINT_STAY_WALL,
    animation: "animpoint_stay_wall_drink_energy",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_table_drink_vodka: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_stay_table",
    animation: "animpoint_stay_table_drink_vodka",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_table_drink_energy: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_stay_table",
    animation: "animpoint_stay_table_drink_energy",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_high_drink_vodka: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_high",
    animation: "animpoint_sit_high_drink_vodka",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_high_drink_energy: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_high",
    animation: "animpoint_sit_high_drink_energy",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_normal_drink_vodka: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_normal",
    animation: "animpoint_sit_normal_drink_vodka",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_normal_drink_energy: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_normal",
    animation: "animpoint_sit_normal_drink_energy",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_low_drink_vodka: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_low",
    animation: "animpoint_sit_low_drink_vodka",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_low_drink_energy: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_low",
    animation: "animpoint_sit_low_drink_energy",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_ass_drink_vodka: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_ass",
    animation: "animpoint_sit_ass_drink_vodka",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_ass_drink_energy: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_ass",
    animation: "animpoint_sit_ass_drink_energy",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_knee_drink_vodka: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_ass",
    animation: "animpoint_sit_ass_drink_vodka",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_knee_drink_energy: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_ass",
    animation: "animpoint_sit_ass_drink_energy",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_wall_guitar: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.ANIMPOINT_STAY_WALL,
    animation: "animpoint_stay_wall_guitar",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_table_guitar: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_stay_table",
    animation: "animpoint_stay_table_guitar",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_high_guitar: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_high",
    animation: "animpoint_sit_high_guitar",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_normal_guitar: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_normal",
    animation: "animpoint_sit_normal_guitar",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_low_guitar: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_low",
    animation: "animpoint_sit_low_guitar",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_ass_guitar: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_ass",
    animation: "animpoint_sit_ass_guitar",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_knee_guitar: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_ass",
    animation: "animpoint_sit_ass_guitar",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_wall_harmonica: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.ANIMPOINT_STAY_WALL,
    animation: "animpoint_stay_wall_harmonica",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_table_harmonica: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_stay_table",
    animation: "animpoint_stay_table_harmonica",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_high_harmonica: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_high",
    animation: "animpoint_sit_high_harmonica",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_normal_harmonica: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_normal",
    animation: "animpoint_sit_normal_harmonica",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_low_harmonica: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_low",
    animation: "animpoint_sit_low_harmonica",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_ass_harmonica: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_ass",
    animation: "animpoint_sit_ass_harmonica",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_knee_harmonica: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_ass",
    animation: "animpoint_sit_ass_harmonica",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_wall_weapon: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_stay_wall_weapon",
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_stay_table_weapon: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.ANIMPOINT_STAY_TABLE_WEAPON,
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_high_weapon: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.ANIMPOINT_SIT_HIGH_WEAPON,
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_normal_weapon: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.ANIMPOINT_SIT_NORMAL_WEAPON,
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
    isForced: null,
  },
  animpoint_sit_low_weapon: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.ANIMPOINT_SIT_LOW_WEAPON,
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
    isForced: null,
  },
  animpoint_stay_wall_no_rnd: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.ANIMPOINT_STAY_WALL,
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
    isForced: null,
  },
  animpoint_stay_table_no_rnd: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_stay_table",
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_high_no_rnd: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_high",
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_normal_no_rnd: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_normal",
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  animpoint_sit_low_no_rnd: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_low",
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
});
