import { anim, CSightParams, look, move } from "xray16";

import { EWeaponAnimation } from "@/engine/core/objects/state/animation_types";
import { EStalkerState, IStateDescriptor } from "@/engine/core/objects/state/state_types";
import { TName } from "@/engine/lib/types";

/**
 * List of default state descriptors to use in scripts.
 * todo: Enum values as keys?
 */
export const baseStates: LuaTable<TName, IStateDescriptor> = $fromObject<TName, IStateDescriptor>({
  [EStalkerState.IDLE]: {
    weapon: null,
    movement: null,
    mental: null,
    bodystate: null,
    animstate: null,
    animation: null,
    isForced: null,
  },
  [EStalkerState.SMART_COVER]: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: null,
    mental: null,
    bodystate: null,
    animstate: null,
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
    isForced: null,
  },
  [EStalkerState.WALK]: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.walk,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  walk_noweap: {
    weapon: EWeaponAnimation.NONE,
    movement: move.walk,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  run: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.run,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  sprint: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.run,
    mental: anim.panic,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  patrol: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.walk,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  patrol_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.walk,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  raid: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.walk,
    mental: anim.danger,
    special_danger_move: true,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  raid_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.walk,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  sneak: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.walk,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
    isForced: null,
  },
  sneak_run: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.run,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
    isForced: null,
  },
  sneak_no_wpn: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.walk,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
    isForced: null,
  },
  sneak_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.walk,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
    isForced: null,
  },
  assault: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.run,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  assault_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.run,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  rush: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.run,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  wait: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.IDLE,
    isForced: null,
  },
  wait_trade: {
    weapon: EWeaponAnimation.NONE,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.IDLE,
    isForced: null,
  },
  wait_na: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  guard: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.IDLE,
    isForced: null,
  },
  guard_chasovoy: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.IDLE_CHASOVOY,
    isForced: null,
  },
  guard_na: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  guard_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  threat: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: true,
  },
  threat_danger: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.BLOODSUCKER_SEARCH,
    isForced: null,
  },
  give_orders: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.GIVE_ORDERS,
    isForced: null,
  },
  threat_heli: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  threat_na: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: true,
  },
  threat_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  threat_sniper_fire: {
    weapon: EWeaponAnimation.SNIPER_FIRE,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: null,
    isForced: null,
  },
  hide: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: EStalkerState.HIDE,
    isForced: null,
  },
  hide_na: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
    isForced: null,
  },
  hide_fire: {
    weapon: EWeaponAnimation.FIRE,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
    isForced: null,
  },
  hide_sniper_fire: {
    weapon: EWeaponAnimation.SNIPER_FIRE,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: null,
    isForced: null,
  },
  caution: {
    weapon: null,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.CAUTION,
    isForced: null,
  },
  choose: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.CHOOSING,
    isForced: null,
  },
  press: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PRESS,
    isForced: null,
  },
  ward: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.WARDING,
    isForced: null,
  },
  ward_short: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.WARDING_SHORT,
    isForced: null,
  },
  ward_noweap: {
    weapon: EWeaponAnimation.NONE,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.WARDING,
    isForced: null,
  },
  ward_noweap_short: {
    weapon: EWeaponAnimation.NONE,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.WARDING_SHORT,
    isForced: null,
  },
  fold_arms: {
    weapon: EWeaponAnimation.NONE,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.FOLD_ARMS,
    isForced: null,
  },
  search: {
    weapon: null,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.POISK,
    isForced: null,
  },
  stoop_no_weap: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.STOOP_NO_WEAP,
    isForced: null,
  },
  salut: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.SALUT,
    isForced: null,
  },
  salut_free: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.SALUT_FREE,
    isForced: null,
  },
  prisoner: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: null,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PRISONER,
    isForced: null,
  },
  hide_no_wpn: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: EStalkerState.HIDE,
    isForced: null,
  },
  // -- sit
  sit: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.SIT,
    animation: null,
    isForced: null,
  },
  sit_knee: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.SIT_KNEE,
    animation: null,
    isForced: null,
  },
  sit_ass: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.SIT_ASS,
    animation: null,
    isForced: null,
  },
  sleep_sit: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.SIT_ASS,
    animation: EStalkerState.SLEEP_SIT,
    isForced: null,
  },
  eat_bread: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.SIT_KNEE,
    animation: EStalkerState.EAT_BREAD,
    isForced: null,
  },
  eat_vodka: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.SIT_ASS,
    animation: EStalkerState.EAT_VODKA,
    isForced: null,
  },
  eat_energy: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.SIT_ASS,
    animation: EStalkerState.EAT_ENERGY,
    isForced: null,
  },
  eat_kolbasa: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.SIT_ASS,
    animation: EStalkerState.EAT_KOLBASA,
    isForced: null,
  },
  play_guitar: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.SIT_KNEE,
    animation: EStalkerState.PLAY_GUITAR,
    isForced: null,
  },
  play_harmonica: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: EStalkerState.SIT_ASS,
    animation: EStalkerState.PLAY_HARMONICA,
    isForced: null,
  },
  sleep: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.SLEEPING,
    isForced: null,
  },
  hello: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.HELLO,
    isForced: null,
  },
  hello_wpn: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.HELLO,
    isForced: null,
  },
  refuse: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.REFUSE,
    isForced: null,
  },
  claim: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.CLAIM,
    isForced: null,
  },
  backoff: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.BACKOFF,
    isForced: null,
  },
  backoff2: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.BACKOFF,
    isForced: null,
  },
  punch: {
    weapon: null,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PUNCH,
    isForced: null,
  },
  search_corpse: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: EStalkerState.SEARCH_CORPSE,
    isForced: null,
  },
  help_wounded: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: EStalkerState.HELP_WOUNDED,
    isForced: null,
  },
  dynamite: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: EStalkerState.DYNAMITE,
    isForced: null,
  },
  binocular: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.BINOCULAR,
    isForced: null,
  },
  hide_rac: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    animstate: null,
    animation: EStalkerState.CR_RACIYA,
    isForced: null,
  },
  wait_rac: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.RACIYA,
    isForced: null,
  },
  wait_rac_noweap: {
    weapon: EWeaponAnimation.NONE,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.RACIYA,
    isForced: null,
  },
  wait_rac_stc: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.RACIYA_STC,
    isForced: null,
  },
  guard_rac: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.RACIYA,
    isForced: null,
  },
  probe_stand: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PROBE_STAND,
    isForced: null,
  },
  probe_stand_detector_advanced: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PROBE_STAND_DETECTOR_ADVANCED,
    isForced: null,
  },
  probe_stand_detector_elite: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PROBE_STAND_DETECTOR_ELITE,
    isForced: null,
  },
  probe_way: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PROBE_WAY,
    isForced: null,
  },
  probe_way_detector_advanced: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PROBE_WAY_DETECTOR_ADVANCED,
    isForced: null,
  },
  probe_way_detector_elite: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PROBE_WAY_DETECTOR_ELITE,
    isForced: null,
  },
  probe_crouch: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PROBE_CROUCH,
    isForced: null,
  },
  probe_crouch_detector_advanced: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PROBE_CROUCH_DETECTOR_ADVANCED,
    isForced: null,
  },
  probe_crouch_detector_elite: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PROBE_CROUCH_DETECTOR_ELITE,
    isForced: null,
  },
  scaner_stand: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.SCANER_STAND,
    isForced: null,
  },
  scaner_way: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.SCANER_WAY,
    isForced: null,
  },
  scaner_crouch: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.SCANER_CROUCH,
    isForced: null,
  },
  hands_up: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.HANDS_UP,
    isForced: null,
  },
  // -- Wounded
  wounded: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    direction: look.cur_dir,
    animstate: null,
    animation: EStalkerState.WOUNDED,
    isForced: null,
  },
  wounded_heavy: {
    weapon: EWeaponAnimation.DROP,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    direction: look.cur_dir, // --CSightParams.eSightTypeAnimationDirection
    animstate: null,
    animation: EStalkerState.WOUNDED_HEAVY_1,
    isForced: null,
  },
  wounded_heavy_2: {
    weapon: EWeaponAnimation.DROP,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    direction: look.cur_dir,
    animstate: null,
    animation: EStalkerState.WOUNDED_HEAVY_2,
    isForced: null,
  },
  wounded_heavy_3: {
    weapon: EWeaponAnimation.DROP,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    direction: look.cur_dir,
    animstate: null,
    animation: EStalkerState.WOUNDED_HEAVY_3,
    isForced: null,
  },
  wounded_zombie: {
    weapon: EWeaponAnimation.DROP,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    direction: look.cur_dir,
    animstate: null,
    animation: EStalkerState.WOUNDED_ZOMBIE,
    isForced: null,
  },
  trans_0: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.TRANS_0,
    isForced: null,
  },
  trans_1: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.TRANS_1,
    isForced: null,
  },
  trans_zombied: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.TRANS_ZOMBIED,
    isForced: null,
  },
  talk_default: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.TALK_DEFAULT,
    isForced: null,
  },
  psy_pain: {
    weapon: EWeaponAnimation.DROP,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PSY_ARMED,
    isForced: null,
  },
  psy_armed: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PSY_ARMED,
    isForced: null,
  },
  psy_shoot: {
    weapon: EWeaponAnimation.FIRE,
    weapon_slot: 1,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: EStalkerState.PSY_SHOOT,
    isForced: null,
  },
  lay_on_bed: {
    weapon: EWeaponAnimation.DROP,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.crouch,
    direction: look.cur_dir,
    animstate: null,
    animation: EStalkerState.WOUNDED_HEAVY_1,
    isForced: null,
  },
});
