import { anim, CSightParams, move } from "xray16";

import { EWeaponAnimation, IStateDescriptor } from "@/engine/core/objects/state/state_types";
import { TName } from "@/engine/lib/types";

/**
 * todo;
 */
export const scenarioStates: LuaTable<TName, IStateDescriptor> = {
  zat_b14_give_artefact_idle: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b14_give_artefact_idle",
  },
  zat_b14_give_artefact_act: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b14_give_artefact_act",
  },
  zat_b14_stay_wall: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b14_stay_wall",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b38_stalker_break_lock: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b38_stalker_break_lock",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b38_stalker_turn_on_lift: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b38_stalker_turn_on_lift",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b38_stalker_jump_tonnel: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b38_stalker_jump_tonnel",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b38_stalker_alert: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b38_stalker_alert",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b20_noah_jump: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b20_noah_jump",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pri_a17_ice_climb: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "pri_a17_ice_climb",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pri_a17_fall_down: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "pri_a17_fall_down",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pri_a17_pray_in: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "pri_a17_pray_in",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pri_a17_pray: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "pri_a17_pray",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b22_medic_turn_idle: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "zat_b22_medic_turn_idle",
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b22_medic_turn_out: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b22_medic_turn_out",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b22_medic_suicide: {
    weapon: "fire",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b22_medic_suicide",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b3_tech_drunk: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "zat_b3_tech_idle",
    animation: "zat_b3_tech_drunk",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b3_tech_drink: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "zat_b3_tech_idle",
    animation: "zat_b3_tech_drink",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b3_tech_idle: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "zat_b3_tech_idle",
    animation: "zat_b3_tech_idle_1",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b3_tech_idle_short: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "zat_b3_tech_idle",
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b3_tech_surprise: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "zat_b3_tech_idle",
    animation: "zat_b3_tech_surprise",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  give_orders: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "give_orders",
  },
  bloodsucker_search: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "bloodsucker_search",
  },
  bloodsucker_panic: {
    weapon: "fire",
    movement: move.stand,
    mental: anim.danger,
    bodystate: move.standing,
    animstate: null,
    animation: "bloodsucker_panic",
  },
  suicide_animation: {
    weapon: "fire",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "suicide_animation",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b10_drunk_ravings: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b10_drunk_ravings",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pas_b400_vano_probe: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "pas_b400_vano_probe",
  },
  pri_a28_kirillov_sit_high_radio: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "animpoint_sit_high",
    animation: "pri_a28_kirillov_sit_high_radio",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pri_a18_inspert_monolit_actor: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "pri_a18_inspert_monolit_actor",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pri_a20_colonel_radio: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "pri_a20_colonel_radio",
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pri_a21_sentry_madness: {
    weapon: "fire",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "pri_a21_sentry_madness_idle",
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pri_a21_sentry_madness_suicide: {
    weapon: "fire",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "pri_a21_sentry_madness_idle",
    animation: "pri_a21_sentry_madness_suicide",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pri_a22_colonel_lean_on_table: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "pri_a22_colonel_lean_on_table",
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pri_a28_army_trance_out: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "pri_a28_army_trance_out",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b106_wounded_idle: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b106_wounded_idle",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b38_cop_dead: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b38_cop_dead",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b15_zulus_sit_drink: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "jup_b15_zulus_sit_idle_short",
    animation: "jup_b15_zulus_sit_drink",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b15_zulus_sit_idle: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "jup_b15_zulus_sit_idle_short",
    animation: "jup_b15_zulus_sit_idle",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b15_zulus_sit_idle_short: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: "jup_b15_zulus_sit_idle_short",
    animation: null,
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b15_zulus_sit_out: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b15_zulus_sit_out",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_actor_one: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_actor_one",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_actor_one_vano: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_actor_one_vano",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_actor_one_monolith: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_actor_one_monolith",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_actor_one_soldier: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_actor_one_soldier",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_actor_all: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_actor_all",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_actor_soldier_vano: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_actor_soldier_vano",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_actor_soldier_monolith: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_actor_soldier_monolith",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_actor_vano_monolith: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_actor_vano_monolith",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_zulus_one: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_zulus_one",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_zulus_one_vano: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_zulus_one_vano",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_zulus_one_monolith: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_zulus_one_monolith",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_zulus_one_soldier: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_zulus_one_soldier",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_zulus_all: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_zulus_all",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_zulus_soldier_vano: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_zulus_soldier_vano",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_zulus_soldier_monolith: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_zulus_soldier_monolith",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_zulus_vano_monolith: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_zulus_vano_monolith",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_soldier_one: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_soldier_one",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_soldier_all: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_soldier_all",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_soldier_soldier_vano: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_soldier_soldier_vano",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_soldier_soldier_monolith: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_soldier_soldier_monolith",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_monolith_one: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_monolith_one",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_monolith_all: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_monolith_all",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_monolith_soldier_monolith: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_monolith_soldier_monolith",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_monolith_vano_monolith: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_monolith_vano_monolith",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_vano_one: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_vano_one",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_vano_all: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_vano_all",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_vano_soldier_vano: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_vano_soldier_vano",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_vano_vano_monolith: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_vano_vano_monolith",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_azot_one: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_azot_one",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_azot_one_vano: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_azot_one_vano",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_azot_one_monolith: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_azot_one_monolith",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_azot_one_soldier: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_azot_one_soldier",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_azot_soldier_vano: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_azot_soldier_vano",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_azot_soldier_monolith: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_azot_soldier_monolith",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_azot_vano_monolith: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_azot_vano_monolith",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b219_azot_all: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b219_azot_all",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b100_heli_2_serch: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b100_heli_2_serch",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b101_heli_5_serch: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b101_heli_5_serch",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  zat_b28_heli3_serch: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "zat_b28_heli3_serch",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b217_guide_stand: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b217_guide_stand",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b217_nitro_stand: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b217_nitro_stand",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b41_novikov_stand: {
    weapon: "none",
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b41_novikov_stand",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pri_b305_actor: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "pri_b305_actor",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_a9_cam1_actor: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_a9_cam1_actor",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_a9_cam2_actor: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_a9_cam2_actor",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_a9_cam3_actor: {
    weapon: EWeaponAnimation.UNSTRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_a9_cam3_actor",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  jup_b217_nitro_straight: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "jup_b217_nitro_straight",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pri_a25_psy_medic_idle: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "pri_a25_psy_medic_idle",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
  pri_a25_psy_medic_out: {
    weapon: EWeaponAnimation.STRAPPED,
    movement: move.stand,
    mental: anim.free,
    bodystate: move.standing,
    animstate: null,
    animation: "pri_a25_psy_medic_out",
    direction: CSightParams.eSightTypeAnimationDirection,
  },
} as any;
