/* eslint sort-keys-fix/sort-keys-fix: "error" */

export const quest_items = {
  device_flash_snag: "device_flash_snag",
  device_pda_port_bandit_leader: "device_pda_port_bandit_leader",
  device_pda_zat_b5_dealer: "device_pda_zat_b5_dealer",
  helm_hardhat_snag: "helm_hardhat_snag",
  jup_a9_conservation_info: "jup_a9_conservation_info",
  jup_a9_delivery_info: "jup_a9_delivery_info",
  jup_a9_evacuation_info: "jup_a9_evacuation_info",
  jup_a9_losses_info: "jup_a9_losses_info",
  jup_a9_meeting_info: "jup_a9_meeting_info",
  jup_a9_power_info: "jup_a9_power_info",
  jup_a9_way_info: "jup_a9_way_info",
  jup_b10_notes_01: "jup_b10_notes_01",
  jup_b10_notes_02: "jup_b10_notes_02",
  jup_b10_notes_03: "jup_b10_notes_03",
  jup_b10_ufo_memory: "jup_b10_ufo_memory",
  jup_b10_ufo_memory_2: "jup_b10_ufo_memory_2",
  jup_b1_half_artifact: "jup_b1_half_artifact",
  jup_b200_tech_materials_acetone: "jup_b200_tech_materials_acetone",
  jup_b200_tech_materials_capacitor: "jup_b200_tech_materials_capacitor",
  jup_b200_tech_materials_textolite: "jup_b200_tech_materials_textolite",
  jup_b200_tech_materials_transistor: "jup_b200_tech_materials_transistor",
  jup_b200_tech_materials_wire: "jup_b200_tech_materials_wire",
  jup_b202_bandit_pda: "jup_b202_bandit_pda",
  jup_b205_sokolov_note: "jup_b205_sokolov_note",
  jup_b206_plant: "jup_b206_plant",
  jup_b207_merc_pda_with_contract: "jup_b207_merc_pda_with_contract",
  jup_b209_monster_scanner: "jup_b209_monster_scanner",
  jup_b32_scanner_device: "jup_b32_scanner_device",
  jup_b46_duty_founder_pda: "jup_b46_duty_founder_pda",
  jup_b47_jupiter_products_info: "jup_b47_jupiter_products_info",
  jup_b47_merc_pda: "jup_b47_merc_pda",
  jup_b9_blackbox: "jup_b9_blackbox",
  pri_a17_gauss_rifle: "pri_a17_gauss_rifle",
  pri_b306_envoy_pda: "pri_b306_envoy_pda",
  pri_b36_monolith_hiding_place_pda: "pri_b36_monolith_hiding_place_pda",
  wpn_ak74u_snag: "wpn_ak74u_snag",
  wpn_fort_snag: "wpn_fort_snag",
  zat_a23_access_card: "zat_a23_access_card",
  zat_a23_gauss_rifle_docs: "zat_a23_gauss_rifle_docs",
  zat_b12_documents_1: "zat_b12_documents_1",
  zat_b12_documents_2: "zat_b12_documents_2",
  zat_b12_documents_3: "zat_b12_documents_3",
  zat_b20_noah_pda: "zat_b20_noah_pda",
  zat_b33_safe_container: "zat_b33_safe_container",
  zat_b39_joker_pda: "zat_b39_joker_pda",
  zat_b40_notebook: "zat_b40_notebook",
  zat_b40_pda_1: "zat_b40_pda_1",
  zat_b40_pda_2: "zat_b40_pda_2",
  zat_b44_barge_pda: "zat_b44_barge_pda",
  zat_b57_gas: "zat_b57_gas",
} as const;

export type TQuestItems = typeof quest_items;

export type TQuestItem = TQuestItems[keyof TQuestItems];
