export const combatConfig = {
  ATTACK_DISTANCE_SQR: 60 * 60,
  BULLET_REACT_DISTANCE_SQR: 2 * 2,
  ALLIES_SHOOTING_ASSIST_DISTANCE_SQR: 40 * 40,
  MONSTER_REACT_DISTANCE_SQR: 30 * 30,
  BULLET_CONFUSED_DISTANCE_SQR: 50 * 50,
  POST_COMBAT_IDLE: {
    MIN: 5,
    MAX: 10,
  },
  LAST_SEEN_POSITION_TIMEOUT: 30_000,
  SEARCH_DIRECTION_CHANGE_TIMEOUT: 10_000,
  SEARCH_DIRECTION_ROTATION_RANGE: { MIN: -120, MAX: 120 }, // min-max angle to change when searching for target.
  SEARCH_DIRECTION_CHANGE_PERIOD: { MIN: 2000, MAX: 4000 },
};
