import * as fs from "node:fs";
import * as path from "node:path";

import { blueBright, green, greenBright, red, yellow, yellowBright } from "chalk";
import * as tstl from "typescript-to-lua";

import { discoverChecks, ICheckDescriptor } from "#/checks/utils/discover_checks";
import { BUILD_CHECKS_TSCONFIG, TARGET_GAME_DATA_CHECKS_DIR, TARGET_GAME_DATA_SCRIPTS_DIR } from "#/globals/paths";
import { NodeLogger } from "#/utils/logging";
import { TimeTracker } from "#/utils/timing";

const log: NodeLogger = NodeLogger.forFile(__filename);

export interface IBuildChecksParameters {
  verbose?: boolean;
}

/**
 * Transpile checks into gamedata and emit a console launcher for each one.
 *
 * Checks live outside the regular script build, so nothing here affects normal build or watch
 * timings. Running this command is the only way check code reaches gamedata.
 */
export async function buildChecks(parameters: IBuildChecksParameters = {}): Promise<void> {
  NodeLogger.IS_VERBOSE = Boolean(parameters.verbose);

  log.info(blueBright("Build checks"));

  const timeTracker: TimeTracker = new TimeTracker().start();
  const checks: Array<ICheckDescriptor> = discoverChecks();

  if (!checks.length) {
    return log.warn("No checks found, nothing to build");
  }

  log.info("Discovered checks:", checks.length);

  transpileChecks();
  timeTracker.addMark("CHECKS_TRANSPILED");

  emitLaunchers(checks);
  timeTracker.addMark("CHECKS_LAUNCHERS");

  log.info("Checks built in", timeTracker.end().getDuration() / 1000, "sec");
  log.pushNewLine();
  log.info("Run in game console (engine variant must be", yellowBright("mixed"), "or", yellowBright("release") + "):");

  for (const check of checks) {
    log.info(" ", greenBright(check.command), green(`(${check.relative})`));
  }
}

/**
 * Flatten a possibly chained diagnostic message into readable text.
 */
function flattenDiagnostic(message: string | { messageText: string; next?: Array<unknown> }): string {
  return typeof message === "string" ? message : message.messageText;
}

/**
 * Transpile the checks project into gamedata.
 */
function transpileChecks(): void {
  const result = tstl.transpileProject(BUILD_CHECKS_TSCONFIG, { noHeader: true, tstlVerbose: false });

  if (result.diagnostics?.length) {
    result.diagnostics.forEach((it) => {
      log.error(red("Lua issue:"), it.code, yellowBright(it.file?.fileName), red(flattenDiagnostic(it.messageText)));
    });

    throw new Error(
      `Checks transpiling failed with ${result.diagnostics.length} issue(s). Use ${yellow(
        "'npm run typecheck:checks'"
      )} for investigation.`
    );
  }
}

/**
 * Write one launcher script per check into `$game_scripts$`.
 *
 * The launcher exists purely so `run_script` can find and tab-complete the check: the console
 * command resolves a flat file name under `gamedata/scripts` and cannot address a nested module.
 * Clearing `package.loaded` first means a rebuild takes effect without restarting the game, since
 * `run_script` reloads the launcher but would otherwise reuse the cached check module.
 */
function emitLaunchers(checks: Array<ICheckDescriptor>): void {
  fs.mkdirSync(TARGET_GAME_DATA_SCRIPTS_DIR, { recursive: true });

  for (const check of checks) {
    const emittedPath: string = path.resolve(TARGET_GAME_DATA_CHECKS_DIR, check.emitted);

    // Guard against the transpiler changing how it derives emitted file names: a launcher
    // pointing at a module that does not exist would only fail once typed into the console.
    if (!fs.existsSync(emittedPath)) {
      throw new Error(
        `Expected transpiled check at '${emittedPath}' for source '${check.relative}'. ` +
          `Emitted file naming changed, launcher module '${check.module}' would not resolve.`
      );
    }

    const body: string =
      `-- Generated by 'xrf checks build'. Do not edit.\n` +
      `-- Launcher for ${check.relative}, run with: ${check.command}\n` +
      `package.loaded["${check.module}"] = nil\n` +
      `require("${check.module}").run()\n`;

    fs.writeFileSync(path.resolve(TARGET_GAME_DATA_SCRIPTS_DIR, check.launcher), body, "utf8");

    log.debug("Emitted launcher:", check.launcher, "->", check.module);
  }

  log.info("Emitted launchers:", checks.length, green(TARGET_GAME_DATA_CHECKS_DIR));
}
