name: build-and-test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]
        shard: [1, 2, 3, 4, 5, 6]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run setup

      - name: Restore jest cache
        id: cache-jest-restore
        uses: actions/cache/restore@v4
        with:
          path: /tmp/jest_rt
          key: jest-${{ hashFiles('**/package-lock.json') }}-${{ matrix.shard }}

      - run: npm run test -- --shard=${{ matrix.shard }}/${{ strategy.job-total }} --maxWorkers=100%

      - name: Save jest cache
        if: ${{ steps.cache-jest-restore.outputs.cache-hit != 'true' && github.event_name != 'pull_request' }}
        id: cache-jest-save
        uses: actions/cache/save@v4
        with:
          path: /tmp/jest_rt
          key: ${{ steps.cache-jest-restore.outputs.cache-primary-key }}

      - run: mv target/coverage_report/coverage-final.json target/coverage_report/${{matrix.shard}}.json

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts-${{matrix.shard}}
          path: target/coverage_report/${{matrix.shard}}.json

  report-coverage:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: coverage-artifacts-*
          merge-multiple: true
          path: target/coverage_report

      - name: Merge code coverage
        run: npx nyc merge target/coverage_report/ target/coverage-report/coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/coverage_report/coverage-final.json

  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Restore eslint cache
        id: cache-eslint-restore
        uses: actions/cache/restore@v4
        with:
          path: target/eslint
          key: eslint-${{ hashFiles('**/package-lock.json') }}-${{ matrix.shard }}

      - run: npm ci
      - run: npm run setup
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run cli format ltx -- --check
      - run: npm run cli verify ltx

      - name: Save eslint cache
        if: ${{ steps.cache-eslint-restore.outputs.cache-hit != 'true' && github.event_name != 'pull_request' }}
        id: cache-eslint-save
        uses: actions/cache/save@v4
        with:
          path: target/eslint
          key: ${{ steps.cache-eslint-restore.outputs.cache-primary-key }}

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run setup
      - run: npm run pack:mod -- --se

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Move build statics
        run: |
          mv target/xrf_build.log target/mod_package/xrf_build.log
          mv target/README.md target/mod_package/README.md

      - name: Archive build artifacts
        working-directory: target/mod_package
        run: zip -qq -r gamedata.release.zip gamedata/ bin/ xrf_build.log README.md

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: gamedata-release
          path: target/mod_package/gamedata.release.zip
          retention-days: 1

  upload-nightly:
    if: ${{ github.ref_name == 'main' && github.event_name != 'pull_request' }}
    needs: [test, check, build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: gamedata-release

      - name: Update nightly tag
        uses: EndBug/latest-tag@latest
        id: update-nightly-tag
        with:
          ref: nightly

      - name: Publish nightly gamedata build
        if: ${{ steps.update-nightly-tag.outcome == 'success' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload --clobber nightly gamedata.release.zip
